/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IAnimalNoDomicilioThriftArgs {
    animal?: number | Int64;
    quantidade?: number;
}
export class AnimalNoDomicilioThrift {
    public animal?: Int64;
    public quantidade?: number;
    constructor(args?: IAnimalNoDomicilioThriftArgs) {
        if (args != null && args.animal != null) {
            if (typeof args.animal === "number") {
                this.animal = new Int64(args.animal);
            }
            else {
                this.animal = args.animal;
            }
        }
        if (args != null && args.quantidade != null) {
            this.quantidade = args.quantidade;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("AnimalNoDomicilioThrift");
        if (this.animal != null) {
            output.writeFieldBegin("animal", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.animal);
            output.writeFieldEnd();
        }
        if (this.quantidade != null) {
            output.writeFieldBegin("quantidade", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.quantidade);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): AnimalNoDomicilioThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.animal = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.quantidade = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new AnimalNoDomicilioThrift(_args);
    }
}
