/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as AnimalNoDomicilioThrift from "./AnimalNoDomicilioThrift";
import * as CondicaoMoradiaThrift from "./CondicaoMoradiaThrift";
import * as EnderecoLocalPermanenciaThrift from "./EnderecoLocalPermanenciaThrift";
import * as FamiliaRowThrift from "./FamiliaRowThrift";
import * as InstituicaoPermanenciaThrift from "./InstituicaoPermanenciaThrift";
import * as VariasLotacoesHeaderThrift from "./VariasLotacoesHeaderThrift";
export interface ICadastroDomiciliarThriftArgs {
    animaisNoDomicilio?: Array<AnimalNoDomicilioThrift.AnimalNoDomicilioThrift>;
    condicaoMoradia?: CondicaoMoradiaThrift.CondicaoMoradiaThrift;
    enderecoLocalPermanencia?: EnderecoLocalPermanenciaThrift.EnderecoLocalPermanenciaThrift;
    familias?: Array<FamiliaRowThrift.FamiliaRowThrift>;
    fichaAtualizada?: boolean;
    quantosAnimaisNoDomicilio?: number;
    stAnimaisNoDomicilio?: boolean;
    statusTermoRecusa?: boolean;
    tpCdsOrigem?: number;
    uuid: string;
    uuidFichaOriginadora?: string;
    tipoDeImovel?: number | Int64;
    instituicaoPermanencia?: InstituicaoPermanenciaThrift.InstituicaoPermanenciaThrift;
    headerTransport?: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    latitude?: number;
    longitude?: number;
    tipoEndereco?: number | Int64;
}
export class CadastroDomiciliarThrift {
    public animaisNoDomicilio?: Array<AnimalNoDomicilioThrift.AnimalNoDomicilioThrift>;
    public condicaoMoradia?: CondicaoMoradiaThrift.CondicaoMoradiaThrift;
    public enderecoLocalPermanencia?: EnderecoLocalPermanenciaThrift.EnderecoLocalPermanenciaThrift;
    public familias?: Array<FamiliaRowThrift.FamiliaRowThrift>;
    public fichaAtualizada?: boolean;
    public quantosAnimaisNoDomicilio?: number;
    public stAnimaisNoDomicilio?: boolean;
    public statusTermoRecusa?: boolean;
    public tpCdsOrigem?: number;
    public uuid: string;
    public uuidFichaOriginadora?: string;
    public tipoDeImovel?: Int64;
    public instituicaoPermanencia?: InstituicaoPermanenciaThrift.InstituicaoPermanenciaThrift;
    public headerTransport?: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    public latitude?: number;
    public longitude?: number;
    public tipoEndereco?: Int64;
    constructor(args: ICadastroDomiciliarThriftArgs) {
        if (args != null && args.animaisNoDomicilio != null) {
            this.animaisNoDomicilio = args.animaisNoDomicilio;
        }
        if (args != null && args.condicaoMoradia != null) {
            this.condicaoMoradia = args.condicaoMoradia;
        }
        if (args != null && args.enderecoLocalPermanencia != null) {
            this.enderecoLocalPermanencia = args.enderecoLocalPermanencia;
        }
        if (args != null && args.familias != null) {
            this.familias = args.familias;
        }
        if (args != null && args.fichaAtualizada != null) {
            this.fichaAtualizada = args.fichaAtualizada;
        }
        if (args != null && args.quantosAnimaisNoDomicilio != null) {
            this.quantosAnimaisNoDomicilio = args.quantosAnimaisNoDomicilio;
        }
        if (args != null && args.stAnimaisNoDomicilio != null) {
            this.stAnimaisNoDomicilio = args.stAnimaisNoDomicilio;
        }
        if (args != null && args.statusTermoRecusa != null) {
            this.statusTermoRecusa = args.statusTermoRecusa;
        }
        if (args != null && args.tpCdsOrigem != null) {
            this.tpCdsOrigem = args.tpCdsOrigem;
        }
        if (args != null && args.uuid != null) {
            this.uuid = args.uuid;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[uuid] is unset!");
        }
        if (args != null && args.uuidFichaOriginadora != null) {
            this.uuidFichaOriginadora = args.uuidFichaOriginadora;
        }
        if (args != null && args.tipoDeImovel != null) {
            if (typeof args.tipoDeImovel === "number") {
                this.tipoDeImovel = new Int64(args.tipoDeImovel);
            }
            else {
                this.tipoDeImovel = args.tipoDeImovel;
            }
        }
        if (args != null && args.instituicaoPermanencia != null) {
            this.instituicaoPermanencia = args.instituicaoPermanencia;
        }
        if (args != null && args.headerTransport != null) {
            this.headerTransport = args.headerTransport;
        }
        if (args != null && args.latitude != null) {
            this.latitude = args.latitude;
        }
        if (args != null && args.longitude != null) {
            this.longitude = args.longitude;
        }
        if (args != null && args.tipoEndereco != null) {
            if (typeof args.tipoEndereco === "number") {
                this.tipoEndereco = new Int64(args.tipoEndereco);
            }
            else {
                this.tipoEndereco = args.tipoEndereco;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CadastroDomiciliarThrift");
        if (this.animaisNoDomicilio != null) {
            output.writeFieldBegin("animaisNoDomicilio", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.animaisNoDomicilio.length);
            this.animaisNoDomicilio.forEach((value_1: AnimalNoDomicilioThrift.AnimalNoDomicilioThrift): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.condicaoMoradia != null) {
            output.writeFieldBegin("condicaoMoradia", thrift.Thrift.Type.STRUCT, 2);
            this.condicaoMoradia.write(output);
            output.writeFieldEnd();
        }
        if (this.enderecoLocalPermanencia != null) {
            output.writeFieldBegin("enderecoLocalPermanencia", thrift.Thrift.Type.STRUCT, 3);
            this.enderecoLocalPermanencia.write(output);
            output.writeFieldEnd();
        }
        if (this.familias != null) {
            output.writeFieldBegin("familias", thrift.Thrift.Type.LIST, 4);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.familias.length);
            this.familias.forEach((value_2: FamiliaRowThrift.FamiliaRowThrift): void => {
                value_2.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.fichaAtualizada != null) {
            output.writeFieldBegin("fichaAtualizada", thrift.Thrift.Type.BOOL, 5);
            output.writeBool(this.fichaAtualizada);
            output.writeFieldEnd();
        }
        if (this.quantosAnimaisNoDomicilio != null) {
            output.writeFieldBegin("quantosAnimaisNoDomicilio", thrift.Thrift.Type.I32, 6);
            output.writeI32(this.quantosAnimaisNoDomicilio);
            output.writeFieldEnd();
        }
        if (this.stAnimaisNoDomicilio != null) {
            output.writeFieldBegin("stAnimaisNoDomicilio", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.stAnimaisNoDomicilio);
            output.writeFieldEnd();
        }
        if (this.statusTermoRecusa != null) {
            output.writeFieldBegin("statusTermoRecusa", thrift.Thrift.Type.BOOL, 8);
            output.writeBool(this.statusTermoRecusa);
            output.writeFieldEnd();
        }
        if (this.tpCdsOrigem != null) {
            output.writeFieldBegin("tpCdsOrigem", thrift.Thrift.Type.I32, 9);
            output.writeI32(this.tpCdsOrigem);
            output.writeFieldEnd();
        }
        if (this.uuid != null) {
            output.writeFieldBegin("uuid", thrift.Thrift.Type.STRING, 10);
            output.writeString(this.uuid);
            output.writeFieldEnd();
        }
        if (this.uuidFichaOriginadora != null) {
            output.writeFieldBegin("uuidFichaOriginadora", thrift.Thrift.Type.STRING, 11);
            output.writeString(this.uuidFichaOriginadora);
            output.writeFieldEnd();
        }
        if (this.tipoDeImovel != null) {
            output.writeFieldBegin("tipoDeImovel", thrift.Thrift.Type.I64, 12);
            output.writeI64(this.tipoDeImovel);
            output.writeFieldEnd();
        }
        if (this.instituicaoPermanencia != null) {
            output.writeFieldBegin("instituicaoPermanencia", thrift.Thrift.Type.STRUCT, 13);
            this.instituicaoPermanencia.write(output);
            output.writeFieldEnd();
        }
        if (this.headerTransport != null) {
            output.writeFieldBegin("headerTransport", thrift.Thrift.Type.STRUCT, 14);
            this.headerTransport.write(output);
            output.writeFieldEnd();
        }
        if (this.latitude != null) {
            output.writeFieldBegin("latitude", thrift.Thrift.Type.DOUBLE, 15);
            output.writeDouble(this.latitude);
            output.writeFieldEnd();
        }
        if (this.longitude != null) {
            output.writeFieldBegin("longitude", thrift.Thrift.Type.DOUBLE, 16);
            output.writeDouble(this.longitude);
            output.writeFieldEnd();
        }
        if (this.tipoEndereco != null) {
            output.writeFieldBegin("tipoEndereco", thrift.Thrift.Type.I64, 17);
            output.writeI64(this.tipoEndereco);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CadastroDomiciliarThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_3: Array<AnimalNoDomicilioThrift.AnimalNoDomicilioThrift> = new Array<AnimalNoDomicilioThrift.AnimalNoDomicilioThrift>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: AnimalNoDomicilioThrift.AnimalNoDomicilioThrift = AnimalNoDomicilioThrift.AnimalNoDomicilioThrift.read(input);
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.animaisNoDomicilio = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_5: CondicaoMoradiaThrift.CondicaoMoradiaThrift = CondicaoMoradiaThrift.CondicaoMoradiaThrift.read(input);
                        _args.condicaoMoradia = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_6: EnderecoLocalPermanenciaThrift.EnderecoLocalPermanenciaThrift = EnderecoLocalPermanenciaThrift.EnderecoLocalPermanenciaThrift.read(input);
                        _args.enderecoLocalPermanencia = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_7: Array<FamiliaRowThrift.FamiliaRowThrift> = new Array<FamiliaRowThrift.FamiliaRowThrift>();
                        const metadata_2: thrift.TList = input.readListBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const value_8: FamiliaRowThrift.FamiliaRowThrift = FamiliaRowThrift.FamiliaRowThrift.read(input);
                            value_7.push(value_8);
                        }
                        input.readListEnd();
                        _args.familias = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_9: boolean = input.readBool();
                        _args.fichaAtualizada = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_10: number = input.readI32();
                        _args.quantosAnimaisNoDomicilio = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_11: boolean = input.readBool();
                        _args.stAnimaisNoDomicilio = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_12: boolean = input.readBool();
                        _args.statusTermoRecusa = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_13: number = input.readI32();
                        _args.tpCdsOrigem = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_14: string = input.readString();
                        _args.uuid = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_15: string = input.readString();
                        _args.uuidFichaOriginadora = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_16: Int64 = input.readI64();
                        _args.tipoDeImovel = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_17: InstituicaoPermanenciaThrift.InstituicaoPermanenciaThrift = InstituicaoPermanenciaThrift.InstituicaoPermanenciaThrift.read(input);
                        _args.instituicaoPermanencia = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_18: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift = VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift.read(input);
                        _args.headerTransport = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_19: number = input.readDouble();
                        _args.latitude = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_20: number = input.readDouble();
                        _args.longitude = value_20;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_21: Int64 = input.readI64();
                        _args.tipoEndereco = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.uuid !== undefined) {
            return new CadastroDomiciliarThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read CadastroDomiciliarThrift from input");
        }
    }
}
