/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as CondicoesDeSaudeThrift from "./CondicoesDeSaudeThrift";
import * as EmSituacaoDeRuaThrift from "./EmSituacaoDeRuaThrift";
import * as IdentificacaoUsuarioCidadaoThrift from "./IdentificacaoUsuarioCidadaoThrift";
import * as InformacoesSocioDemograficasThrift from "./InformacoesSocioDemograficasThrift";
import * as SaidaCidadaoCadastroThrift from "./SaidaCidadaoCadastroThrift";
import * as VariasLotacoesHeaderThrift from "./VariasLotacoesHeaderThrift";
export interface ICadastroIndividualThriftArgs {
    condicoesDeSaude?: CondicoesDeSaudeThrift.CondicoesDeSaudeThrift;
    emSituacaoDeRua?: EmSituacaoDeRuaThrift.EmSituacaoDeRuaThrift;
    fichaAtualizada?: boolean;
    identificacaoUsuarioCidadao?: IdentificacaoUsuarioCidadaoThrift.IdentificacaoUsuarioCidadaoThrift;
    informacoesSocioDemograficas?: InformacoesSocioDemograficasThrift.InformacoesSocioDemograficasThrift;
    statusTermoRecusaCadastroIndividualAtencaoBasica?: boolean;
    tpCdsOrigem?: number;
    uuid: string;
    uuidFichaOriginadora?: string;
    saidaCidadaoCadastro?: SaidaCidadaoCadastroThrift.SaidaCidadaoCadastroThrift;
    headerTransport?: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
}
export class CadastroIndividualThrift {
    public condicoesDeSaude?: CondicoesDeSaudeThrift.CondicoesDeSaudeThrift;
    public emSituacaoDeRua?: EmSituacaoDeRuaThrift.EmSituacaoDeRuaThrift;
    public fichaAtualizada?: boolean;
    public identificacaoUsuarioCidadao?: IdentificacaoUsuarioCidadaoThrift.IdentificacaoUsuarioCidadaoThrift;
    public informacoesSocioDemograficas?: InformacoesSocioDemograficasThrift.InformacoesSocioDemograficasThrift;
    public statusTermoRecusaCadastroIndividualAtencaoBasica?: boolean;
    public tpCdsOrigem?: number;
    public uuid: string;
    public uuidFichaOriginadora?: string;
    public saidaCidadaoCadastro?: SaidaCidadaoCadastroThrift.SaidaCidadaoCadastroThrift;
    public headerTransport?: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    constructor(args: ICadastroIndividualThriftArgs) {
        if (args != null && args.condicoesDeSaude != null) {
            this.condicoesDeSaude = args.condicoesDeSaude;
        }
        if (args != null && args.emSituacaoDeRua != null) {
            this.emSituacaoDeRua = args.emSituacaoDeRua;
        }
        if (args != null && args.fichaAtualizada != null) {
            this.fichaAtualizada = args.fichaAtualizada;
        }
        if (args != null && args.identificacaoUsuarioCidadao != null) {
            this.identificacaoUsuarioCidadao = args.identificacaoUsuarioCidadao;
        }
        if (args != null && args.informacoesSocioDemograficas != null) {
            this.informacoesSocioDemograficas = args.informacoesSocioDemograficas;
        }
        if (args != null && args.statusTermoRecusaCadastroIndividualAtencaoBasica != null) {
            this.statusTermoRecusaCadastroIndividualAtencaoBasica = args.statusTermoRecusaCadastroIndividualAtencaoBasica;
        }
        if (args != null && args.tpCdsOrigem != null) {
            this.tpCdsOrigem = args.tpCdsOrigem;
        }
        if (args != null && args.uuid != null) {
            this.uuid = args.uuid;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[uuid] is unset!");
        }
        if (args != null && args.uuidFichaOriginadora != null) {
            this.uuidFichaOriginadora = args.uuidFichaOriginadora;
        }
        if (args != null && args.saidaCidadaoCadastro != null) {
            this.saidaCidadaoCadastro = args.saidaCidadaoCadastro;
        }
        if (args != null && args.headerTransport != null) {
            this.headerTransport = args.headerTransport;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CadastroIndividualThrift");
        if (this.condicoesDeSaude != null) {
            output.writeFieldBegin("condicoesDeSaude", thrift.Thrift.Type.STRUCT, 1);
            this.condicoesDeSaude.write(output);
            output.writeFieldEnd();
        }
        if (this.emSituacaoDeRua != null) {
            output.writeFieldBegin("emSituacaoDeRua", thrift.Thrift.Type.STRUCT, 2);
            this.emSituacaoDeRua.write(output);
            output.writeFieldEnd();
        }
        if (this.fichaAtualizada != null) {
            output.writeFieldBegin("fichaAtualizada", thrift.Thrift.Type.BOOL, 3);
            output.writeBool(this.fichaAtualizada);
            output.writeFieldEnd();
        }
        if (this.identificacaoUsuarioCidadao != null) {
            output.writeFieldBegin("identificacaoUsuarioCidadao", thrift.Thrift.Type.STRUCT, 4);
            this.identificacaoUsuarioCidadao.write(output);
            output.writeFieldEnd();
        }
        if (this.informacoesSocioDemograficas != null) {
            output.writeFieldBegin("informacoesSocioDemograficas", thrift.Thrift.Type.STRUCT, 5);
            this.informacoesSocioDemograficas.write(output);
            output.writeFieldEnd();
        }
        if (this.statusTermoRecusaCadastroIndividualAtencaoBasica != null) {
            output.writeFieldBegin("statusTermoRecusaCadastroIndividualAtencaoBasica", thrift.Thrift.Type.BOOL, 6);
            output.writeBool(this.statusTermoRecusaCadastroIndividualAtencaoBasica);
            output.writeFieldEnd();
        }
        if (this.tpCdsOrigem != null) {
            output.writeFieldBegin("tpCdsOrigem", thrift.Thrift.Type.I32, 7);
            output.writeI32(this.tpCdsOrigem);
            output.writeFieldEnd();
        }
        if (this.uuid != null) {
            output.writeFieldBegin("uuid", thrift.Thrift.Type.STRING, 8);
            output.writeString(this.uuid);
            output.writeFieldEnd();
        }
        if (this.uuidFichaOriginadora != null) {
            output.writeFieldBegin("uuidFichaOriginadora", thrift.Thrift.Type.STRING, 9);
            output.writeString(this.uuidFichaOriginadora);
            output.writeFieldEnd();
        }
        if (this.saidaCidadaoCadastro != null) {
            output.writeFieldBegin("saidaCidadaoCadastro", thrift.Thrift.Type.STRUCT, 10);
            this.saidaCidadaoCadastro.write(output);
            output.writeFieldEnd();
        }
        if (this.headerTransport != null) {
            output.writeFieldBegin("headerTransport", thrift.Thrift.Type.STRUCT, 11);
            this.headerTransport.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CadastroIndividualThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: CondicoesDeSaudeThrift.CondicoesDeSaudeThrift = CondicoesDeSaudeThrift.CondicoesDeSaudeThrift.read(input);
                        _args.condicoesDeSaude = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_2: EmSituacaoDeRuaThrift.EmSituacaoDeRuaThrift = EmSituacaoDeRuaThrift.EmSituacaoDeRuaThrift.read(input);
                        _args.emSituacaoDeRua = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_3: boolean = input.readBool();
                        _args.fichaAtualizada = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: IdentificacaoUsuarioCidadaoThrift.IdentificacaoUsuarioCidadaoThrift = IdentificacaoUsuarioCidadaoThrift.IdentificacaoUsuarioCidadaoThrift.read(input);
                        _args.identificacaoUsuarioCidadao = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_5: InformacoesSocioDemograficasThrift.InformacoesSocioDemograficasThrift = InformacoesSocioDemograficasThrift.InformacoesSocioDemograficasThrift.read(input);
                        _args.informacoesSocioDemograficas = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_6: boolean = input.readBool();
                        _args.statusTermoRecusaCadastroIndividualAtencaoBasica = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_7: number = input.readI32();
                        _args.tpCdsOrigem = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_8: string = input.readString();
                        _args.uuid = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_9: string = input.readString();
                        _args.uuidFichaOriginadora = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_10: SaidaCidadaoCadastroThrift.SaidaCidadaoCadastroThrift = SaidaCidadaoCadastroThrift.SaidaCidadaoCadastroThrift.read(input);
                        _args.saidaCidadaoCadastro = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_11: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift = VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift.read(input);
                        _args.headerTransport = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.uuid !== undefined) {
            return new CadastroIndividualThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read CadastroIndividualThrift from input");
        }
    }
}
