/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ICondicaoMoradiaThriftArgs {
    abastecimentoAgua?: number | Int64;
    areaProducaoRural?: number | Int64;
    destinoLixo?: number | Int64;
    formaEscoamentoBanheiro?: number | Int64;
    localizacao?: number | Int64;
    materialPredominanteParedesExtDomicilio?: number | Int64;
    nuComodos?: number;
    nuMoradores?: number;
    situacaoMoradiaPosseTerra?: number | Int64;
    stDisponibilidadeEnergiaEletrica?: boolean;
    tipoAcessoDomicilio?: number | Int64;
    tipoDomicilio?: number | Int64;
    aguaConsumoDomicilio?: number | Int64;
    tipoOrigemEnergiaEletrica?: number | Int64;
}
export class CondicaoMoradiaThrift {
    public abastecimentoAgua?: Int64;
    public areaProducaoRural?: Int64;
    public destinoLixo?: Int64;
    public formaEscoamentoBanheiro?: Int64;
    public localizacao?: Int64;
    public materialPredominanteParedesExtDomicilio?: Int64;
    public nuComodos?: number;
    public nuMoradores?: number;
    public situacaoMoradiaPosseTerra?: Int64;
    public stDisponibilidadeEnergiaEletrica?: boolean;
    public tipoAcessoDomicilio?: Int64;
    public tipoDomicilio?: Int64;
    public aguaConsumoDomicilio?: Int64;
    public tipoOrigemEnergiaEletrica?: Int64;
    constructor(args?: ICondicaoMoradiaThriftArgs) {
        if (args != null && args.abastecimentoAgua != null) {
            if (typeof args.abastecimentoAgua === "number") {
                this.abastecimentoAgua = new Int64(args.abastecimentoAgua);
            }
            else {
                this.abastecimentoAgua = args.abastecimentoAgua;
            }
        }
        if (args != null && args.areaProducaoRural != null) {
            if (typeof args.areaProducaoRural === "number") {
                this.areaProducaoRural = new Int64(args.areaProducaoRural);
            }
            else {
                this.areaProducaoRural = args.areaProducaoRural;
            }
        }
        if (args != null && args.destinoLixo != null) {
            if (typeof args.destinoLixo === "number") {
                this.destinoLixo = new Int64(args.destinoLixo);
            }
            else {
                this.destinoLixo = args.destinoLixo;
            }
        }
        if (args != null && args.formaEscoamentoBanheiro != null) {
            if (typeof args.formaEscoamentoBanheiro === "number") {
                this.formaEscoamentoBanheiro = new Int64(args.formaEscoamentoBanheiro);
            }
            else {
                this.formaEscoamentoBanheiro = args.formaEscoamentoBanheiro;
            }
        }
        if (args != null && args.localizacao != null) {
            if (typeof args.localizacao === "number") {
                this.localizacao = new Int64(args.localizacao);
            }
            else {
                this.localizacao = args.localizacao;
            }
        }
        if (args != null && args.materialPredominanteParedesExtDomicilio != null) {
            if (typeof args.materialPredominanteParedesExtDomicilio === "number") {
                this.materialPredominanteParedesExtDomicilio = new Int64(args.materialPredominanteParedesExtDomicilio);
            }
            else {
                this.materialPredominanteParedesExtDomicilio = args.materialPredominanteParedesExtDomicilio;
            }
        }
        if (args != null && args.nuComodos != null) {
            this.nuComodos = args.nuComodos;
        }
        if (args != null && args.nuMoradores != null) {
            this.nuMoradores = args.nuMoradores;
        }
        if (args != null && args.situacaoMoradiaPosseTerra != null) {
            if (typeof args.situacaoMoradiaPosseTerra === "number") {
                this.situacaoMoradiaPosseTerra = new Int64(args.situacaoMoradiaPosseTerra);
            }
            else {
                this.situacaoMoradiaPosseTerra = args.situacaoMoradiaPosseTerra;
            }
        }
        if (args != null && args.stDisponibilidadeEnergiaEletrica != null) {
            this.stDisponibilidadeEnergiaEletrica = args.stDisponibilidadeEnergiaEletrica;
        }
        if (args != null && args.tipoAcessoDomicilio != null) {
            if (typeof args.tipoAcessoDomicilio === "number") {
                this.tipoAcessoDomicilio = new Int64(args.tipoAcessoDomicilio);
            }
            else {
                this.tipoAcessoDomicilio = args.tipoAcessoDomicilio;
            }
        }
        if (args != null && args.tipoDomicilio != null) {
            if (typeof args.tipoDomicilio === "number") {
                this.tipoDomicilio = new Int64(args.tipoDomicilio);
            }
            else {
                this.tipoDomicilio = args.tipoDomicilio;
            }
        }
        if (args != null && args.aguaConsumoDomicilio != null) {
            if (typeof args.aguaConsumoDomicilio === "number") {
                this.aguaConsumoDomicilio = new Int64(args.aguaConsumoDomicilio);
            }
            else {
                this.aguaConsumoDomicilio = args.aguaConsumoDomicilio;
            }
        }
        if (args != null && args.tipoOrigemEnergiaEletrica != null) {
            if (typeof args.tipoOrigemEnergiaEletrica === "number") {
                this.tipoOrigemEnergiaEletrica = new Int64(args.tipoOrigemEnergiaEletrica);
            }
            else {
                this.tipoOrigemEnergiaEletrica = args.tipoOrigemEnergiaEletrica;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CondicaoMoradiaThrift");
        if (this.abastecimentoAgua != null) {
            output.writeFieldBegin("abastecimentoAgua", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.abastecimentoAgua);
            output.writeFieldEnd();
        }
        if (this.areaProducaoRural != null) {
            output.writeFieldBegin("areaProducaoRural", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.areaProducaoRural);
            output.writeFieldEnd();
        }
        if (this.destinoLixo != null) {
            output.writeFieldBegin("destinoLixo", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.destinoLixo);
            output.writeFieldEnd();
        }
        if (this.formaEscoamentoBanheiro != null) {
            output.writeFieldBegin("formaEscoamentoBanheiro", thrift.Thrift.Type.I64, 4);
            output.writeI64(this.formaEscoamentoBanheiro);
            output.writeFieldEnd();
        }
        if (this.localizacao != null) {
            output.writeFieldBegin("localizacao", thrift.Thrift.Type.I64, 5);
            output.writeI64(this.localizacao);
            output.writeFieldEnd();
        }
        if (this.materialPredominanteParedesExtDomicilio != null) {
            output.writeFieldBegin("materialPredominanteParedesExtDomicilio", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.materialPredominanteParedesExtDomicilio);
            output.writeFieldEnd();
        }
        if (this.nuComodos != null) {
            output.writeFieldBegin("nuComodos", thrift.Thrift.Type.I32, 7);
            output.writeI32(this.nuComodos);
            output.writeFieldEnd();
        }
        if (this.nuMoradores != null) {
            output.writeFieldBegin("nuMoradores", thrift.Thrift.Type.I32, 8);
            output.writeI32(this.nuMoradores);
            output.writeFieldEnd();
        }
        if (this.situacaoMoradiaPosseTerra != null) {
            output.writeFieldBegin("situacaoMoradiaPosseTerra", thrift.Thrift.Type.I64, 9);
            output.writeI64(this.situacaoMoradiaPosseTerra);
            output.writeFieldEnd();
        }
        if (this.stDisponibilidadeEnergiaEletrica != null) {
            output.writeFieldBegin("stDisponibilidadeEnergiaEletrica", thrift.Thrift.Type.BOOL, 10);
            output.writeBool(this.stDisponibilidadeEnergiaEletrica);
            output.writeFieldEnd();
        }
        if (this.tipoAcessoDomicilio != null) {
            output.writeFieldBegin("tipoAcessoDomicilio", thrift.Thrift.Type.I64, 11);
            output.writeI64(this.tipoAcessoDomicilio);
            output.writeFieldEnd();
        }
        if (this.tipoDomicilio != null) {
            output.writeFieldBegin("tipoDomicilio", thrift.Thrift.Type.I64, 12);
            output.writeI64(this.tipoDomicilio);
            output.writeFieldEnd();
        }
        if (this.aguaConsumoDomicilio != null) {
            output.writeFieldBegin("aguaConsumoDomicilio", thrift.Thrift.Type.I64, 13);
            output.writeI64(this.aguaConsumoDomicilio);
            output.writeFieldEnd();
        }
        if (this.tipoOrigemEnergiaEletrica != null) {
            output.writeFieldBegin("tipoOrigemEnergiaEletrica", thrift.Thrift.Type.I64, 14);
            output.writeI64(this.tipoOrigemEnergiaEletrica);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CondicaoMoradiaThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.abastecimentoAgua = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.areaProducaoRural = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.destinoLixo = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_4: Int64 = input.readI64();
                        _args.formaEscoamentoBanheiro = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_5: Int64 = input.readI64();
                        _args.localizacao = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.materialPredominanteParedesExtDomicilio = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_7: number = input.readI32();
                        _args.nuComodos = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_8: number = input.readI32();
                        _args.nuMoradores = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_9: Int64 = input.readI64();
                        _args.situacaoMoradiaPosseTerra = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_10: boolean = input.readBool();
                        _args.stDisponibilidadeEnergiaEletrica = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_11: Int64 = input.readI64();
                        _args.tipoAcessoDomicilio = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_12: Int64 = input.readI64();
                        _args.tipoDomicilio = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_13: Int64 = input.readI64();
                        _args.aguaConsumoDomicilio = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_14: Int64 = input.readI64();
                        _args.tipoOrigemEnergiaEletrica = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new CondicaoMoradiaThrift(_args);
    }
}
