/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ICondicoesDeSaudeThriftArgs {
    descricaoCausaInternacaoEm12Meses?: string;
    descricaoOutraCondicao1?: string;
    descricaoOutraCondicao2?: string;
    descricaoOutraCondicao3?: string;
    descricaoPlantasMedicinaisUsadas?: string;
    doencaCardiaca?: string;
    doencaRespiratoria?: string;
    doencaRins?: string;
    maternidadeDeReferencia?: string;
    situacaoPeso?: number | Int64;
    statusEhDependenteAlcool?: boolean;
    statusEhDependenteOutrasDrogas?: boolean;
    statusEhFumante?: boolean;
    statusEhGestante?: boolean;
    statusEstaAcamado?: boolean;
    statusEstaDomiciliado?: boolean;
    statusTemDiabetes?: boolean;
    statusTemDoencaRespiratoria?: boolean;
    statusTemHanseniase?: boolean;
    statusTemHipertensaoArterial?: boolean;
    statusTemTeveCancer?: boolean;
    statusTemTeveDoencasRins?: boolean;
    statusTemTuberculose?: boolean;
    statusTeveAvcDerrame?: boolean;
    statusTeveDoencaCardiaca?: boolean;
    statusTeveInfarto?: boolean;
    statusTeveInternadoem12Meses?: boolean;
    statusUsaOutrasPraticasIntegrativasOuComplementares?: boolean;
    statusUsaPlantasMedicinais?: boolean;
    statusDiagnosticoMental?: boolean;
}
export class CondicoesDeSaudeThrift {
    public descricaoCausaInternacaoEm12Meses?: string;
    public descricaoOutraCondicao1?: string;
    public descricaoOutraCondicao2?: string;
    public descricaoOutraCondicao3?: string;
    public descricaoPlantasMedicinaisUsadas?: string;
    public doencaCardiaca?: string;
    public doencaRespiratoria?: string;
    public doencaRins?: string;
    public maternidadeDeReferencia?: string;
    public situacaoPeso?: Int64;
    public statusEhDependenteAlcool?: boolean;
    public statusEhDependenteOutrasDrogas?: boolean;
    public statusEhFumante?: boolean;
    public statusEhGestante?: boolean;
    public statusEstaAcamado?: boolean;
    public statusEstaDomiciliado?: boolean;
    public statusTemDiabetes?: boolean;
    public statusTemDoencaRespiratoria?: boolean;
    public statusTemHanseniase?: boolean;
    public statusTemHipertensaoArterial?: boolean;
    public statusTemTeveCancer?: boolean;
    public statusTemTeveDoencasRins?: boolean;
    public statusTemTuberculose?: boolean;
    public statusTeveAvcDerrame?: boolean;
    public statusTeveDoencaCardiaca?: boolean;
    public statusTeveInfarto?: boolean;
    public statusTeveInternadoem12Meses?: boolean;
    public statusUsaOutrasPraticasIntegrativasOuComplementares?: boolean;
    public statusUsaPlantasMedicinais?: boolean;
    public statusDiagnosticoMental?: boolean;
    constructor(args?: ICondicoesDeSaudeThriftArgs) {
        if (args != null && args.descricaoCausaInternacaoEm12Meses != null) {
            this.descricaoCausaInternacaoEm12Meses = args.descricaoCausaInternacaoEm12Meses;
        }
        if (args != null && args.descricaoOutraCondicao1 != null) {
            this.descricaoOutraCondicao1 = args.descricaoOutraCondicao1;
        }
        if (args != null && args.descricaoOutraCondicao2 != null) {
            this.descricaoOutraCondicao2 = args.descricaoOutraCondicao2;
        }
        if (args != null && args.descricaoOutraCondicao3 != null) {
            this.descricaoOutraCondicao3 = args.descricaoOutraCondicao3;
        }
        if (args != null && args.descricaoPlantasMedicinaisUsadas != null) {
            this.descricaoPlantasMedicinaisUsadas = args.descricaoPlantasMedicinaisUsadas;
        }
        if (args != null && args.doencaCardiaca != null) {
            this.doencaCardiaca = args.doencaCardiaca;
        }
        if (args != null && args.doencaRespiratoria != null) {
            this.doencaRespiratoria = args.doencaRespiratoria;
        }
        if (args != null && args.doencaRins != null) {
            this.doencaRins = args.doencaRins;
        }
        if (args != null && args.maternidadeDeReferencia != null) {
            this.maternidadeDeReferencia = args.maternidadeDeReferencia;
        }
        if (args != null && args.situacaoPeso != null) {
            if (typeof args.situacaoPeso === "number") {
                this.situacaoPeso = new Int64(args.situacaoPeso);
            }
            else {
                this.situacaoPeso = args.situacaoPeso;
            }
        }
        if (args != null && args.statusEhDependenteAlcool != null) {
            this.statusEhDependenteAlcool = args.statusEhDependenteAlcool;
        }
        if (args != null && args.statusEhDependenteOutrasDrogas != null) {
            this.statusEhDependenteOutrasDrogas = args.statusEhDependenteOutrasDrogas;
        }
        if (args != null && args.statusEhFumante != null) {
            this.statusEhFumante = args.statusEhFumante;
        }
        if (args != null && args.statusEhGestante != null) {
            this.statusEhGestante = args.statusEhGestante;
        }
        if (args != null && args.statusEstaAcamado != null) {
            this.statusEstaAcamado = args.statusEstaAcamado;
        }
        if (args != null && args.statusEstaDomiciliado != null) {
            this.statusEstaDomiciliado = args.statusEstaDomiciliado;
        }
        if (args != null && args.statusTemDiabetes != null) {
            this.statusTemDiabetes = args.statusTemDiabetes;
        }
        if (args != null && args.statusTemDoencaRespiratoria != null) {
            this.statusTemDoencaRespiratoria = args.statusTemDoencaRespiratoria;
        }
        if (args != null && args.statusTemHanseniase != null) {
            this.statusTemHanseniase = args.statusTemHanseniase;
        }
        if (args != null && args.statusTemHipertensaoArterial != null) {
            this.statusTemHipertensaoArterial = args.statusTemHipertensaoArterial;
        }
        if (args != null && args.statusTemTeveCancer != null) {
            this.statusTemTeveCancer = args.statusTemTeveCancer;
        }
        if (args != null && args.statusTemTeveDoencasRins != null) {
            this.statusTemTeveDoencasRins = args.statusTemTeveDoencasRins;
        }
        if (args != null && args.statusTemTuberculose != null) {
            this.statusTemTuberculose = args.statusTemTuberculose;
        }
        if (args != null && args.statusTeveAvcDerrame != null) {
            this.statusTeveAvcDerrame = args.statusTeveAvcDerrame;
        }
        if (args != null && args.statusTeveDoencaCardiaca != null) {
            this.statusTeveDoencaCardiaca = args.statusTeveDoencaCardiaca;
        }
        if (args != null && args.statusTeveInfarto != null) {
            this.statusTeveInfarto = args.statusTeveInfarto;
        }
        if (args != null && args.statusTeveInternadoem12Meses != null) {
            this.statusTeveInternadoem12Meses = args.statusTeveInternadoem12Meses;
        }
        if (args != null && args.statusUsaOutrasPraticasIntegrativasOuComplementares != null) {
            this.statusUsaOutrasPraticasIntegrativasOuComplementares = args.statusUsaOutrasPraticasIntegrativasOuComplementares;
        }
        if (args != null && args.statusUsaPlantasMedicinais != null) {
            this.statusUsaPlantasMedicinais = args.statusUsaPlantasMedicinais;
        }
        if (args != null && args.statusDiagnosticoMental != null) {
            this.statusDiagnosticoMental = args.statusDiagnosticoMental;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("CondicoesDeSaudeThrift");
        if (this.descricaoCausaInternacaoEm12Meses != null) {
            output.writeFieldBegin("descricaoCausaInternacaoEm12Meses", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.descricaoCausaInternacaoEm12Meses);
            output.writeFieldEnd();
        }
        if (this.descricaoOutraCondicao1 != null) {
            output.writeFieldBegin("descricaoOutraCondicao1", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.descricaoOutraCondicao1);
            output.writeFieldEnd();
        }
        if (this.descricaoOutraCondicao2 != null) {
            output.writeFieldBegin("descricaoOutraCondicao2", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.descricaoOutraCondicao2);
            output.writeFieldEnd();
        }
        if (this.descricaoOutraCondicao3 != null) {
            output.writeFieldBegin("descricaoOutraCondicao3", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.descricaoOutraCondicao3);
            output.writeFieldEnd();
        }
        if (this.descricaoPlantasMedicinaisUsadas != null) {
            output.writeFieldBegin("descricaoPlantasMedicinaisUsadas", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.descricaoPlantasMedicinaisUsadas);
            output.writeFieldEnd();
        }
        if (this.doencaCardiaca != null) {
            output.writeFieldBegin("doencaCardiaca", thrift.Thrift.Type.STRING, 6);
            output.writeString(this.doencaCardiaca);
            output.writeFieldEnd();
        }
        if (this.doencaRespiratoria != null) {
            output.writeFieldBegin("doencaRespiratoria", thrift.Thrift.Type.STRING, 7);
            output.writeString(this.doencaRespiratoria);
            output.writeFieldEnd();
        }
        if (this.doencaRins != null) {
            output.writeFieldBegin("doencaRins", thrift.Thrift.Type.STRING, 8);
            output.writeString(this.doencaRins);
            output.writeFieldEnd();
        }
        if (this.maternidadeDeReferencia != null) {
            output.writeFieldBegin("maternidadeDeReferencia", thrift.Thrift.Type.STRING, 9);
            output.writeString(this.maternidadeDeReferencia);
            output.writeFieldEnd();
        }
        if (this.situacaoPeso != null) {
            output.writeFieldBegin("situacaoPeso", thrift.Thrift.Type.I64, 10);
            output.writeI64(this.situacaoPeso);
            output.writeFieldEnd();
        }
        if (this.statusEhDependenteAlcool != null) {
            output.writeFieldBegin("statusEhDependenteAlcool", thrift.Thrift.Type.BOOL, 11);
            output.writeBool(this.statusEhDependenteAlcool);
            output.writeFieldEnd();
        }
        if (this.statusEhDependenteOutrasDrogas != null) {
            output.writeFieldBegin("statusEhDependenteOutrasDrogas", thrift.Thrift.Type.BOOL, 12);
            output.writeBool(this.statusEhDependenteOutrasDrogas);
            output.writeFieldEnd();
        }
        if (this.statusEhFumante != null) {
            output.writeFieldBegin("statusEhFumante", thrift.Thrift.Type.BOOL, 13);
            output.writeBool(this.statusEhFumante);
            output.writeFieldEnd();
        }
        if (this.statusEhGestante != null) {
            output.writeFieldBegin("statusEhGestante", thrift.Thrift.Type.BOOL, 14);
            output.writeBool(this.statusEhGestante);
            output.writeFieldEnd();
        }
        if (this.statusEstaAcamado != null) {
            output.writeFieldBegin("statusEstaAcamado", thrift.Thrift.Type.BOOL, 15);
            output.writeBool(this.statusEstaAcamado);
            output.writeFieldEnd();
        }
        if (this.statusEstaDomiciliado != null) {
            output.writeFieldBegin("statusEstaDomiciliado", thrift.Thrift.Type.BOOL, 16);
            output.writeBool(this.statusEstaDomiciliado);
            output.writeFieldEnd();
        }
        if (this.statusTemDiabetes != null) {
            output.writeFieldBegin("statusTemDiabetes", thrift.Thrift.Type.BOOL, 17);
            output.writeBool(this.statusTemDiabetes);
            output.writeFieldEnd();
        }
        if (this.statusTemDoencaRespiratoria != null) {
            output.writeFieldBegin("statusTemDoencaRespiratoria", thrift.Thrift.Type.BOOL, 18);
            output.writeBool(this.statusTemDoencaRespiratoria);
            output.writeFieldEnd();
        }
        if (this.statusTemHanseniase != null) {
            output.writeFieldBegin("statusTemHanseniase", thrift.Thrift.Type.BOOL, 19);
            output.writeBool(this.statusTemHanseniase);
            output.writeFieldEnd();
        }
        if (this.statusTemHipertensaoArterial != null) {
            output.writeFieldBegin("statusTemHipertensaoArterial", thrift.Thrift.Type.BOOL, 20);
            output.writeBool(this.statusTemHipertensaoArterial);
            output.writeFieldEnd();
        }
        if (this.statusTemTeveCancer != null) {
            output.writeFieldBegin("statusTemTeveCancer", thrift.Thrift.Type.BOOL, 21);
            output.writeBool(this.statusTemTeveCancer);
            output.writeFieldEnd();
        }
        if (this.statusTemTeveDoencasRins != null) {
            output.writeFieldBegin("statusTemTeveDoencasRins", thrift.Thrift.Type.BOOL, 22);
            output.writeBool(this.statusTemTeveDoencasRins);
            output.writeFieldEnd();
        }
        if (this.statusTemTuberculose != null) {
            output.writeFieldBegin("statusTemTuberculose", thrift.Thrift.Type.BOOL, 23);
            output.writeBool(this.statusTemTuberculose);
            output.writeFieldEnd();
        }
        if (this.statusTeveAvcDerrame != null) {
            output.writeFieldBegin("statusTeveAvcDerrame", thrift.Thrift.Type.BOOL, 24);
            output.writeBool(this.statusTeveAvcDerrame);
            output.writeFieldEnd();
        }
        if (this.statusTeveDoencaCardiaca != null) {
            output.writeFieldBegin("statusTeveDoencaCardiaca", thrift.Thrift.Type.BOOL, 25);
            output.writeBool(this.statusTeveDoencaCardiaca);
            output.writeFieldEnd();
        }
        if (this.statusTeveInfarto != null) {
            output.writeFieldBegin("statusTeveInfarto", thrift.Thrift.Type.BOOL, 26);
            output.writeBool(this.statusTeveInfarto);
            output.writeFieldEnd();
        }
        if (this.statusTeveInternadoem12Meses != null) {
            output.writeFieldBegin("statusTeveInternadoem12Meses", thrift.Thrift.Type.BOOL, 27);
            output.writeBool(this.statusTeveInternadoem12Meses);
            output.writeFieldEnd();
        }
        if (this.statusUsaOutrasPraticasIntegrativasOuComplementares != null) {
            output.writeFieldBegin("statusUsaOutrasPraticasIntegrativasOuComplementares", thrift.Thrift.Type.BOOL, 28);
            output.writeBool(this.statusUsaOutrasPraticasIntegrativasOuComplementares);
            output.writeFieldEnd();
        }
        if (this.statusUsaPlantasMedicinais != null) {
            output.writeFieldBegin("statusUsaPlantasMedicinais", thrift.Thrift.Type.BOOL, 29);
            output.writeBool(this.statusUsaPlantasMedicinais);
            output.writeFieldEnd();
        }
        if (this.statusDiagnosticoMental != null) {
            output.writeFieldBegin("statusDiagnosticoMental", thrift.Thrift.Type.BOOL, 30);
            output.writeBool(this.statusDiagnosticoMental);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): CondicoesDeSaudeThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.descricaoCausaInternacaoEm12Meses = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.descricaoOutraCondicao1 = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.descricaoOutraCondicao2 = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.descricaoOutraCondicao3 = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.descricaoPlantasMedicinaisUsadas = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_6: string = input.readString();
                        _args.doencaCardiaca = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: string = input.readString();
                        _args.doencaRespiratoria = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_8: string = input.readString();
                        _args.doencaRins = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_9: string = input.readString();
                        _args.maternidadeDeReferencia = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_10: Int64 = input.readI64();
                        _args.situacaoPeso = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_11: boolean = input.readBool();
                        _args.statusEhDependenteAlcool = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_12: boolean = input.readBool();
                        _args.statusEhDependenteOutrasDrogas = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_13: boolean = input.readBool();
                        _args.statusEhFumante = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_14: boolean = input.readBool();
                        _args.statusEhGestante = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_15: boolean = input.readBool();
                        _args.statusEstaAcamado = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_16: boolean = input.readBool();
                        _args.statusEstaDomiciliado = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_17: boolean = input.readBool();
                        _args.statusTemDiabetes = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_18: boolean = input.readBool();
                        _args.statusTemDoencaRespiratoria = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 19:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_19: boolean = input.readBool();
                        _args.statusTemHanseniase = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 20:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_20: boolean = input.readBool();
                        _args.statusTemHipertensaoArterial = value_20;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 21:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_21: boolean = input.readBool();
                        _args.statusTemTeveCancer = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 22:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_22: boolean = input.readBool();
                        _args.statusTemTeveDoencasRins = value_22;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 23:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_23: boolean = input.readBool();
                        _args.statusTemTuberculose = value_23;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 24:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_24: boolean = input.readBool();
                        _args.statusTeveAvcDerrame = value_24;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 25:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_25: boolean = input.readBool();
                        _args.statusTeveDoencaCardiaca = value_25;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 26:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_26: boolean = input.readBool();
                        _args.statusTeveInfarto = value_26;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 27:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_27: boolean = input.readBool();
                        _args.statusTeveInternadoem12Meses = value_27;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 28:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_28: boolean = input.readBool();
                        _args.statusUsaOutrasPraticasIntegrativasOuComplementares = value_28;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 29:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_29: boolean = input.readBool();
                        _args.statusUsaPlantasMedicinais = value_29;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 30:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_30: boolean = input.readBool();
                        _args.statusDiagnosticoMental = value_30;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new CondicoesDeSaudeThrift(_args);
    }
}
