/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as LediRemetenteThrift from "./LediRemetenteThrift";
import * as LediOriginadoraThrift from "./LediOriginadoraThrift";
import * as VersaoThrift from "./VersaoThrift";
export interface IDadoTransporteThriftArgs {
    uuidDadoSerializado: string;
    tipoDadoSerializado: number | Int64;
    cnesDadoSerializado: string;
    codIbge: string;
    ineDadoSerializado?: string;
    numLote?: number | Int64;
    dadoSerializado: Buffer;
    remetente: LediRemetenteThrift.LediRemetenteThrift;
    originadora: LediOriginadoraThrift.LediOriginadoraThrift;
    versao?: VersaoThrift.VersaoThrift;
}
export class DadoTransporteThrift {
    public uuidDadoSerializado: string;
    public tipoDadoSerializado: Int64;
    public cnesDadoSerializado: string;
    public codIbge: string;
    public ineDadoSerializado?: string;
    public numLote?: Int64;
    public dadoSerializado: Buffer;
    public remetente: LediRemetenteThrift.LediRemetenteThrift;
    public originadora: LediOriginadoraThrift.LediOriginadoraThrift;
    public versao?: VersaoThrift.VersaoThrift;
    constructor(args: IDadoTransporteThriftArgs) {
        if (args != null && args.uuidDadoSerializado != null) {
            this.uuidDadoSerializado = args.uuidDadoSerializado;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[uuidDadoSerializado] is unset!");
        }
        if (args != null && args.tipoDadoSerializado != null) {
            if (typeof args.tipoDadoSerializado === "number") {
                this.tipoDadoSerializado = new Int64(args.tipoDadoSerializado);
            }
            else {
                this.tipoDadoSerializado = args.tipoDadoSerializado;
            }
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[tipoDadoSerializado] is unset!");
        }
        if (args != null && args.cnesDadoSerializado != null) {
            this.cnesDadoSerializado = args.cnesDadoSerializado;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cnesDadoSerializado] is unset!");
        }
        if (args != null && args.codIbge != null) {
            this.codIbge = args.codIbge;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[codIbge] is unset!");
        }
        if (args != null && args.ineDadoSerializado != null) {
            this.ineDadoSerializado = args.ineDadoSerializado;
        }
        if (args != null && args.numLote != null) {
            if (typeof args.numLote === "number") {
                this.numLote = new Int64(args.numLote);
            }
            else {
                this.numLote = args.numLote;
            }
        }
        if (args != null && args.dadoSerializado != null) {
            this.dadoSerializado = args.dadoSerializado;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[dadoSerializado] is unset!");
        }
        if (args != null && args.remetente != null) {
            this.remetente = args.remetente;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[remetente] is unset!");
        }
        if (args != null && args.originadora != null) {
            this.originadora = args.originadora;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[originadora] is unset!");
        }
        if (args != null && args.versao != null) {
            this.versao = args.versao;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("DadoTransporteThrift");
        if (this.uuidDadoSerializado != null) {
            output.writeFieldBegin("uuidDadoSerializado", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.uuidDadoSerializado);
            output.writeFieldEnd();
        }
        if (this.tipoDadoSerializado != null) {
            output.writeFieldBegin("tipoDadoSerializado", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.tipoDadoSerializado);
            output.writeFieldEnd();
        }
        if (this.cnesDadoSerializado != null) {
            output.writeFieldBegin("cnesDadoSerializado", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.cnesDadoSerializado);
            output.writeFieldEnd();
        }
        if (this.codIbge != null) {
            output.writeFieldBegin("codIbge", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.codIbge);
            output.writeFieldEnd();
        }
        if (this.ineDadoSerializado != null) {
            output.writeFieldBegin("ineDadoSerializado", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.ineDadoSerializado);
            output.writeFieldEnd();
        }
        if (this.numLote != null) {
            output.writeFieldBegin("numLote", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.numLote);
            output.writeFieldEnd();
        }
        if (this.dadoSerializado != null) {
            output.writeFieldBegin("dadoSerializado", thrift.Thrift.Type.STRING, 7);
            output.writeBinary(this.dadoSerializado);
            output.writeFieldEnd();
        }
        if (this.remetente != null) {
            output.writeFieldBegin("remetente", thrift.Thrift.Type.STRUCT, 8);
            this.remetente.write(output);
            output.writeFieldEnd();
        }
        if (this.originadora != null) {
            output.writeFieldBegin("originadora", thrift.Thrift.Type.STRUCT, 9);
            this.originadora.write(output);
            output.writeFieldEnd();
        }
        if (this.versao != null) {
            output.writeFieldBegin("versao", thrift.Thrift.Type.STRUCT, 10);
            this.versao.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): DadoTransporteThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.uuidDadoSerializado = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.tipoDadoSerializado = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.cnesDadoSerializado = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.codIbge = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.ineDadoSerializado = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.numLote = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: Buffer = input.readBinary();
                        _args.dadoSerializado = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_8: LediRemetenteThrift.LediRemetenteThrift = LediRemetenteThrift.LediRemetenteThrift.read(input);
                        _args.remetente = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_9: LediOriginadoraThrift.LediOriginadoraThrift = LediOriginadoraThrift.LediOriginadoraThrift.read(input);
                        _args.originadora = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_10: VersaoThrift.VersaoThrift = VersaoThrift.VersaoThrift.read(input);
                        _args.versao = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.uuidDadoSerializado !== undefined && _args.tipoDadoSerializado !== undefined && _args.cnesDadoSerializado !== undefined && _args.codIbge !== undefined && _args.dadoSerializado !== undefined && _args.remetente !== undefined && _args.originadora !== undefined) {
            return new DadoTransporteThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read DadoTransporteThrift from input");
        }
    }
}
