/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IEmSituacaoDeRuaThriftArgs {
    grauParentescoFamiliarFrequentado?: string;
    higienePessoalSituacaoRua?: string;
    statusTemAcessoHigienePessoalSituacaoRua?: boolean;
    origemAlimentoSituacaoRua?: string;
    outraInstituicaoQueAcompanha?: string;
    quantidadeAlimentacoesAoDiaSituacaoRua?: number | Int64;
    statusAcompanhadoPorOutraInstituicao?: boolean;
    statusPossuiReferenciaFamiliar?: boolean;
    statusRecebeBeneficio?: boolean;
    statusSituacaoRua?: boolean;
    statusVisitaFamiliarFrequentemente?: boolean;
    tempoSituacaoRua?: number | Int64;
}
export class EmSituacaoDeRuaThrift {
    public grauParentescoFamiliarFrequentado?: string;
    public higienePessoalSituacaoRua?: string;
    public statusTemAcessoHigienePessoalSituacaoRua?: boolean;
    public origemAlimentoSituacaoRua?: string;
    public outraInstituicaoQueAcompanha?: string;
    public quantidadeAlimentacoesAoDiaSituacaoRua?: Int64;
    public statusAcompanhadoPorOutraInstituicao?: boolean;
    public statusPossuiReferenciaFamiliar?: boolean;
    public statusRecebeBeneficio?: boolean;
    public statusSituacaoRua?: boolean;
    public statusVisitaFamiliarFrequentemente?: boolean;
    public tempoSituacaoRua?: Int64;
    constructor(args?: IEmSituacaoDeRuaThriftArgs) {
        if (args != null && args.grauParentescoFamiliarFrequentado != null) {
            this.grauParentescoFamiliarFrequentado = args.grauParentescoFamiliarFrequentado;
        }
        if (args != null && args.higienePessoalSituacaoRua != null) {
            this.higienePessoalSituacaoRua = args.higienePessoalSituacaoRua;
        }
        if (args != null && args.statusTemAcessoHigienePessoalSituacaoRua != null) {
            this.statusTemAcessoHigienePessoalSituacaoRua = args.statusTemAcessoHigienePessoalSituacaoRua;
        }
        if (args != null && args.origemAlimentoSituacaoRua != null) {
            this.origemAlimentoSituacaoRua = args.origemAlimentoSituacaoRua;
        }
        if (args != null && args.outraInstituicaoQueAcompanha != null) {
            this.outraInstituicaoQueAcompanha = args.outraInstituicaoQueAcompanha;
        }
        if (args != null && args.quantidadeAlimentacoesAoDiaSituacaoRua != null) {
            if (typeof args.quantidadeAlimentacoesAoDiaSituacaoRua === "number") {
                this.quantidadeAlimentacoesAoDiaSituacaoRua = new Int64(args.quantidadeAlimentacoesAoDiaSituacaoRua);
            }
            else {
                this.quantidadeAlimentacoesAoDiaSituacaoRua = args.quantidadeAlimentacoesAoDiaSituacaoRua;
            }
        }
        if (args != null && args.statusAcompanhadoPorOutraInstituicao != null) {
            this.statusAcompanhadoPorOutraInstituicao = args.statusAcompanhadoPorOutraInstituicao;
        }
        if (args != null && args.statusPossuiReferenciaFamiliar != null) {
            this.statusPossuiReferenciaFamiliar = args.statusPossuiReferenciaFamiliar;
        }
        if (args != null && args.statusRecebeBeneficio != null) {
            this.statusRecebeBeneficio = args.statusRecebeBeneficio;
        }
        if (args != null && args.statusSituacaoRua != null) {
            this.statusSituacaoRua = args.statusSituacaoRua;
        }
        if (args != null && args.statusVisitaFamiliarFrequentemente != null) {
            this.statusVisitaFamiliarFrequentemente = args.statusVisitaFamiliarFrequentemente;
        }
        if (args != null && args.tempoSituacaoRua != null) {
            if (typeof args.tempoSituacaoRua === "number") {
                this.tempoSituacaoRua = new Int64(args.tempoSituacaoRua);
            }
            else {
                this.tempoSituacaoRua = args.tempoSituacaoRua;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("EmSituacaoDeRuaThrift");
        if (this.grauParentescoFamiliarFrequentado != null) {
            output.writeFieldBegin("grauParentescoFamiliarFrequentado", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.grauParentescoFamiliarFrequentado);
            output.writeFieldEnd();
        }
        if (this.higienePessoalSituacaoRua != null) {
            output.writeFieldBegin("higienePessoalSituacaoRua", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.higienePessoalSituacaoRua);
            output.writeFieldEnd();
        }
        if (this.statusTemAcessoHigienePessoalSituacaoRua != null) {
            output.writeFieldBegin("statusTemAcessoHigienePessoalSituacaoRua", thrift.Thrift.Type.BOOL, 3);
            output.writeBool(this.statusTemAcessoHigienePessoalSituacaoRua);
            output.writeFieldEnd();
        }
        if (this.origemAlimentoSituacaoRua != null) {
            output.writeFieldBegin("origemAlimentoSituacaoRua", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.origemAlimentoSituacaoRua);
            output.writeFieldEnd();
        }
        if (this.outraInstituicaoQueAcompanha != null) {
            output.writeFieldBegin("outraInstituicaoQueAcompanha", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.outraInstituicaoQueAcompanha);
            output.writeFieldEnd();
        }
        if (this.quantidadeAlimentacoesAoDiaSituacaoRua != null) {
            output.writeFieldBegin("quantidadeAlimentacoesAoDiaSituacaoRua", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.quantidadeAlimentacoesAoDiaSituacaoRua);
            output.writeFieldEnd();
        }
        if (this.statusAcompanhadoPorOutraInstituicao != null) {
            output.writeFieldBegin("statusAcompanhadoPorOutraInstituicao", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.statusAcompanhadoPorOutraInstituicao);
            output.writeFieldEnd();
        }
        if (this.statusPossuiReferenciaFamiliar != null) {
            output.writeFieldBegin("statusPossuiReferenciaFamiliar", thrift.Thrift.Type.BOOL, 8);
            output.writeBool(this.statusPossuiReferenciaFamiliar);
            output.writeFieldEnd();
        }
        if (this.statusRecebeBeneficio != null) {
            output.writeFieldBegin("statusRecebeBeneficio", thrift.Thrift.Type.BOOL, 9);
            output.writeBool(this.statusRecebeBeneficio);
            output.writeFieldEnd();
        }
        if (this.statusSituacaoRua != null) {
            output.writeFieldBegin("statusSituacaoRua", thrift.Thrift.Type.BOOL, 10);
            output.writeBool(this.statusSituacaoRua);
            output.writeFieldEnd();
        }
        if (this.statusVisitaFamiliarFrequentemente != null) {
            output.writeFieldBegin("statusVisitaFamiliarFrequentemente", thrift.Thrift.Type.BOOL, 11);
            output.writeBool(this.statusVisitaFamiliarFrequentemente);
            output.writeFieldEnd();
        }
        if (this.tempoSituacaoRua != null) {
            output.writeFieldBegin("tempoSituacaoRua", thrift.Thrift.Type.I64, 12);
            output.writeI64(this.tempoSituacaoRua);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): EmSituacaoDeRuaThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.grauParentescoFamiliarFrequentado = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.higienePessoalSituacaoRua = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_3: boolean = input.readBool();
                        _args.statusTemAcessoHigienePessoalSituacaoRua = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.origemAlimentoSituacaoRua = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.outraInstituicaoQueAcompanha = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.quantidadeAlimentacoesAoDiaSituacaoRua = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_7: boolean = input.readBool();
                        _args.statusAcompanhadoPorOutraInstituicao = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_8: boolean = input.readBool();
                        _args.statusPossuiReferenciaFamiliar = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_9: boolean = input.readBool();
                        _args.statusRecebeBeneficio = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_10: boolean = input.readBool();
                        _args.statusSituacaoRua = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_11: boolean = input.readBool();
                        _args.statusVisitaFamiliarFrequentemente = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_12: Int64 = input.readI64();
                        _args.tempoSituacaoRua = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new EmSituacaoDeRuaThrift(_args);
    }
}
