/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IEnderecoLocalPermanenciaThriftArgs {
    bairro?: string;
    cep?: string;
    codigoIbgeMunicipio?: string;
    complemento?: string;
    nomeLogradouro?: string;
    numero?: string;
    numeroDneUf?: string;
    telefoneContato?: string;
    telefoneResidencia?: string;
    tipoLogradouroNumeroDne?: string;
    stSemNumero?: boolean;
    pontoReferencia?: string;
    microArea?: string;
    stForaArea?: boolean;
}
export class EnderecoLocalPermanenciaThrift {
    public bairro?: string;
    public cep?: string;
    public codigoIbgeMunicipio?: string;
    public complemento?: string;
    public nomeLogradouro?: string;
    public numero?: string;
    public numeroDneUf?: string;
    public telefoneContato?: string;
    public telefoneResidencia?: string;
    public tipoLogradouroNumeroDne?: string;
    public stSemNumero?: boolean;
    public pontoReferencia?: string;
    public microArea?: string;
    public stForaArea?: boolean;
    constructor(args?: IEnderecoLocalPermanenciaThriftArgs) {
        if (args != null && args.bairro != null) {
            this.bairro = args.bairro;
        }
        if (args != null && args.cep != null) {
            this.cep = args.cep;
        }
        if (args != null && args.codigoIbgeMunicipio != null) {
            this.codigoIbgeMunicipio = args.codigoIbgeMunicipio;
        }
        if (args != null && args.complemento != null) {
            this.complemento = args.complemento;
        }
        if (args != null && args.nomeLogradouro != null) {
            this.nomeLogradouro = args.nomeLogradouro;
        }
        if (args != null && args.numero != null) {
            this.numero = args.numero;
        }
        if (args != null && args.numeroDneUf != null) {
            this.numeroDneUf = args.numeroDneUf;
        }
        if (args != null && args.telefoneContato != null) {
            this.telefoneContato = args.telefoneContato;
        }
        if (args != null && args.telefoneResidencia != null) {
            this.telefoneResidencia = args.telefoneResidencia;
        }
        if (args != null && args.tipoLogradouroNumeroDne != null) {
            this.tipoLogradouroNumeroDne = args.tipoLogradouroNumeroDne;
        }
        if (args != null && args.stSemNumero != null) {
            this.stSemNumero = args.stSemNumero;
        }
        if (args != null && args.pontoReferencia != null) {
            this.pontoReferencia = args.pontoReferencia;
        }
        if (args != null && args.microArea != null) {
            this.microArea = args.microArea;
        }
        if (args != null && args.stForaArea != null) {
            this.stForaArea = args.stForaArea;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("EnderecoLocalPermanenciaThrift");
        if (this.bairro != null) {
            output.writeFieldBegin("bairro", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.bairro);
            output.writeFieldEnd();
        }
        if (this.cep != null) {
            output.writeFieldBegin("cep", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.cep);
            output.writeFieldEnd();
        }
        if (this.codigoIbgeMunicipio != null) {
            output.writeFieldBegin("codigoIbgeMunicipio", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.codigoIbgeMunicipio);
            output.writeFieldEnd();
        }
        if (this.complemento != null) {
            output.writeFieldBegin("complemento", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.complemento);
            output.writeFieldEnd();
        }
        if (this.nomeLogradouro != null) {
            output.writeFieldBegin("nomeLogradouro", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.nomeLogradouro);
            output.writeFieldEnd();
        }
        if (this.numero != null) {
            output.writeFieldBegin("numero", thrift.Thrift.Type.STRING, 6);
            output.writeString(this.numero);
            output.writeFieldEnd();
        }
        if (this.numeroDneUf != null) {
            output.writeFieldBegin("numeroDneUf", thrift.Thrift.Type.STRING, 7);
            output.writeString(this.numeroDneUf);
            output.writeFieldEnd();
        }
        if (this.telefoneContato != null) {
            output.writeFieldBegin("telefoneContato", thrift.Thrift.Type.STRING, 8);
            output.writeString(this.telefoneContato);
            output.writeFieldEnd();
        }
        if (this.telefoneResidencia != null) {
            output.writeFieldBegin("telefoneResidencia", thrift.Thrift.Type.STRING, 9);
            output.writeString(this.telefoneResidencia);
            output.writeFieldEnd();
        }
        if (this.tipoLogradouroNumeroDne != null) {
            output.writeFieldBegin("tipoLogradouroNumeroDne", thrift.Thrift.Type.STRING, 10);
            output.writeString(this.tipoLogradouroNumeroDne);
            output.writeFieldEnd();
        }
        if (this.stSemNumero != null) {
            output.writeFieldBegin("stSemNumero", thrift.Thrift.Type.BOOL, 11);
            output.writeBool(this.stSemNumero);
            output.writeFieldEnd();
        }
        if (this.pontoReferencia != null) {
            output.writeFieldBegin("pontoReferencia", thrift.Thrift.Type.STRING, 12);
            output.writeString(this.pontoReferencia);
            output.writeFieldEnd();
        }
        if (this.microArea != null) {
            output.writeFieldBegin("microArea", thrift.Thrift.Type.STRING, 13);
            output.writeString(this.microArea);
            output.writeFieldEnd();
        }
        if (this.stForaArea != null) {
            output.writeFieldBegin("stForaArea", thrift.Thrift.Type.BOOL, 14);
            output.writeBool(this.stForaArea);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): EnderecoLocalPermanenciaThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.bairro = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.cep = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.codigoIbgeMunicipio = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.complemento = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.nomeLogradouro = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_6: string = input.readString();
                        _args.numero = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: string = input.readString();
                        _args.numeroDneUf = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_8: string = input.readString();
                        _args.telefoneContato = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_9: string = input.readString();
                        _args.telefoneResidencia = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_10: string = input.readString();
                        _args.tipoLogradouroNumeroDne = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_11: boolean = input.readBool();
                        _args.stSemNumero = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_12: string = input.readString();
                        _args.pontoReferencia = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_13: string = input.readString();
                        _args.microArea = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_14: boolean = input.readBool();
                        _args.stForaArea = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new EnderecoLocalPermanenciaThrift(_args);
    }
}
