/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IExameThriftArgs {
    codigoExame?: string;
    solicitadoAvaliado?: Array<string>;
}
export class ExameThrift {
    public codigoExame?: string;
    public solicitadoAvaliado?: Array<string>;
    constructor(args?: IExameThriftArgs) {
        if (args != null && args.codigoExame != null) {
            this.codigoExame = args.codigoExame;
        }
        if (args != null && args.solicitadoAvaliado != null) {
            this.solicitadoAvaliado = args.solicitadoAvaliado;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ExameThrift");
        if (this.codigoExame != null) {
            output.writeFieldBegin("codigoExame", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.codigoExame);
            output.writeFieldEnd();
        }
        if (this.solicitadoAvaliado != null) {
            output.writeFieldBegin("solicitadoAvaliado", thrift.Thrift.Type.LIST, 2);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.solicitadoAvaliado.length);
            this.solicitadoAvaliado.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ExameThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.codigoExame = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_3: Array<string> = new Array<string>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_4: string = input.readString();
                            value_3.push(value_4);
                        }
                        input.readListEnd();
                        _args.solicitadoAvaliado = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ExameThrift(_args);
    }
}
