/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IFamiliaRowThriftArgs {
    dataNascimentoResponsavel?: number | Int64;
    numeroCnsResponsavel?: string;
    numeroMembrosFamilia?: number;
    numeroProntuario?: string;
    rendaFamiliar?: number | Int64;
    resideDesde?: number | Int64;
    stMudanca?: boolean;
    cpfResponsavel?: string;
}
export class FamiliaRowThrift {
    public dataNascimentoResponsavel?: Int64;
    public numeroCnsResponsavel?: string;
    public numeroMembrosFamilia?: number;
    public numeroProntuario?: string;
    public rendaFamiliar?: Int64;
    public resideDesde?: Int64;
    public stMudanca?: boolean;
    public cpfResponsavel?: string;
    constructor(args?: IFamiliaRowThriftArgs) {
        if (args != null && args.dataNascimentoResponsavel != null) {
            if (typeof args.dataNascimentoResponsavel === "number") {
                this.dataNascimentoResponsavel = new Int64(args.dataNascimentoResponsavel);
            }
            else {
                this.dataNascimentoResponsavel = args.dataNascimentoResponsavel;
            }
        }
        if (args != null && args.numeroCnsResponsavel != null) {
            this.numeroCnsResponsavel = args.numeroCnsResponsavel;
        }
        if (args != null && args.numeroMembrosFamilia != null) {
            this.numeroMembrosFamilia = args.numeroMembrosFamilia;
        }
        if (args != null && args.numeroProntuario != null) {
            this.numeroProntuario = args.numeroProntuario;
        }
        if (args != null && args.rendaFamiliar != null) {
            if (typeof args.rendaFamiliar === "number") {
                this.rendaFamiliar = new Int64(args.rendaFamiliar);
            }
            else {
                this.rendaFamiliar = args.rendaFamiliar;
            }
        }
        if (args != null && args.resideDesde != null) {
            if (typeof args.resideDesde === "number") {
                this.resideDesde = new Int64(args.resideDesde);
            }
            else {
                this.resideDesde = args.resideDesde;
            }
        }
        if (args != null && args.stMudanca != null) {
            this.stMudanca = args.stMudanca;
        }
        if (args != null && args.cpfResponsavel != null) {
            this.cpfResponsavel = args.cpfResponsavel;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FamiliaRowThrift");
        if (this.dataNascimentoResponsavel != null) {
            output.writeFieldBegin("dataNascimentoResponsavel", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.dataNascimentoResponsavel);
            output.writeFieldEnd();
        }
        if (this.numeroCnsResponsavel != null) {
            output.writeFieldBegin("numeroCnsResponsavel", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.numeroCnsResponsavel);
            output.writeFieldEnd();
        }
        if (this.numeroMembrosFamilia != null) {
            output.writeFieldBegin("numeroMembrosFamilia", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.numeroMembrosFamilia);
            output.writeFieldEnd();
        }
        if (this.numeroProntuario != null) {
            output.writeFieldBegin("numeroProntuario", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.numeroProntuario);
            output.writeFieldEnd();
        }
        if (this.rendaFamiliar != null) {
            output.writeFieldBegin("rendaFamiliar", thrift.Thrift.Type.I64, 5);
            output.writeI64(this.rendaFamiliar);
            output.writeFieldEnd();
        }
        if (this.resideDesde != null) {
            output.writeFieldBegin("resideDesde", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.resideDesde);
            output.writeFieldEnd();
        }
        if (this.stMudanca != null) {
            output.writeFieldBegin("stMudanca", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.stMudanca);
            output.writeFieldEnd();
        }
        if (this.cpfResponsavel != null) {
            output.writeFieldBegin("cpfResponsavel", thrift.Thrift.Type.STRING, 8);
            output.writeString(this.cpfResponsavel);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FamiliaRowThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.dataNascimentoResponsavel = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.numeroCnsResponsavel = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.numeroMembrosFamilia = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.numeroProntuario = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_5: Int64 = input.readI64();
                        _args.rendaFamiliar = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.resideDesde = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_7: boolean = input.readBool();
                        _args.stMudanca = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_8: string = input.readString();
                        _args.cpfResponsavel = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new FamiliaRowThrift(_args);
    }
}
