/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as VacinaRowThrift from "./VacinaRowThrift";
export interface IFichaVacinacaoChildThriftArgs {
    turno?: number | Int64;
    numProntuario?: string;
    cnsCidadao?: string;
    dtNascimento?: number | Int64;
    sexo?: number | Int64;
    localAtendimento?: number | Int64;
    viajante?: boolean;
    comunicanteHanseniase?: boolean;
    vacinas?: Array<VacinaRowThrift.VacinaRowThrift>;
    dataHoraInicialAtendimento?: number | Int64;
    dataHoraFinalAtendimento?: number | Int64;
    cpfCidadao?: string;
    condicaoMaternal?: number | Int64;
}
export class FichaVacinacaoChildThrift {
    public turno?: Int64;
    public numProntuario?: string;
    public cnsCidadao?: string;
    public dtNascimento?: Int64;
    public sexo?: Int64;
    public localAtendimento?: Int64;
    public viajante?: boolean;
    public comunicanteHanseniase?: boolean;
    public vacinas?: Array<VacinaRowThrift.VacinaRowThrift>;
    public dataHoraInicialAtendimento?: Int64;
    public dataHoraFinalAtendimento?: Int64;
    public cpfCidadao?: string;
    public condicaoMaternal?: Int64;
    constructor(args?: IFichaVacinacaoChildThriftArgs) {
        if (args != null && args.turno != null) {
            if (typeof args.turno === "number") {
                this.turno = new Int64(args.turno);
            }
            else {
                this.turno = args.turno;
            }
        }
        if (args != null && args.numProntuario != null) {
            this.numProntuario = args.numProntuario;
        }
        if (args != null && args.cnsCidadao != null) {
            this.cnsCidadao = args.cnsCidadao;
        }
        if (args != null && args.dtNascimento != null) {
            if (typeof args.dtNascimento === "number") {
                this.dtNascimento = new Int64(args.dtNascimento);
            }
            else {
                this.dtNascimento = args.dtNascimento;
            }
        }
        if (args != null && args.sexo != null) {
            if (typeof args.sexo === "number") {
                this.sexo = new Int64(args.sexo);
            }
            else {
                this.sexo = args.sexo;
            }
        }
        if (args != null && args.localAtendimento != null) {
            if (typeof args.localAtendimento === "number") {
                this.localAtendimento = new Int64(args.localAtendimento);
            }
            else {
                this.localAtendimento = args.localAtendimento;
            }
        }
        if (args != null && args.viajante != null) {
            this.viajante = args.viajante;
        }
        if (args != null && args.comunicanteHanseniase != null) {
            this.comunicanteHanseniase = args.comunicanteHanseniase;
        }
        if (args != null && args.vacinas != null) {
            this.vacinas = args.vacinas;
        }
        if (args != null && args.dataHoraInicialAtendimento != null) {
            if (typeof args.dataHoraInicialAtendimento === "number") {
                this.dataHoraInicialAtendimento = new Int64(args.dataHoraInicialAtendimento);
            }
            else {
                this.dataHoraInicialAtendimento = args.dataHoraInicialAtendimento;
            }
        }
        if (args != null && args.dataHoraFinalAtendimento != null) {
            if (typeof args.dataHoraFinalAtendimento === "number") {
                this.dataHoraFinalAtendimento = new Int64(args.dataHoraFinalAtendimento);
            }
            else {
                this.dataHoraFinalAtendimento = args.dataHoraFinalAtendimento;
            }
        }
        if (args != null && args.cpfCidadao != null) {
            this.cpfCidadao = args.cpfCidadao;
        }
        if (args != null && args.condicaoMaternal != null) {
            if (typeof args.condicaoMaternal === "number") {
                this.condicaoMaternal = new Int64(args.condicaoMaternal);
            }
            else {
                this.condicaoMaternal = args.condicaoMaternal;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaVacinacaoChildThrift");
        if (this.turno != null) {
            output.writeFieldBegin("turno", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.turno);
            output.writeFieldEnd();
        }
        if (this.numProntuario != null) {
            output.writeFieldBegin("numProntuario", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.numProntuario);
            output.writeFieldEnd();
        }
        if (this.cnsCidadao != null) {
            output.writeFieldBegin("cnsCidadao", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.cnsCidadao);
            output.writeFieldEnd();
        }
        if (this.dtNascimento != null) {
            output.writeFieldBegin("dtNascimento", thrift.Thrift.Type.I64, 4);
            output.writeI64(this.dtNascimento);
            output.writeFieldEnd();
        }
        if (this.sexo != null) {
            output.writeFieldBegin("sexo", thrift.Thrift.Type.I64, 5);
            output.writeI64(this.sexo);
            output.writeFieldEnd();
        }
        if (this.localAtendimento != null) {
            output.writeFieldBegin("localAtendimento", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.localAtendimento);
            output.writeFieldEnd();
        }
        if (this.viajante != null) {
            output.writeFieldBegin("viajante", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.viajante);
            output.writeFieldEnd();
        }
        if (this.comunicanteHanseniase != null) {
            output.writeFieldBegin("comunicanteHanseniase", thrift.Thrift.Type.BOOL, 8);
            output.writeBool(this.comunicanteHanseniase);
            output.writeFieldEnd();
        }
        if (this.vacinas != null) {
            output.writeFieldBegin("vacinas", thrift.Thrift.Type.LIST, 9);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.vacinas.length);
            this.vacinas.forEach((value_1: VacinaRowThrift.VacinaRowThrift): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.dataHoraInicialAtendimento != null) {
            output.writeFieldBegin("dataHoraInicialAtendimento", thrift.Thrift.Type.I64, 10);
            output.writeI64(this.dataHoraInicialAtendimento);
            output.writeFieldEnd();
        }
        if (this.dataHoraFinalAtendimento != null) {
            output.writeFieldBegin("dataHoraFinalAtendimento", thrift.Thrift.Type.I64, 11);
            output.writeI64(this.dataHoraFinalAtendimento);
            output.writeFieldEnd();
        }
        if (this.cpfCidadao != null) {
            output.writeFieldBegin("cpfCidadao", thrift.Thrift.Type.STRING, 12);
            output.writeString(this.cpfCidadao);
            output.writeFieldEnd();
        }
        if (this.condicaoMaternal != null) {
            output.writeFieldBegin("condicaoMaternal", thrift.Thrift.Type.I64, 13);
            output.writeI64(this.condicaoMaternal);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FichaVacinacaoChildThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.turno = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.numProntuario = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.cnsCidadao = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_5: Int64 = input.readI64();
                        _args.dtNascimento = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.sexo = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_7: Int64 = input.readI64();
                        _args.localAtendimento = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_8: boolean = input.readBool();
                        _args.viajante = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_9: boolean = input.readBool();
                        _args.comunicanteHanseniase = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_10: Array<VacinaRowThrift.VacinaRowThrift> = new Array<VacinaRowThrift.VacinaRowThrift>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_11: VacinaRowThrift.VacinaRowThrift = VacinaRowThrift.VacinaRowThrift.read(input);
                            value_10.push(value_11);
                        }
                        input.readListEnd();
                        _args.vacinas = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_12: Int64 = input.readI64();
                        _args.dataHoraInicialAtendimento = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_13: Int64 = input.readI64();
                        _args.dataHoraFinalAtendimento = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_14: string = input.readString();
                        _args.cpfCidadao = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_15: Int64 = input.readI64();
                        _args.condicaoMaternal = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new FichaVacinacaoChildThrift(_args);
    }
}
