/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as VariasLotacoesHeaderThrift from "./VariasLotacoesHeaderThrift";
import * as FichaVacinacaoChildThrift from "./FichaVacinacaoChildThrift";
export interface IFichaVacinacaoMasterThriftArgs {
    uuidFicha: string;
    tpCdsOrigem?: number;
    headerTransport: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    vacinacoes?: Array<FichaVacinacaoChildThrift.FichaVacinacaoChildThrift>;
}
export class FichaVacinacaoMasterThrift {
    public uuidFicha: string;
    public tpCdsOrigem?: number;
    public headerTransport: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    public vacinacoes?: Array<FichaVacinacaoChildThrift.FichaVacinacaoChildThrift>;
    constructor(args: IFichaVacinacaoMasterThriftArgs) {
        if (args != null && args.uuidFicha != null) {
            this.uuidFicha = args.uuidFicha;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[uuidFicha] is unset!");
        }
        if (args != null && args.tpCdsOrigem != null) {
            this.tpCdsOrigem = args.tpCdsOrigem;
        }
        if (args != null && args.headerTransport != null) {
            this.headerTransport = args.headerTransport;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[headerTransport] is unset!");
        }
        if (args != null && args.vacinacoes != null) {
            this.vacinacoes = args.vacinacoes;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaVacinacaoMasterThrift");
        if (this.uuidFicha != null) {
            output.writeFieldBegin("uuidFicha", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.uuidFicha);
            output.writeFieldEnd();
        }
        if (this.tpCdsOrigem != null) {
            output.writeFieldBegin("tpCdsOrigem", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.tpCdsOrigem);
            output.writeFieldEnd();
        }
        if (this.headerTransport != null) {
            output.writeFieldBegin("headerTransport", thrift.Thrift.Type.STRUCT, 3);
            this.headerTransport.write(output);
            output.writeFieldEnd();
        }
        if (this.vacinacoes != null) {
            output.writeFieldBegin("vacinacoes", thrift.Thrift.Type.LIST, 4);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.vacinacoes.length);
            this.vacinacoes.forEach((value_1: FichaVacinacaoChildThrift.FichaVacinacaoChildThrift): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FichaVacinacaoMasterThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.uuidFicha = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.tpCdsOrigem = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift = VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift.read(input);
                        _args.headerTransport = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_5: Array<FichaVacinacaoChildThrift.FichaVacinacaoChildThrift> = new Array<FichaVacinacaoChildThrift.FichaVacinacaoChildThrift>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_6: FichaVacinacaoChildThrift.FichaVacinacaoChildThrift = FichaVacinacaoChildThrift.FichaVacinacaoChildThrift.read(input);
                            value_5.push(value_6);
                        }
                        input.readListEnd();
                        _args.vacinacoes = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.uuidFicha !== undefined && _args.headerTransport !== undefined) {
            return new FichaVacinacaoMasterThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read FichaVacinacaoMasterThrift from input");
        }
    }
}
