/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IFichaVisitaDomiciliarChildThriftArgs {
    turno?: number | Int64;
    numProntuario?: string;
    cnsCidadao?: string;
    dtNascimento?: number | Int64;
    sexo?: number | Int64;
    statusVisitaCompartilhadaOutroProfissional?: boolean;
    motivosVisita?: Array<number>;
    desfecho?: number | Int64;
    microarea?: string;
    stForaArea?: boolean;
    tipoDeImovel?: number | Int64;
    pesoAcompanhamentoNutricional?: number;
    alturaAcompanhamentoNutricional?: number;
    cpfCidadao?: string;
    pressaoSistolica?: number;
    pressaoDiastolica?: number;
    temperatura?: number;
    glicemia?: number;
    tipoGlicemia?: number | Int64;
    latitude?: number;
    longitude?: number;
    uuidOrigemCadastroDomiciliar?: string;
}
export class FichaVisitaDomiciliarChildThrift {
    public turno?: Int64;
    public numProntuario?: string;
    public cnsCidadao?: string;
    public dtNascimento?: Int64;
    public sexo?: Int64;
    public statusVisitaCompartilhadaOutroProfissional?: boolean;
    public motivosVisita?: Array<number>;
    public desfecho?: Int64;
    public microarea?: string;
    public stForaArea?: boolean;
    public tipoDeImovel?: Int64;
    public pesoAcompanhamentoNutricional?: number;
    public alturaAcompanhamentoNutricional?: number;
    public cpfCidadao?: string;
    public pressaoSistolica?: number;
    public pressaoDiastolica?: number;
    public temperatura?: number;
    public glicemia?: number;
    public tipoGlicemia?: Int64;
    public latitude?: number;
    public longitude?: number;
    public uuidOrigemCadastroDomiciliar?: string;
    constructor(args?: IFichaVisitaDomiciliarChildThriftArgs) {
        if (args != null && args.turno != null) {
            if (typeof args.turno === "number") {
                this.turno = new Int64(args.turno);
            }
            else {
                this.turno = args.turno;
            }
        }
        if (args != null && args.numProntuario != null) {
            this.numProntuario = args.numProntuario;
        }
        if (args != null && args.cnsCidadao != null) {
            this.cnsCidadao = args.cnsCidadao;
        }
        if (args != null && args.dtNascimento != null) {
            if (typeof args.dtNascimento === "number") {
                this.dtNascimento = new Int64(args.dtNascimento);
            }
            else {
                this.dtNascimento = args.dtNascimento;
            }
        }
        if (args != null && args.sexo != null) {
            if (typeof args.sexo === "number") {
                this.sexo = new Int64(args.sexo);
            }
            else {
                this.sexo = args.sexo;
            }
        }
        if (args != null && args.statusVisitaCompartilhadaOutroProfissional != null) {
            this.statusVisitaCompartilhadaOutroProfissional = args.statusVisitaCompartilhadaOutroProfissional;
        }
        if (args != null && args.motivosVisita != null) {
            this.motivosVisita = args.motivosVisita;
        }
        if (args != null && args.desfecho != null) {
            if (typeof args.desfecho === "number") {
                this.desfecho = new Int64(args.desfecho);
            }
            else {
                this.desfecho = args.desfecho;
            }
        }
        if (args != null && args.microarea != null) {
            this.microarea = args.microarea;
        }
        if (args != null && args.stForaArea != null) {
            this.stForaArea = args.stForaArea;
        }
        if (args != null && args.tipoDeImovel != null) {
            if (typeof args.tipoDeImovel === "number") {
                this.tipoDeImovel = new Int64(args.tipoDeImovel);
            }
            else {
                this.tipoDeImovel = args.tipoDeImovel;
            }
        }
        if (args != null && args.pesoAcompanhamentoNutricional != null) {
            this.pesoAcompanhamentoNutricional = args.pesoAcompanhamentoNutricional;
        }
        if (args != null && args.alturaAcompanhamentoNutricional != null) {
            this.alturaAcompanhamentoNutricional = args.alturaAcompanhamentoNutricional;
        }
        if (args != null && args.cpfCidadao != null) {
            this.cpfCidadao = args.cpfCidadao;
        }
        if (args != null && args.pressaoSistolica != null) {
            this.pressaoSistolica = args.pressaoSistolica;
        }
        if (args != null && args.pressaoDiastolica != null) {
            this.pressaoDiastolica = args.pressaoDiastolica;
        }
        if (args != null && args.temperatura != null) {
            this.temperatura = args.temperatura;
        }
        if (args != null && args.glicemia != null) {
            this.glicemia = args.glicemia;
        }
        if (args != null && args.tipoGlicemia != null) {
            if (typeof args.tipoGlicemia === "number") {
                this.tipoGlicemia = new Int64(args.tipoGlicemia);
            }
            else {
                this.tipoGlicemia = args.tipoGlicemia;
            }
        }
        if (args != null && args.latitude != null) {
            this.latitude = args.latitude;
        }
        if (args != null && args.longitude != null) {
            this.longitude = args.longitude;
        }
        if (args != null && args.uuidOrigemCadastroDomiciliar != null) {
            this.uuidOrigemCadastroDomiciliar = args.uuidOrigemCadastroDomiciliar;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaVisitaDomiciliarChildThrift");
        if (this.turno != null) {
            output.writeFieldBegin("turno", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.turno);
            output.writeFieldEnd();
        }
        if (this.numProntuario != null) {
            output.writeFieldBegin("numProntuario", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.numProntuario);
            output.writeFieldEnd();
        }
        if (this.cnsCidadao != null) {
            output.writeFieldBegin("cnsCidadao", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.cnsCidadao);
            output.writeFieldEnd();
        }
        if (this.dtNascimento != null) {
            output.writeFieldBegin("dtNascimento", thrift.Thrift.Type.I64, 4);
            output.writeI64(this.dtNascimento);
            output.writeFieldEnd();
        }
        if (this.sexo != null) {
            output.writeFieldBegin("sexo", thrift.Thrift.Type.I64, 5);
            output.writeI64(this.sexo);
            output.writeFieldEnd();
        }
        if (this.statusVisitaCompartilhadaOutroProfissional != null) {
            output.writeFieldBegin("statusVisitaCompartilhadaOutroProfissional", thrift.Thrift.Type.BOOL, 6);
            output.writeBool(this.statusVisitaCompartilhadaOutroProfissional);
            output.writeFieldEnd();
        }
        if (this.motivosVisita != null) {
            output.writeFieldBegin("motivosVisita", thrift.Thrift.Type.LIST, 7);
            output.writeListBegin(thrift.Thrift.Type.I32, this.motivosVisita.length);
            this.motivosVisita.forEach((value_1: number): void => {
                output.writeI32(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.desfecho != null) {
            output.writeFieldBegin("desfecho", thrift.Thrift.Type.I64, 8);
            output.writeI64(this.desfecho);
            output.writeFieldEnd();
        }
        if (this.microarea != null) {
            output.writeFieldBegin("microarea", thrift.Thrift.Type.STRING, 9);
            output.writeString(this.microarea);
            output.writeFieldEnd();
        }
        if (this.stForaArea != null) {
            output.writeFieldBegin("stForaArea", thrift.Thrift.Type.BOOL, 10);
            output.writeBool(this.stForaArea);
            output.writeFieldEnd();
        }
        if (this.tipoDeImovel != null) {
            output.writeFieldBegin("tipoDeImovel", thrift.Thrift.Type.I64, 11);
            output.writeI64(this.tipoDeImovel);
            output.writeFieldEnd();
        }
        if (this.pesoAcompanhamentoNutricional != null) {
            output.writeFieldBegin("pesoAcompanhamentoNutricional", thrift.Thrift.Type.DOUBLE, 12);
            output.writeDouble(this.pesoAcompanhamentoNutricional);
            output.writeFieldEnd();
        }
        if (this.alturaAcompanhamentoNutricional != null) {
            output.writeFieldBegin("alturaAcompanhamentoNutricional", thrift.Thrift.Type.DOUBLE, 13);
            output.writeDouble(this.alturaAcompanhamentoNutricional);
            output.writeFieldEnd();
        }
        if (this.cpfCidadao != null) {
            output.writeFieldBegin("cpfCidadao", thrift.Thrift.Type.STRING, 14);
            output.writeString(this.cpfCidadao);
            output.writeFieldEnd();
        }
        if (this.pressaoSistolica != null) {
            output.writeFieldBegin("pressaoSistolica", thrift.Thrift.Type.I32, 15);
            output.writeI32(this.pressaoSistolica);
            output.writeFieldEnd();
        }
        if (this.pressaoDiastolica != null) {
            output.writeFieldBegin("pressaoDiastolica", thrift.Thrift.Type.I32, 16);
            output.writeI32(this.pressaoDiastolica);
            output.writeFieldEnd();
        }
        if (this.temperatura != null) {
            output.writeFieldBegin("temperatura", thrift.Thrift.Type.DOUBLE, 17);
            output.writeDouble(this.temperatura);
            output.writeFieldEnd();
        }
        if (this.glicemia != null) {
            output.writeFieldBegin("glicemia", thrift.Thrift.Type.I32, 18);
            output.writeI32(this.glicemia);
            output.writeFieldEnd();
        }
        if (this.tipoGlicemia != null) {
            output.writeFieldBegin("tipoGlicemia", thrift.Thrift.Type.I64, 19);
            output.writeI64(this.tipoGlicemia);
            output.writeFieldEnd();
        }
        if (this.latitude != null) {
            output.writeFieldBegin("latitude", thrift.Thrift.Type.DOUBLE, 20);
            output.writeDouble(this.latitude);
            output.writeFieldEnd();
        }
        if (this.longitude != null) {
            output.writeFieldBegin("longitude", thrift.Thrift.Type.DOUBLE, 21);
            output.writeDouble(this.longitude);
            output.writeFieldEnd();
        }
        if (this.uuidOrigemCadastroDomiciliar != null) {
            output.writeFieldBegin("uuidOrigemCadastroDomiciliar", thrift.Thrift.Type.STRING, 22);
            output.writeString(this.uuidOrigemCadastroDomiciliar);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FichaVisitaDomiciliarChildThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.turno = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.numProntuario = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.cnsCidadao = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_5: Int64 = input.readI64();
                        _args.dtNascimento = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.sexo = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_7: boolean = input.readBool();
                        _args.statusVisitaCompartilhadaOutroProfissional = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_8: Array<number> = new Array<number>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_9: number = input.readI32();
                            value_8.push(value_9);
                        }
                        input.readListEnd();
                        _args.motivosVisita = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_10: Int64 = input.readI64();
                        _args.desfecho = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_11: string = input.readString();
                        _args.microarea = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_12: boolean = input.readBool();
                        _args.stForaArea = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_13: Int64 = input.readI64();
                        _args.tipoDeImovel = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_14: number = input.readDouble();
                        _args.pesoAcompanhamentoNutricional = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_15: number = input.readDouble();
                        _args.alturaAcompanhamentoNutricional = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_16: string = input.readString();
                        _args.cpfCidadao = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_17: number = input.readI32();
                        _args.pressaoSistolica = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_18: number = input.readI32();
                        _args.pressaoDiastolica = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_19: number = input.readDouble();
                        _args.temperatura = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_20: number = input.readI32();
                        _args.glicemia = value_20;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 19:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_21: Int64 = input.readI64();
                        _args.tipoGlicemia = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 20:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_22: number = input.readDouble();
                        _args.latitude = value_22;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 21:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_23: number = input.readDouble();
                        _args.longitude = value_23;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 22:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_24: string = input.readString();
                        _args.uuidOrigemCadastroDomiciliar = value_24;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new FichaVisitaDomiciliarChildThrift(_args);
    }
}
