/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as VariasLotacoesHeaderThrift from "./VariasLotacoesHeaderThrift";
import * as FichaProcedimentoChildThrift from "./FichaProcedimentoChildThrift";
export interface IFichaProcedimentoMasterThriftArgs {
    uuidFicha: string;
    tpCdsOrigem?: number;
    headerTransport: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    atendProcedimentos?: Array<FichaProcedimentoChildThrift.FichaProcedimentoChildThrift>;
    numTotalAfericaoPa?: number;
    numTotalGlicemiaCapilar?: number;
    numTotalAfericaoTemperatura?: number;
    numTotalMedicaoAltura?: number;
    numTotalCurativoSimples?: number;
    numTotalMedicaoPeso?: number;
    numTotalColetaMaterialParaExameLaboratorial?: number;
}
export class FichaProcedimentoMasterThrift {
    public uuidFicha: string;
    public tpCdsOrigem?: number;
    public headerTransport: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    public atendProcedimentos?: Array<FichaProcedimentoChildThrift.FichaProcedimentoChildThrift>;
    public numTotalAfericaoPa?: number;
    public numTotalGlicemiaCapilar?: number;
    public numTotalAfericaoTemperatura?: number;
    public numTotalMedicaoAltura?: number;
    public numTotalCurativoSimples?: number;
    public numTotalMedicaoPeso?: number;
    public numTotalColetaMaterialParaExameLaboratorial?: number;
    constructor(args: IFichaProcedimentoMasterThriftArgs) {
        if (args != null && args.uuidFicha != null) {
            this.uuidFicha = args.uuidFicha;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[uuidFicha] is unset!");
        }
        if (args != null && args.tpCdsOrigem != null) {
            this.tpCdsOrigem = args.tpCdsOrigem;
        }
        if (args != null && args.headerTransport != null) {
            this.headerTransport = args.headerTransport;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[headerTransport] is unset!");
        }
        if (args != null && args.atendProcedimentos != null) {
            this.atendProcedimentos = args.atendProcedimentos;
        }
        if (args != null && args.numTotalAfericaoPa != null) {
            this.numTotalAfericaoPa = args.numTotalAfericaoPa;
        }
        if (args != null && args.numTotalGlicemiaCapilar != null) {
            this.numTotalGlicemiaCapilar = args.numTotalGlicemiaCapilar;
        }
        if (args != null && args.numTotalAfericaoTemperatura != null) {
            this.numTotalAfericaoTemperatura = args.numTotalAfericaoTemperatura;
        }
        if (args != null && args.numTotalMedicaoAltura != null) {
            this.numTotalMedicaoAltura = args.numTotalMedicaoAltura;
        }
        if (args != null && args.numTotalCurativoSimples != null) {
            this.numTotalCurativoSimples = args.numTotalCurativoSimples;
        }
        if (args != null && args.numTotalMedicaoPeso != null) {
            this.numTotalMedicaoPeso = args.numTotalMedicaoPeso;
        }
        if (args != null && args.numTotalColetaMaterialParaExameLaboratorial != null) {
            this.numTotalColetaMaterialParaExameLaboratorial = args.numTotalColetaMaterialParaExameLaboratorial;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaProcedimentoMasterThrift");
        if (this.uuidFicha != null) {
            output.writeFieldBegin("uuidFicha", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.uuidFicha);
            output.writeFieldEnd();
        }
        if (this.tpCdsOrigem != null) {
            output.writeFieldBegin("tpCdsOrigem", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.tpCdsOrigem);
            output.writeFieldEnd();
        }
        if (this.headerTransport != null) {
            output.writeFieldBegin("headerTransport", thrift.Thrift.Type.STRUCT, 3);
            this.headerTransport.write(output);
            output.writeFieldEnd();
        }
        if (this.atendProcedimentos != null) {
            output.writeFieldBegin("atendProcedimentos", thrift.Thrift.Type.LIST, 4);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.atendProcedimentos.length);
            this.atendProcedimentos.forEach((value_1: FichaProcedimentoChildThrift.FichaProcedimentoChildThrift): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.numTotalAfericaoPa != null) {
            output.writeFieldBegin("numTotalAfericaoPa", thrift.Thrift.Type.I32, 5);
            output.writeI32(this.numTotalAfericaoPa);
            output.writeFieldEnd();
        }
        if (this.numTotalGlicemiaCapilar != null) {
            output.writeFieldBegin("numTotalGlicemiaCapilar", thrift.Thrift.Type.I32, 6);
            output.writeI32(this.numTotalGlicemiaCapilar);
            output.writeFieldEnd();
        }
        if (this.numTotalAfericaoTemperatura != null) {
            output.writeFieldBegin("numTotalAfericaoTemperatura", thrift.Thrift.Type.I32, 7);
            output.writeI32(this.numTotalAfericaoTemperatura);
            output.writeFieldEnd();
        }
        if (this.numTotalMedicaoAltura != null) {
            output.writeFieldBegin("numTotalMedicaoAltura", thrift.Thrift.Type.I32, 8);
            output.writeI32(this.numTotalMedicaoAltura);
            output.writeFieldEnd();
        }
        if (this.numTotalCurativoSimples != null) {
            output.writeFieldBegin("numTotalCurativoSimples", thrift.Thrift.Type.I32, 9);
            output.writeI32(this.numTotalCurativoSimples);
            output.writeFieldEnd();
        }
        if (this.numTotalMedicaoPeso != null) {
            output.writeFieldBegin("numTotalMedicaoPeso", thrift.Thrift.Type.I32, 10);
            output.writeI32(this.numTotalMedicaoPeso);
            output.writeFieldEnd();
        }
        if (this.numTotalColetaMaterialParaExameLaboratorial != null) {
            output.writeFieldBegin("numTotalColetaMaterialParaExameLaboratorial", thrift.Thrift.Type.I32, 11);
            output.writeI32(this.numTotalColetaMaterialParaExameLaboratorial);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FichaProcedimentoMasterThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.uuidFicha = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.tpCdsOrigem = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_4: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift = VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift.read(input);
                        _args.headerTransport = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_5: Array<FichaProcedimentoChildThrift.FichaProcedimentoChildThrift> = new Array<FichaProcedimentoChildThrift.FichaProcedimentoChildThrift>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_6: FichaProcedimentoChildThrift.FichaProcedimentoChildThrift = FichaProcedimentoChildThrift.FichaProcedimentoChildThrift.read(input);
                            value_5.push(value_6);
                        }
                        input.readListEnd();
                        _args.atendProcedimentos = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_7: number = input.readI32();
                        _args.numTotalAfericaoPa = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_8: number = input.readI32();
                        _args.numTotalGlicemiaCapilar = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_9: number = input.readI32();
                        _args.numTotalAfericaoTemperatura = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_10: number = input.readI32();
                        _args.numTotalMedicaoAltura = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_11: number = input.readI32();
                        _args.numTotalCurativoSimples = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_12: number = input.readI32();
                        _args.numTotalMedicaoPeso = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_13: number = input.readI32();
                        _args.numTotalColetaMaterialParaExameLaboratorial = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.uuidFicha !== undefined && _args.headerTransport !== undefined) {
            return new FichaProcedimentoMasterThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read FichaProcedimentoMasterThrift from input");
        }
    }
}
