/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 */
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as MedicoesThrift from "./MedicoesThrift";
import * as ExameThrift from "./ExameThrift";
import * as ProblemaCondicaoThrift from "./ProblemaCondicaoThrift";
import * as MedicamentoThrift from "./MedicamentoThrift";
import * as EncaminhamentoThrift from "./EncaminhamentoThrift";
import * as ResultadosExameThrift from "./ResultadosExameThrift";
import * as IvcfThrift from "./IvcfThrift";
import * as SolicitacaoOutraCondutaThrift from "./SolicitacaoOutraCondutaThrift";
import * as LotacaoHeaderThrift from "./LotacaoHeaderThrift";

export interface IFichaAtendimentoIndividualChildThriftArgs {
    numeroProntuario?: string;
    cnsCidadao?: string; // Note: Node file calls it "cns" (ID 2), TS file called it "cnsCidadao". I will keep TS name for compatibility or check mapping? Node: this.cns = args.cns; TS: cnsCidadao. The ID is what matters. 
    dataNascimento?: number | Int64;
    localDeAtendimento?: number | Int64;
    sexo?: number | Int64;
    turno?: number | Int64;
    tipoAtendimento?: number | Int64;
    aleitamentoMaterno?: number | Int64;
    dumDaGestante?: number | Int64;
    idadeGestacional?: number;
    atencaoDomiciliarModalidade?: number | Int64;
    exame?: Array<ExameThrift.ExameThrift>;
    vacinaEmDia?: boolean;
    pic?: number | Int64;
    ficouEmObservacao?: boolean;
    nasfs?: Array<number | Int64>;
    condutas?: Array<number | Int64>;
    stGravidezPlanejada?: boolean;
    nuGestasPrevias?: number;
    nuPartos?: number;
    racionalidadeSaude?: number | Int64;
    dataHoraInicialAtendimento?: number | Int64;
    dataHoraFinalAtendimento?: number | Int64;
    cpfCidadao?: string;
    medicamentos?: Array<MedicamentoThrift.MedicamentoThrift>;
    encaminhamentos?: Array<EncaminhamentoThrift.EncaminhamentoThrift>;
    resultadosExames?: Array<ResultadosExameThrift.ResultadosExameThrift>;
    finalizadorObservacao?: LotacaoHeaderThrift.LotacaoHeaderThrift;
    tipoParticipacaoCidadao?: number | Int64;
    tipoParticipacaoProfissionalConvidado?: number | Int64;
    emultis?: Array<number | Int64>;
    medicoes?: MedicoesThrift.MedicoesThrift;
    problemasCondicoes?: Array<ProblemaCondicaoThrift.ProblemaCondicaoThrift>;
    ivcf?: IvcfThrift.IvcfThrift;
    solicitacoesOci?: Array<SolicitacaoOutraCondutaThrift.SolicitacaoOutraCondutaThrift>;
}

export class FichaAtendimentoIndividualChildThrift {
    public numeroProntuario?: string;
    public cnsCidadao?: string;
    public dataNascimento?: Int64;
    public localDeAtendimento?: Int64;
    public sexo?: Int64;
    public turno?: Int64;
    public tipoAtendimento?: Int64;
    public aleitamentoMaterno?: Int64;
    public dumDaGestante?: Int64;
    public idadeGestacional?: number;
    public atencaoDomiciliarModalidade?: Int64;
    public exame?: Array<ExameThrift.ExameThrift>;
    public vacinaEmDia?: boolean;
    public pic?: Int64;
    public ficouEmObservacao?: boolean;
    public nasfs?: Array<Int64>;
    public condutas?: Array<Int64>;
    public stGravidezPlanejada?: boolean;
    public nuGestasPrevias?: number;
    public nuPartos?: number;
    public racionalidadeSaude?: Int64;
    public dataHoraInicialAtendimento?: Int64;
    public dataHoraFinalAtendimento?: Int64;
    public cpfCidadao?: string;
    public medicamentos?: Array<MedicamentoThrift.MedicamentoThrift>;
    public encaminhamentos?: Array<EncaminhamentoThrift.EncaminhamentoThrift>;
    public resultadosExames?: Array<ResultadosExameThrift.ResultadosExameThrift>;
    public finalizadorObservacao?: LotacaoHeaderThrift.LotacaoHeaderThrift;
    public tipoParticipacaoCidadao?: Int64;
    public tipoParticipacaoProfissionalConvidado?: Int64;
    public emultis?: Array<Int64>;
    public medicoes?: MedicoesThrift.MedicoesThrift;
    public problemasCondicoes?: Array<ProblemaCondicaoThrift.ProblemaCondicaoThrift>;
    public ivcf?: IvcfThrift.IvcfThrift;
    public solicitacoesOci?: Array<SolicitacaoOutraCondutaThrift.SolicitacaoOutraCondutaThrift>;

    constructor(args?: IFichaAtendimentoIndividualChildThriftArgs) {
        if (args != null && args.numeroProntuario != null) {
            this.numeroProntuario = args.numeroProntuario;
        }
        if (args != null && args.cnsCidadao != null) {
            this.cnsCidadao = args.cnsCidadao;
        }
        if (args != null && args.dataNascimento != null) {
            if (typeof args.dataNascimento === "number") {
                this.dataNascimento = new Int64(args.dataNascimento);
            } else {
                this.dataNascimento = args.dataNascimento;
            }
        }
        if (args != null && args.localDeAtendimento != null) {
            if (typeof args.localDeAtendimento === "number") {
                this.localDeAtendimento = new Int64(args.localDeAtendimento);
            } else {
                this.localDeAtendimento = args.localDeAtendimento;
            }
        }
        if (args != null && args.sexo != null) {
            if (typeof args.sexo === "number") {
                this.sexo = new Int64(args.sexo);
            } else {
                this.sexo = args.sexo;
            }
        }
        if (args != null && args.turno != null) {
            if (typeof args.turno === "number") {
                this.turno = new Int64(args.turno);
            } else {
                this.turno = args.turno;
            }
        }
        if (args != null && args.tipoAtendimento != null) {
            if (typeof args.tipoAtendimento === "number") {
                this.tipoAtendimento = new Int64(args.tipoAtendimento);
            } else {
                this.tipoAtendimento = args.tipoAtendimento;
            }
        }
        if (args != null && args.aleitamentoMaterno != null) {
            if (typeof args.aleitamentoMaterno === "number") {
                this.aleitamentoMaterno = new Int64(args.aleitamentoMaterno);
            } else {
                this.aleitamentoMaterno = args.aleitamentoMaterno;
            }
        }
        if (args != null && args.dumDaGestante != null) {
            if (typeof args.dumDaGestante === "number") {
                this.dumDaGestante = new Int64(args.dumDaGestante);
            } else {
                this.dumDaGestante = args.dumDaGestante;
            }
        }
        if (args != null && args.idadeGestacional != null) {
            this.idadeGestacional = args.idadeGestacional;
        }
        if (args != null && args.atencaoDomiciliarModalidade != null) {
            if (typeof args.atencaoDomiciliarModalidade === "number") {
                this.atencaoDomiciliarModalidade = new Int64(args.atencaoDomiciliarModalidade);
            } else {
                this.atencaoDomiciliarModalidade = args.atencaoDomiciliarModalidade;
            }
        }
        if (args != null && args.exame != null) {
            this.exame = args.exame;
        }
        if (args != null && args.vacinaEmDia != null) {
            this.vacinaEmDia = args.vacinaEmDia;
        }
        if (args != null && args.pic != null) {
            if (typeof args.pic === "number") {
                this.pic = new Int64(args.pic);
            } else {
                this.pic = args.pic;
            }
        }
        if (args != null && args.ficouEmObservacao != null) {
            this.ficouEmObservacao = args.ficouEmObservacao;
        }
        if (args != null && args.nasfs != null) {
            this.nasfs = args.nasfs.map(v => typeof v === 'number' ? new Int64(v) : v);
        }
        if (args != null && args.condutas != null) {
            this.condutas = args.condutas.map(v => typeof v === 'number' ? new Int64(v) : v);
        }
        if (args != null && args.stGravidezPlanejada != null) {
            this.stGravidezPlanejada = args.stGravidezPlanejada;
        }
        if (args != null && args.nuGestasPrevias != null) {
            this.nuGestasPrevias = args.nuGestasPrevias;
        }
        if (args != null && args.nuPartos != null) {
            this.nuPartos = args.nuPartos;
        }
        if (args != null && args.racionalidadeSaude != null) {
            if (typeof args.racionalidadeSaude === "number") {
                this.racionalidadeSaude = new Int64(args.racionalidadeSaude);
            } else {
                this.racionalidadeSaude = args.racionalidadeSaude;
            }
        }
        if (args != null && args.dataHoraInicialAtendimento != null) {
            if (typeof args.dataHoraInicialAtendimento === "number") {
                this.dataHoraInicialAtendimento = new Int64(args.dataHoraInicialAtendimento);
            } else {
                this.dataHoraInicialAtendimento = args.dataHoraInicialAtendimento;
            }
        }
        if (args != null && args.dataHoraFinalAtendimento != null) {
            if (typeof args.dataHoraFinalAtendimento === "number") {
                this.dataHoraFinalAtendimento = new Int64(args.dataHoraFinalAtendimento);
            } else {
                this.dataHoraFinalAtendimento = args.dataHoraFinalAtendimento;
            }
        }
        if (args != null && args.cpfCidadao != null) {
            this.cpfCidadao = args.cpfCidadao;
        }
        if (args != null && args.medicamentos != null) {
            this.medicamentos = args.medicamentos;
        }
        if (args != null && args.encaminhamentos != null) {
            this.encaminhamentos = args.encaminhamentos;
        }
        if (args != null && args.resultadosExames != null) {
            this.resultadosExames = args.resultadosExames;
        }
        if (args != null && args.finalizadorObservacao != null) {
            this.finalizadorObservacao = args.finalizadorObservacao;
        }
        if (args != null && args.tipoParticipacaoCidadao != null) {
            if (typeof args.tipoParticipacaoCidadao === "number") {
                this.tipoParticipacaoCidadao = new Int64(args.tipoParticipacaoCidadao);
            } else {
                this.tipoParticipacaoCidadao = args.tipoParticipacaoCidadao;
            }
        }
        if (args != null && args.tipoParticipacaoProfissionalConvidado != null) {
            if (typeof args.tipoParticipacaoProfissionalConvidado === "number") {
                this.tipoParticipacaoProfissionalConvidado = new Int64(args.tipoParticipacaoProfissionalConvidado);
            } else {
                this.tipoParticipacaoProfissionalConvidado = args.tipoParticipacaoProfissionalConvidado;
            }
        }
        if (args != null && args.emultis != null) {
            this.emultis = args.emultis.map(v => typeof v === 'number' ? new Int64(v) : v);
        }
        if (args != null && args.medicoes != null) {
            this.medicoes = args.medicoes;
        }
        if (args != null && args.problemasCondicoes != null) {
            this.problemasCondicoes = args.problemasCondicoes;
        }
        if (args != null && args.ivcf != null) {
            this.ivcf = args.ivcf;
        }
        if (args != null && args.solicitacoesOci != null) {
            this.solicitacoesOci = args.solicitacoesOci;
        }
    }

    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaAtendimentoIndividualChildThrift");
        if (this.numeroProntuario != null) {
            output.writeFieldBegin("numeroProntuario", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.numeroProntuario);
            output.writeFieldEnd();
        }
        if (this.cnsCidadao != null) {
            output.writeFieldBegin("cnsCidadao", thrift.Thrift.Type.STRING, 2); // Matched ID 2 (cns in msg, cnsCidadao in TS)
            output.writeString(this.cnsCidadao);
            output.writeFieldEnd();
        }
        if (this.dataNascimento != null) {
            output.writeFieldBegin("dataNascimento", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.dataNascimento);
            output.writeFieldEnd();
        }
        if (this.localDeAtendimento != null) {
            output.writeFieldBegin("localDeAtendimento", thrift.Thrift.Type.I64, 4);
            output.writeI64(this.localDeAtendimento);
            output.writeFieldEnd();
        }
        if (this.sexo != null) {
            output.writeFieldBegin("sexo", thrift.Thrift.Type.I64, 5);
            output.writeI64(this.sexo);
            output.writeFieldEnd();
        }
        if (this.turno != null) {
            output.writeFieldBegin("turno", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.turno);
            output.writeFieldEnd();
        }
        if (this.tipoAtendimento != null) {
            output.writeFieldBegin("tipoAtendimento", thrift.Thrift.Type.I64, 7);
            output.writeI64(this.tipoAtendimento);
            output.writeFieldEnd();
        }
        if (this.aleitamentoMaterno != null) {
            output.writeFieldBegin("aleitamentoMaterno", thrift.Thrift.Type.I64, 10);
            output.writeI64(this.aleitamentoMaterno);
            output.writeFieldEnd();
        }
        if (this.dumDaGestante != null) {
            output.writeFieldBegin("dumDaGestante", thrift.Thrift.Type.I64, 11);
            output.writeI64(this.dumDaGestante);
            output.writeFieldEnd();
        }
        if (this.idadeGestacional != null) {
            output.writeFieldBegin("idadeGestacional", thrift.Thrift.Type.I32, 12);
            output.writeI32(this.idadeGestacional);
            output.writeFieldEnd();
        }
        if (this.atencaoDomiciliarModalidade != null) {
            output.writeFieldBegin("atencaoDomiciliarModalidade", thrift.Thrift.Type.I64, 13);
            output.writeI64(this.atencaoDomiciliarModalidade);
            output.writeFieldEnd();
        }
        if (this.exame != null) {
            output.writeFieldBegin("exame", thrift.Thrift.Type.LIST, 17);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.exame.length);
            this.exame.forEach((value_1: ExameThrift.ExameThrift): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.vacinaEmDia != null) {
            output.writeFieldBegin("vacinaEmDia", thrift.Thrift.Type.BOOL, 18);
            output.writeBool(this.vacinaEmDia);
            output.writeFieldEnd();
        }
        if (this.pic != null) {
            output.writeFieldBegin("pic", thrift.Thrift.Type.I64, 19);
            output.writeI64(this.pic);
            output.writeFieldEnd();
        }
        if (this.ficouEmObservacao != null) {
            output.writeFieldBegin("ficouEmObservacao", thrift.Thrift.Type.BOOL, 20);
            output.writeBool(this.ficouEmObservacao);
            output.writeFieldEnd();
        }
        if (this.nasfs != null) {
            output.writeFieldBegin("nasfs", thrift.Thrift.Type.LIST, 21);
            output.writeListBegin(thrift.Thrift.Type.I64, this.nasfs.length);
            this.nasfs.forEach((value_2: Int64): void => {
                output.writeI64(value_2);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.condutas != null) {
            output.writeFieldBegin("condutas", thrift.Thrift.Type.LIST, 22);
            output.writeListBegin(thrift.Thrift.Type.I64, this.condutas.length);
            this.condutas.forEach((value_3: Int64): void => {
                output.writeI64(value_3);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.stGravidezPlanejada != null) {
            output.writeFieldBegin("stGravidezPlanejada", thrift.Thrift.Type.BOOL, 23);
            output.writeBool(this.stGravidezPlanejada);
            output.writeFieldEnd();
        }
        if (this.nuGestasPrevias != null) {
            output.writeFieldBegin("nuGestasPrevias", thrift.Thrift.Type.I32, 24);
            output.writeI32(this.nuGestasPrevias);
            output.writeFieldEnd();
        }
        if (this.nuPartos != null) {
            output.writeFieldBegin("nuPartos", thrift.Thrift.Type.I32, 25);
            output.writeI32(this.nuPartos);
            output.writeFieldEnd();
        }
        if (this.racionalidadeSaude != null) {
            output.writeFieldBegin("racionalidadeSaude", thrift.Thrift.Type.I64, 26);
            output.writeI64(this.racionalidadeSaude);
            output.writeFieldEnd();
        }
        if (this.dataHoraInicialAtendimento != null) {
            output.writeFieldBegin("dataHoraInicialAtendimento", thrift.Thrift.Type.I64, 28);
            output.writeI64(this.dataHoraInicialAtendimento);
            output.writeFieldEnd();
        }
        if (this.dataHoraFinalAtendimento != null) {
            output.writeFieldBegin("dataHoraFinalAtendimento", thrift.Thrift.Type.I64, 29);
            output.writeI64(this.dataHoraFinalAtendimento);
            output.writeFieldEnd();
        }
        if (this.cpfCidadao != null) {
            output.writeFieldBegin("cpfCidadao", thrift.Thrift.Type.STRING, 30);
            output.writeString(this.cpfCidadao);
            output.writeFieldEnd();
        }
        if (this.medicamentos != null) {
            output.writeFieldBegin("medicamentos", thrift.Thrift.Type.LIST, 31);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.medicamentos.length);
            this.medicamentos.forEach((value: MedicamentoThrift.MedicamentoThrift): void => {
                value.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.encaminhamentos != null) {
            output.writeFieldBegin("encaminhamentos", thrift.Thrift.Type.LIST, 32);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.encaminhamentos.length);
            this.encaminhamentos.forEach((value: EncaminhamentoThrift.EncaminhamentoThrift): void => {
                value.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.resultadosExames != null) {
            output.writeFieldBegin("resultadosExames", thrift.Thrift.Type.LIST, 33);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.resultadosExames.length);
            this.resultadosExames.forEach((value: ResultadosExameThrift.ResultadosExameThrift): void => {
                value.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.finalizadorObservacao != null) {
            output.writeFieldBegin("finalizadorObservacao", thrift.Thrift.Type.STRUCT, 35);
            this.finalizadorObservacao.write(output);
            output.writeFieldEnd();
        }
        if (this.tipoParticipacaoCidadao != null) {
            output.writeFieldBegin("tipoParticipacaoCidadao", thrift.Thrift.Type.I64, 36);
            output.writeI64(this.tipoParticipacaoCidadao);
            output.writeFieldEnd();
        }
        if (this.tipoParticipacaoProfissionalConvidado != null) {
            output.writeFieldBegin("tipoParticipacaoProfissionalConvidado", thrift.Thrift.Type.I64, 37);
            output.writeI64(this.tipoParticipacaoProfissionalConvidado);
            output.writeFieldEnd();
        }
        if (this.emultis != null) {
            output.writeFieldBegin("emultis", thrift.Thrift.Type.LIST, 38);
            output.writeListBegin(thrift.Thrift.Type.I64, this.emultis.length);
            this.emultis.forEach((value: Int64): void => {
                output.writeI64(value);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.medicoes != null) {
            output.writeFieldBegin("medicoes", thrift.Thrift.Type.STRUCT, 39);
            this.medicoes.write(output);
            output.writeFieldEnd();
        }
        if (this.problemasCondicoes != null) {
            output.writeFieldBegin("problemasCondicoes", thrift.Thrift.Type.LIST, 40);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.problemasCondicoes.length);
            this.problemasCondicoes.forEach((value_4: ProblemaCondicaoThrift.ProblemaCondicaoThrift): void => {
                value_4.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.ivcf != null) {
            output.writeFieldBegin("ivcf", thrift.Thrift.Type.STRUCT, 41);
            this.ivcf.write(output);
            output.writeFieldEnd();
        }
        if (this.solicitacoesOci != null) {
            output.writeFieldBegin("solicitacoesOci", thrift.Thrift.Type.LIST, 43);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.solicitacoesOci.length);
            this.solicitacoesOci.forEach((value: SolicitacaoOutraCondutaThrift.SolicitacaoOutraCondutaThrift): void => {
                value.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }

    public static read(input: thrift.TProtocol): FichaAtendimentoIndividualChildThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        _args.numeroProntuario = input.readString();
                    } else input.skip(fieldType);
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        _args.cnsCidadao = input.readString();
                    } else input.skip(fieldType);
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.dataNascimento = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.localDeAtendimento = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.sexo = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.turno = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.tipoAtendimento = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.aleitamentoMaterno = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.dumDaGestante = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        _args.idadeGestacional = input.readI32();
                    } else input.skip(fieldType);
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.atencaoDomiciliarModalidade = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<ExameThrift.ExameThrift> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(ExameThrift.ExameThrift.read(input));
                        }
                        input.readListEnd();
                        _args.exame = value;
                    } else input.skip(fieldType);
                    break;
                case 18:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        _args.vacinaEmDia = input.readBool();
                    } else input.skip(fieldType);
                    break;
                case 19:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.pic = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 20:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        _args.ficouEmObservacao = input.readBool();
                    } else input.skip(fieldType);
                    break;
                case 21:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<Int64> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(input.readI64());
                        }
                        input.readListEnd();
                        _args.nasfs = value;
                    } else input.skip(fieldType);
                    break;
                case 22:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<Int64> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(input.readI64());
                        }
                        input.readListEnd();
                        _args.condutas = value;
                    } else input.skip(fieldType);
                    break;
                case 23:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        _args.stGravidezPlanejada = input.readBool();
                    } else input.skip(fieldType);
                    break;
                case 24:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        _args.nuGestasPrevias = input.readI32();
                    } else input.skip(fieldType);
                    break;
                case 25:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        _args.nuPartos = input.readI32();
                    } else input.skip(fieldType);
                    break;
                case 26:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.racionalidadeSaude = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 28:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.dataHoraInicialAtendimento = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 29:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.dataHoraFinalAtendimento = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 30:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        _args.cpfCidadao = input.readString();
                    } else input.skip(fieldType);
                    break;
                case 31:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<MedicamentoThrift.MedicamentoThrift> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(MedicamentoThrift.MedicamentoThrift.read(input));
                        }
                        input.readListEnd();
                        _args.medicamentos = value;
                    } else input.skip(fieldType);
                    break;
                case 32:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<EncaminhamentoThrift.EncaminhamentoThrift> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(EncaminhamentoThrift.EncaminhamentoThrift.read(input));
                        }
                        input.readListEnd();
                        _args.encaminhamentos = value;
                    } else input.skip(fieldType);
                    break;
                case 33:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<ResultadosExameThrift.ResultadosExameThrift> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(ResultadosExameThrift.ResultadosExameThrift.read(input));
                        }
                        input.readListEnd();
                        _args.resultadosExames = value;
                    } else input.skip(fieldType);
                    break;
                case 35:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _args.finalizadorObservacao = LotacaoHeaderThrift.LotacaoHeaderThrift.read(input);
                    } else input.skip(fieldType);
                    break;
                case 36:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.tipoParticipacaoCidadao = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 37:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        _args.tipoParticipacaoProfissionalConvidado = input.readI64();
                    } else input.skip(fieldType);
                    break;
                case 38:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<Int64> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(input.readI64());
                        }
                        input.readListEnd();
                        _args.emultis = value;
                    } else input.skip(fieldType);
                    break;
                case 39:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _args.medicoes = MedicoesThrift.MedicoesThrift.read(input);
                    } else input.skip(fieldType);
                    break;
                case 40:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<ProblemaCondicaoThrift.ProblemaCondicaoThrift> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(ProblemaCondicaoThrift.ProblemaCondicaoThrift.read(input));
                        }
                        input.readListEnd();
                        _args.problemasCondicoes = value;
                    } else input.skip(fieldType);
                    break;
                case 41:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        _args.ivcf = IvcfThrift.IvcfThrift.read(input);
                    } else input.skip(fieldType);
                    break;
                case 43:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value: Array<SolicitacaoOutraCondutaThrift.SolicitacaoOutraCondutaThrift> = [];
                        const metadata = input.readListBegin();
                        for (let i = 0; i < metadata.size; i++) {
                            value.push(SolicitacaoOutraCondutaThrift.SolicitacaoOutraCondutaThrift.read(input));
                        }
                        input.readListEnd();
                        _args.solicitacoesOci = value;
                    } else input.skip(fieldType);
                    break;
                default:
                    input.skip(fieldType);
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new FichaAtendimentoIndividualChildThrift(_args);
    }
}
