/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as ProfissionalColetivaThrift from "./ProfissionalColetivaThrift";
import * as ParticipanteRowThrift from "./ParticipanteRowThrift";
import * as VariasLotacoesHeaderThrift from "./VariasLotacoesHeaderThrift";
export interface IFichaAtividadeColetivaMasterThriftArgs {
    uuidFicha: string;
    outraLocalidade?: string;
    inep?: number | Int64;
    numParticipantes?: number;
    numAvaliacoesAlteradas?: number;
    profissionais?: Array<ProfissionalColetivaThrift.ProfissionalColetivaThrift>;
    atividadeTipo?: number | Int64;
    temasParaReuniao?: Array<number>;
    publicoAlvo?: Array<number>;
    praticasEmSaude?: Array<number>;
    temasParaSaude?: Array<number>;
    participantes?: Array<ParticipanteRowThrift.ParticipanteRowThrift>;
    tpCdsOrigem?: number;
    cnesLocalAtividade: string;
    procedimento?: string;
    turno?: number | Int64;
    headerTransport: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    pseEducacao?: number | Int64;
    pseSaude?: number | Int64;
}
export class FichaAtividadeColetivaMasterThrift {
    public uuidFicha: string;
    public outraLocalidade?: string;
    public inep?: Int64;
    public numParticipantes?: number;
    public numAvaliacoesAlteradas?: number;
    public profissionais?: Array<ProfissionalColetivaThrift.ProfissionalColetivaThrift>;
    public atividadeTipo?: Int64;
    public temasParaReuniao?: Array<number>;
    public publicoAlvo?: Array<number>;
    public praticasEmSaude?: Array<number>;
    public temasParaSaude?: Array<number>;
    public participantes?: Array<ParticipanteRowThrift.ParticipanteRowThrift>;
    public tpCdsOrigem?: number;
    public cnesLocalAtividade: string;
    public procedimento?: string;
    public turno?: Int64;
    public headerTransport: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift;
    public pseEducacao?: Int64;
    public pseSaude?: Int64;
    constructor(args: IFichaAtividadeColetivaMasterThriftArgs) {
        if (args != null && args.uuidFicha != null) {
            this.uuidFicha = args.uuidFicha;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[uuidFicha] is unset!");
        }
        if (args != null && args.outraLocalidade != null) {
            this.outraLocalidade = args.outraLocalidade;
        }
        if (args != null && args.inep != null) {
            if (typeof args.inep === "number") {
                this.inep = new Int64(args.inep);
            }
            else {
                this.inep = args.inep;
            }
        }
        if (args != null && args.numParticipantes != null) {
            this.numParticipantes = args.numParticipantes;
        }
        if (args != null && args.numAvaliacoesAlteradas != null) {
            this.numAvaliacoesAlteradas = args.numAvaliacoesAlteradas;
        }
        if (args != null && args.profissionais != null) {
            this.profissionais = args.profissionais;
        }
        if (args != null && args.atividadeTipo != null) {
            if (typeof args.atividadeTipo === "number") {
                this.atividadeTipo = new Int64(args.atividadeTipo);
            }
            else {
                this.atividadeTipo = args.atividadeTipo;
            }
        }
        if (args != null && args.temasParaReuniao != null) {
            this.temasParaReuniao = args.temasParaReuniao;
        }
        if (args != null && args.publicoAlvo != null) {
            this.publicoAlvo = args.publicoAlvo;
        }
        if (args != null && args.praticasEmSaude != null) {
            this.praticasEmSaude = args.praticasEmSaude;
        }
        if (args != null && args.temasParaSaude != null) {
            this.temasParaSaude = args.temasParaSaude;
        }
        if (args != null && args.participantes != null) {
            this.participantes = args.participantes;
        }
        if (args != null && args.tpCdsOrigem != null) {
            this.tpCdsOrigem = args.tpCdsOrigem;
        }
        if (args != null && args.cnesLocalAtividade != null) {
            this.cnesLocalAtividade = args.cnesLocalAtividade;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cnesLocalAtividade] is unset!");
        }
        if (args != null && args.procedimento != null) {
            this.procedimento = args.procedimento;
        }
        if (args != null && args.turno != null) {
            if (typeof args.turno === "number") {
                this.turno = new Int64(args.turno);
            }
            else {
                this.turno = args.turno;
            }
        }
        if (args != null && args.headerTransport != null) {
            this.headerTransport = args.headerTransport;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[headerTransport] is unset!");
        }
        if (args != null && args.pseEducacao != null) {
            if (typeof args.pseEducacao === "number") {
                this.pseEducacao = new Int64(args.pseEducacao);
            }
            else {
                this.pseEducacao = args.pseEducacao;
            }
        }
        if (args != null && args.pseSaude != null) {
            if (typeof args.pseSaude === "number") {
                this.pseSaude = new Int64(args.pseSaude);
            }
            else {
                this.pseSaude = args.pseSaude;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaAtividadeColetivaMasterThrift");
        if (this.uuidFicha != null) {
            output.writeFieldBegin("uuidFicha", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.uuidFicha);
            output.writeFieldEnd();
        }
        if (this.outraLocalidade != null) {
            output.writeFieldBegin("outraLocalidade", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.outraLocalidade);
            output.writeFieldEnd();
        }
        if (this.inep != null) {
            output.writeFieldBegin("inep", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.inep);
            output.writeFieldEnd();
        }
        if (this.numParticipantes != null) {
            output.writeFieldBegin("numParticipantes", thrift.Thrift.Type.I32, 4);
            output.writeI32(this.numParticipantes);
            output.writeFieldEnd();
        }
        if (this.numAvaliacoesAlteradas != null) {
            output.writeFieldBegin("numAvaliacoesAlteradas", thrift.Thrift.Type.I32, 5);
            output.writeI32(this.numAvaliacoesAlteradas);
            output.writeFieldEnd();
        }
        if (this.profissionais != null) {
            output.writeFieldBegin("profissionais", thrift.Thrift.Type.LIST, 6);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.profissionais.length);
            this.profissionais.forEach((value_1: ProfissionalColetivaThrift.ProfissionalColetivaThrift): void => {
                value_1.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.atividadeTipo != null) {
            output.writeFieldBegin("atividadeTipo", thrift.Thrift.Type.I64, 7);
            output.writeI64(this.atividadeTipo);
            output.writeFieldEnd();
        }
        if (this.temasParaReuniao != null) {
            output.writeFieldBegin("temasParaReuniao", thrift.Thrift.Type.LIST, 8);
            output.writeListBegin(thrift.Thrift.Type.I32, this.temasParaReuniao.length);
            this.temasParaReuniao.forEach((value_2: number): void => {
                output.writeI32(value_2);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.publicoAlvo != null) {
            output.writeFieldBegin("publicoAlvo", thrift.Thrift.Type.LIST, 9);
            output.writeListBegin(thrift.Thrift.Type.I32, this.publicoAlvo.length);
            this.publicoAlvo.forEach((value_3: number): void => {
                output.writeI32(value_3);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.praticasEmSaude != null) {
            output.writeFieldBegin("praticasEmSaude", thrift.Thrift.Type.LIST, 10);
            output.writeListBegin(thrift.Thrift.Type.I32, this.praticasEmSaude.length);
            this.praticasEmSaude.forEach((value_4: number): void => {
                output.writeI32(value_4);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.temasParaSaude != null) {
            output.writeFieldBegin("temasParaSaude", thrift.Thrift.Type.LIST, 11);
            output.writeListBegin(thrift.Thrift.Type.I32, this.temasParaSaude.length);
            this.temasParaSaude.forEach((value_5: number): void => {
                output.writeI32(value_5);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.participantes != null) {
            output.writeFieldBegin("participantes", thrift.Thrift.Type.LIST, 12);
            output.writeListBegin(thrift.Thrift.Type.STRUCT, this.participantes.length);
            this.participantes.forEach((value_6: ParticipanteRowThrift.ParticipanteRowThrift): void => {
                value_6.write(output);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.tpCdsOrigem != null) {
            output.writeFieldBegin("tpCdsOrigem", thrift.Thrift.Type.I32, 13);
            output.writeI32(this.tpCdsOrigem);
            output.writeFieldEnd();
        }
        if (this.cnesLocalAtividade != null) {
            output.writeFieldBegin("cnesLocalAtividade", thrift.Thrift.Type.STRING, 14);
            output.writeString(this.cnesLocalAtividade);
            output.writeFieldEnd();
        }
        if (this.procedimento != null) {
            output.writeFieldBegin("procedimento", thrift.Thrift.Type.STRING, 15);
            output.writeString(this.procedimento);
            output.writeFieldEnd();
        }
        if (this.turno != null) {
            output.writeFieldBegin("turno", thrift.Thrift.Type.I64, 16);
            output.writeI64(this.turno);
            output.writeFieldEnd();
        }
        if (this.headerTransport != null) {
            output.writeFieldBegin("headerTransport", thrift.Thrift.Type.STRUCT, 17);
            this.headerTransport.write(output);
            output.writeFieldEnd();
        }
        if (this.pseEducacao != null) {
            output.writeFieldBegin("pseEducacao", thrift.Thrift.Type.I64, 18);
            output.writeI64(this.pseEducacao);
            output.writeFieldEnd();
        }
        if (this.pseSaude != null) {
            output.writeFieldBegin("pseSaude", thrift.Thrift.Type.I64, 19);
            output.writeI64(this.pseSaude);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FichaAtividadeColetivaMasterThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: string = input.readString();
                        _args.uuidFicha = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_8: string = input.readString();
                        _args.outraLocalidade = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_9: Int64 = input.readI64();
                        _args.inep = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_10: number = input.readI32();
                        _args.numParticipantes = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_11: number = input.readI32();
                        _args.numAvaliacoesAlteradas = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_12: Array<ProfissionalColetivaThrift.ProfissionalColetivaThrift> = new Array<ProfissionalColetivaThrift.ProfissionalColetivaThrift>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_13: ProfissionalColetivaThrift.ProfissionalColetivaThrift = ProfissionalColetivaThrift.ProfissionalColetivaThrift.read(input);
                            value_12.push(value_13);
                        }
                        input.readListEnd();
                        _args.profissionais = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_14: Int64 = input.readI64();
                        _args.atividadeTipo = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_15: Array<number> = new Array<number>();
                        const metadata_2: thrift.TList = input.readListBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const value_16: number = input.readI32();
                            value_15.push(value_16);
                        }
                        input.readListEnd();
                        _args.temasParaReuniao = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_17: Array<number> = new Array<number>();
                        const metadata_3: thrift.TList = input.readListBegin();
                        const size_3: number = metadata_3.size;
                        for (let i_3: number = 0; i_3 < size_3; i_3++) {
                            const value_18: number = input.readI32();
                            value_17.push(value_18);
                        }
                        input.readListEnd();
                        _args.publicoAlvo = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_19: Array<number> = new Array<number>();
                        const metadata_4: thrift.TList = input.readListBegin();
                        const size_4: number = metadata_4.size;
                        for (let i_4: number = 0; i_4 < size_4; i_4++) {
                            const value_20: number = input.readI32();
                            value_19.push(value_20);
                        }
                        input.readListEnd();
                        _args.praticasEmSaude = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_21: Array<number> = new Array<number>();
                        const metadata_5: thrift.TList = input.readListBegin();
                        const size_5: number = metadata_5.size;
                        for (let i_5: number = 0; i_5 < size_5; i_5++) {
                            const value_22: number = input.readI32();
                            value_21.push(value_22);
                        }
                        input.readListEnd();
                        _args.temasParaSaude = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_23: Array<ParticipanteRowThrift.ParticipanteRowThrift> = new Array<ParticipanteRowThrift.ParticipanteRowThrift>();
                        const metadata_6: thrift.TList = input.readListBegin();
                        const size_6: number = metadata_6.size;
                        for (let i_6: number = 0; i_6 < size_6; i_6++) {
                            const value_24: ParticipanteRowThrift.ParticipanteRowThrift = ParticipanteRowThrift.ParticipanteRowThrift.read(input);
                            value_23.push(value_24);
                        }
                        input.readListEnd();
                        _args.participantes = value_23;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_25: number = input.readI32();
                        _args.tpCdsOrigem = value_25;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_26: string = input.readString();
                        _args.cnesLocalAtividade = value_26;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_27: string = input.readString();
                        _args.procedimento = value_27;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_28: Int64 = input.readI64();
                        _args.turno = value_28;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_29: VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift = VariasLotacoesHeaderThrift.VariasLotacoesHeaderThrift.read(input);
                        _args.headerTransport = value_29;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_30: Int64 = input.readI64();
                        _args.pseEducacao = value_30;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 19:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_31: Int64 = input.readI64();
                        _args.pseSaude = value_31;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.uuidFicha !== undefined && _args.cnesLocalAtividade !== undefined && _args.headerTransport !== undefined) {
            return new FichaAtividadeColetivaMasterThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read FichaAtividadeColetivaMasterThrift from input");
        }
    }
}
