/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
import * as MedicoesThrift from "./MedicoesThrift";
import * as IvcfThrift from "./IvcfThrift";
export interface IFichaProcedimentoChildThriftArgs {
    numProntuario?: string;
    cnsCidadao?: string;
    cpfCidadao?: string;
    dtNascimento?: number | Int64;
    sexo?: number | Int64;
    localAtendimento?: number | Int64;
    turno?: number | Int64;
    statusEscutaInicialOrientacao?: boolean;
    procedimentos?: Array<string>;
    dataHoraInicialAtendimento?: number | Int64;
    dataHoraFinalAtendimento?: number | Int64;
    medicoes?: MedicoesThrift.MedicoesThrift;
    ivcf?: IvcfThrift.IvcfThrift;
}
export class FichaProcedimentoChildThrift {
    public numProntuario?: string;
    public cnsCidadao?: string;
    public cpfCidadao?: string;
    public dtNascimento?: Int64;
    public sexo?: Int64;
    public localAtendimento?: Int64;
    public turno?: Int64;
    public statusEscutaInicialOrientacao?: boolean;
    public procedimentos?: Array<string>;
    public dataHoraInicialAtendimento?: Int64;
    public dataHoraFinalAtendimento?: Int64;
    public medicoes?: MedicoesThrift.MedicoesThrift;
    public ivcf?: IvcfThrift.IvcfThrift;
    constructor(args?: IFichaProcedimentoChildThriftArgs) {
        if (args != null && args.numProntuario != null) {
            this.numProntuario = args.numProntuario;
        }
        if (args != null && args.cnsCidadao != null) {
            this.cnsCidadao = args.cnsCidadao;
        }
        if (args != null && args.cpfCidadao != null) {
            this.cpfCidadao = args.cpfCidadao;
        }
        if (args != null && args.dtNascimento != null) {
            if (typeof args.dtNascimento === "number") {
                this.dtNascimento = new Int64(args.dtNascimento);
            }
            else {
                this.dtNascimento = args.dtNascimento;
            }
        }
        if (args != null && args.sexo != null) {
            if (typeof args.sexo === "number") {
                this.sexo = new Int64(args.sexo);
            }
            else {
                this.sexo = args.sexo;
            }
        }
        if (args != null && args.localAtendimento != null) {
            if (typeof args.localAtendimento === "number") {
                this.localAtendimento = new Int64(args.localAtendimento);
            }
            else {
                this.localAtendimento = args.localAtendimento;
            }
        }
        if (args != null && args.turno != null) {
            if (typeof args.turno === "number") {
                this.turno = new Int64(args.turno);
            }
            else {
                this.turno = args.turno;
            }
        }
        if (args != null && args.statusEscutaInicialOrientacao != null) {
            this.statusEscutaInicialOrientacao = args.statusEscutaInicialOrientacao;
        }
        if (args != null && args.procedimentos != null) {
            this.procedimentos = args.procedimentos;
        }
        if (args != null && args.dataHoraInicialAtendimento != null) {
            if (typeof args.dataHoraInicialAtendimento === "number") {
                this.dataHoraInicialAtendimento = new Int64(args.dataHoraInicialAtendimento);
            }
            else {
                this.dataHoraInicialAtendimento = args.dataHoraInicialAtendimento;
            }
        }
        if (args != null && args.dataHoraFinalAtendimento != null) {
            if (typeof args.dataHoraFinalAtendimento === "number") {
                this.dataHoraFinalAtendimento = new Int64(args.dataHoraFinalAtendimento);
            }
            else {
                this.dataHoraFinalAtendimento = args.dataHoraFinalAtendimento;
            }
        }
        if (args != null && args.medicoes != null) {
            this.medicoes = args.medicoes;
        }
        if (args != null && args.ivcf != null) {
            this.ivcf = args.ivcf;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("FichaProcedimentoChildThrift");
        if (this.numProntuario != null) {
            output.writeFieldBegin("numProntuario", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.numProntuario);
            output.writeFieldEnd();
        }
        if (this.cnsCidadao != null) {
            output.writeFieldBegin("cnsCidadao", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.cnsCidadao);
            output.writeFieldEnd();
        }
        if (this.dtNascimento != null) {
            output.writeFieldBegin("dtNascimento", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.dtNascimento);
            output.writeFieldEnd();
        }
        if (this.sexo != null) {
            output.writeFieldBegin("sexo", thrift.Thrift.Type.I64, 4);
            output.writeI64(this.sexo);
            output.writeFieldEnd();
        }
        if (this.localAtendimento != null) {
            output.writeFieldBegin("localAtendimento", thrift.Thrift.Type.I64, 5);
            output.writeI64(this.localAtendimento);
            output.writeFieldEnd();
        }
        if (this.turno != null) {
            output.writeFieldBegin("turno", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.turno);
            output.writeFieldEnd();
        }
        if (this.statusEscutaInicialOrientacao != null) {
            output.writeFieldBegin("statusEscutaInicialOrientacao", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.statusEscutaInicialOrientacao);
            output.writeFieldEnd();
        }
        if (this.procedimentos != null) {
            output.writeFieldBegin("procedimentos", thrift.Thrift.Type.LIST, 8);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.procedimentos.length);
            this.procedimentos.forEach((value_1: string): void => {
                output.writeString(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.dataHoraInicialAtendimento != null) {
            output.writeFieldBegin("dataHoraInicialAtendimento", thrift.Thrift.Type.I64, 10);
            output.writeI64(this.dataHoraInicialAtendimento);
            output.writeFieldEnd();
        }
        if (this.dataHoraFinalAtendimento != null) {
            output.writeFieldBegin("dataHoraFinalAtendimento", thrift.Thrift.Type.I64, 11);
            output.writeI64(this.dataHoraFinalAtendimento);
            output.writeFieldEnd();
        }
        if (this.cpfCidadao != null) {
            output.writeFieldBegin("cpfCidadao", thrift.Thrift.Type.STRING, 12);
            output.writeString(this.cpfCidadao);
            output.writeFieldEnd();
        }
        if (this.medicoes != null) {
            output.writeFieldBegin("medicoes", thrift.Thrift.Type.STRUCT, 16);
            this.medicoes.write(output);
            output.writeFieldEnd();
        }
        if (this.ivcf != null) {
            output.writeFieldBegin("ivcf", thrift.Thrift.Type.STRUCT, 17);
            this.ivcf.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): FichaProcedimentoChildThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.numProntuario = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.cnsCidadao = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_4: Int64 = input.readI64();
                        _args.dtNascimento = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_5: Int64 = input.readI64();
                        _args.sexo = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.localAtendimento = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_7: Int64 = input.readI64();
                        _args.turno = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_8: boolean = input.readBool();
                        _args.statusEscutaInicialOrientacao = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_9: Array<string> = new Array<string>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_10: string = input.readString();
                            value_9.push(value_10);
                        }
                        input.readListEnd();
                        _args.procedimentos = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_11: Int64 = input.readI64();
                        _args.dataHoraInicialAtendimento = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_12: Int64 = input.readI64();
                        _args.dataHoraFinalAtendimento = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_13: string = input.readString();
                        _args.cpfCidadao = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_14: MedicoesThrift.MedicoesThrift = MedicoesThrift.MedicoesThrift.read(input);
                        _args.medicoes = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_15: IvcfThrift.IvcfThrift = IvcfThrift.IvcfThrift.read(input);
                        _args.ivcf = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new FichaProcedimentoChildThrift(_args);
    }
}
