/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IIdentificacaoUsuarioCidadaoThriftArgs {
    nomeSocial?: string;
    codigoIbgeMunicipioNascimento?: string;
    dataNascimentoCidadao?: number | Int64;
    desconheceNomeMae?: boolean;
    emailCidadao?: string;
    nacionalidadeCidadao?: number | Int64;
    nomeCidadao: string;
    nomeMaeCidadao?: string;
    cnsCidadao?: string;
    cnsResponsavelFamiliar?: string;
    telefoneCelular?: string;
    numeroNisPisPasep?: string;
    paisNascimento?: number | Int64;
    racaCorCidadao?: number | Int64;
    sexoCidadao?: number | Int64;
    statusEhResponsavel?: boolean;
    etnia?: number | Int64;
    nomePaiCidadao?: string;
    desconheceNomePai?: boolean;
    dtNaturalizacao?: number | Int64;
    portariaNaturalizacao?: string;
    dtEntradaBrasil?: number | Int64;
    microarea?: string;
    stForaArea?: boolean;
    cpfCidadao?: string;
    cpfResponsavelFamiliar?: string;
}
export class IdentificacaoUsuarioCidadaoThrift {
    public nomeSocial?: string;
    public codigoIbgeMunicipioNascimento?: string;
    public dataNascimentoCidadao?: Int64;
    public desconheceNomeMae?: boolean;
    public emailCidadao?: string;
    public nacionalidadeCidadao?: Int64;
    public nomeCidadao: string;
    public nomeMaeCidadao?: string;
    public cnsCidadao?: string;
    public cnsResponsavelFamiliar?: string;
    public telefoneCelular?: string;
    public numeroNisPisPasep?: string;
    public paisNascimento?: Int64;
    public racaCorCidadao?: Int64;
    public sexoCidadao?: Int64;
    public statusEhResponsavel?: boolean;
    public etnia?: Int64;
    public nomePaiCidadao?: string;
    public desconheceNomePai?: boolean;
    public dtNaturalizacao?: Int64;
    public portariaNaturalizacao?: string;
    public dtEntradaBrasil?: Int64;
    public microarea?: string;
    public stForaArea?: boolean;
    public cpfCidadao?: string;
    public cpfResponsavelFamiliar?: string;
    constructor(args: IIdentificacaoUsuarioCidadaoThriftArgs) {
        if (args != null && args.nomeSocial != null) {
            this.nomeSocial = args.nomeSocial;
        }
        if (args != null && args.codigoIbgeMunicipioNascimento != null) {
            this.codigoIbgeMunicipioNascimento = args.codigoIbgeMunicipioNascimento;
        }
        if (args != null && args.dataNascimentoCidadao != null) {
            if (typeof args.dataNascimentoCidadao === "number") {
                this.dataNascimentoCidadao = new Int64(args.dataNascimentoCidadao);
            }
            else {
                this.dataNascimentoCidadao = args.dataNascimentoCidadao;
            }
        }
        if (args != null && args.desconheceNomeMae != null) {
            this.desconheceNomeMae = args.desconheceNomeMae;
        }
        if (args != null && args.emailCidadao != null) {
            this.emailCidadao = args.emailCidadao;
        }
        if (args != null && args.nacionalidadeCidadao != null) {
            if (typeof args.nacionalidadeCidadao === "number") {
                this.nacionalidadeCidadao = new Int64(args.nacionalidadeCidadao);
            }
            else {
                this.nacionalidadeCidadao = args.nacionalidadeCidadao;
            }
        }
        if (args != null && args.nomeCidadao != null) {
            this.nomeCidadao = args.nomeCidadao;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[nomeCidadao] is unset!");
        }
        if (args != null && args.nomeMaeCidadao != null) {
            this.nomeMaeCidadao = args.nomeMaeCidadao;
        }
        if (args != null && args.cnsCidadao != null) {
            this.cnsCidadao = args.cnsCidadao;
        }
        if (args != null && args.cnsResponsavelFamiliar != null) {
            this.cnsResponsavelFamiliar = args.cnsResponsavelFamiliar;
        }
        if (args != null && args.telefoneCelular != null) {
            this.telefoneCelular = args.telefoneCelular;
        }
        if (args != null && args.numeroNisPisPasep != null) {
            this.numeroNisPisPasep = args.numeroNisPisPasep;
        }
        if (args != null && args.paisNascimento != null) {
            if (typeof args.paisNascimento === "number") {
                this.paisNascimento = new Int64(args.paisNascimento);
            }
            else {
                this.paisNascimento = args.paisNascimento;
            }
        }
        if (args != null && args.racaCorCidadao != null) {
            if (typeof args.racaCorCidadao === "number") {
                this.racaCorCidadao = new Int64(args.racaCorCidadao);
            }
            else {
                this.racaCorCidadao = args.racaCorCidadao;
            }
        }
        if (args != null && args.sexoCidadao != null) {
            if (typeof args.sexoCidadao === "number") {
                this.sexoCidadao = new Int64(args.sexoCidadao);
            }
            else {
                this.sexoCidadao = args.sexoCidadao;
            }
        }
        if (args != null && args.statusEhResponsavel != null) {
            this.statusEhResponsavel = args.statusEhResponsavel;
        }
        if (args != null && args.etnia != null) {
            if (typeof args.etnia === "number") {
                this.etnia = new Int64(args.etnia);
            }
            else {
                this.etnia = args.etnia;
            }
        }
        if (args != null && args.nomePaiCidadao != null) {
            this.nomePaiCidadao = args.nomePaiCidadao;
        }
        if (args != null && args.desconheceNomePai != null) {
            this.desconheceNomePai = args.desconheceNomePai;
        }
        if (args != null && args.dtNaturalizacao != null) {
            if (typeof args.dtNaturalizacao === "number") {
                this.dtNaturalizacao = new Int64(args.dtNaturalizacao);
            }
            else {
                this.dtNaturalizacao = args.dtNaturalizacao;
            }
        }
        if (args != null && args.portariaNaturalizacao != null) {
            this.portariaNaturalizacao = args.portariaNaturalizacao;
        }
        if (args != null && args.dtEntradaBrasil != null) {
            if (typeof args.dtEntradaBrasil === "number") {
                this.dtEntradaBrasil = new Int64(args.dtEntradaBrasil);
            }
            else {
                this.dtEntradaBrasil = args.dtEntradaBrasil;
            }
        }
        if (args != null && args.microarea != null) {
            this.microarea = args.microarea;
        }
        if (args != null && args.stForaArea != null) {
            this.stForaArea = args.stForaArea;
        }
        if (args != null && args.cpfCidadao != null) {
            this.cpfCidadao = args.cpfCidadao;
        }
        if (args != null && args.cpfResponsavelFamiliar != null) {
            this.cpfResponsavelFamiliar = args.cpfResponsavelFamiliar;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("IdentificacaoUsuarioCidadaoThrift");
        if (this.nomeSocial != null) {
            output.writeFieldBegin("nomeSocial", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.nomeSocial);
            output.writeFieldEnd();
        }
        if (this.codigoIbgeMunicipioNascimento != null) {
            output.writeFieldBegin("codigoIbgeMunicipioNascimento", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.codigoIbgeMunicipioNascimento);
            output.writeFieldEnd();
        }
        if (this.dataNascimentoCidadao != null) {
            output.writeFieldBegin("dataNascimentoCidadao", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.dataNascimentoCidadao);
            output.writeFieldEnd();
        }
        if (this.desconheceNomeMae != null) {
            output.writeFieldBegin("desconheceNomeMae", thrift.Thrift.Type.BOOL, 4);
            output.writeBool(this.desconheceNomeMae);
            output.writeFieldEnd();
        }
        if (this.emailCidadao != null) {
            output.writeFieldBegin("emailCidadao", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.emailCidadao);
            output.writeFieldEnd();
        }
        if (this.nacionalidadeCidadao != null) {
            output.writeFieldBegin("nacionalidadeCidadao", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.nacionalidadeCidadao);
            output.writeFieldEnd();
        }
        if (this.nomeCidadao != null) {
            output.writeFieldBegin("nomeCidadao", thrift.Thrift.Type.STRING, 7);
            output.writeString(this.nomeCidadao);
            output.writeFieldEnd();
        }
        if (this.nomeMaeCidadao != null) {
            output.writeFieldBegin("nomeMaeCidadao", thrift.Thrift.Type.STRING, 8);
            output.writeString(this.nomeMaeCidadao);
            output.writeFieldEnd();
        }
        if (this.cnsCidadao != null) {
            output.writeFieldBegin("cnsCidadao", thrift.Thrift.Type.STRING, 9);
            output.writeString(this.cnsCidadao);
            output.writeFieldEnd();
        }
        if (this.cnsResponsavelFamiliar != null) {
            output.writeFieldBegin("cnsResponsavelFamiliar", thrift.Thrift.Type.STRING, 10);
            output.writeString(this.cnsResponsavelFamiliar);
            output.writeFieldEnd();
        }
        if (this.telefoneCelular != null) {
            output.writeFieldBegin("telefoneCelular", thrift.Thrift.Type.STRING, 11);
            output.writeString(this.telefoneCelular);
            output.writeFieldEnd();
        }
        if (this.numeroNisPisPasep != null) {
            output.writeFieldBegin("numeroNisPisPasep", thrift.Thrift.Type.STRING, 12);
            output.writeString(this.numeroNisPisPasep);
            output.writeFieldEnd();
        }
        if (this.paisNascimento != null) {
            output.writeFieldBegin("paisNascimento", thrift.Thrift.Type.I64, 13);
            output.writeI64(this.paisNascimento);
            output.writeFieldEnd();
        }
        if (this.racaCorCidadao != null) {
            output.writeFieldBegin("racaCorCidadao", thrift.Thrift.Type.I64, 14);
            output.writeI64(this.racaCorCidadao);
            output.writeFieldEnd();
        }
        if (this.sexoCidadao != null) {
            output.writeFieldBegin("sexoCidadao", thrift.Thrift.Type.I64, 15);
            output.writeI64(this.sexoCidadao);
            output.writeFieldEnd();
        }
        if (this.statusEhResponsavel != null) {
            output.writeFieldBegin("statusEhResponsavel", thrift.Thrift.Type.BOOL, 16);
            output.writeBool(this.statusEhResponsavel);
            output.writeFieldEnd();
        }
        if (this.etnia != null) {
            output.writeFieldBegin("etnia", thrift.Thrift.Type.I64, 17);
            output.writeI64(this.etnia);
            output.writeFieldEnd();
        }
        if (this.nomePaiCidadao != null) {
            output.writeFieldBegin("nomePaiCidadao", thrift.Thrift.Type.STRING, 18);
            output.writeString(this.nomePaiCidadao);
            output.writeFieldEnd();
        }
        if (this.desconheceNomePai != null) {
            output.writeFieldBegin("desconheceNomePai", thrift.Thrift.Type.BOOL, 19);
            output.writeBool(this.desconheceNomePai);
            output.writeFieldEnd();
        }
        if (this.dtNaturalizacao != null) {
            output.writeFieldBegin("dtNaturalizacao", thrift.Thrift.Type.I64, 20);
            output.writeI64(this.dtNaturalizacao);
            output.writeFieldEnd();
        }
        if (this.portariaNaturalizacao != null) {
            output.writeFieldBegin("portariaNaturalizacao", thrift.Thrift.Type.STRING, 21);
            output.writeString(this.portariaNaturalizacao);
            output.writeFieldEnd();
        }
        if (this.dtEntradaBrasil != null) {
            output.writeFieldBegin("dtEntradaBrasil", thrift.Thrift.Type.I64, 22);
            output.writeI64(this.dtEntradaBrasil);
            output.writeFieldEnd();
        }
        if (this.microarea != null) {
            output.writeFieldBegin("microarea", thrift.Thrift.Type.STRING, 23);
            output.writeString(this.microarea);
            output.writeFieldEnd();
        }
        if (this.stForaArea != null) {
            output.writeFieldBegin("stForaArea", thrift.Thrift.Type.BOOL, 24);
            output.writeBool(this.stForaArea);
            output.writeFieldEnd();
        }
        if (this.cpfCidadao != null) {
            output.writeFieldBegin("cpfCidadao", thrift.Thrift.Type.STRING, 25);
            output.writeString(this.cpfCidadao);
            output.writeFieldEnd();
        }
        if (this.cpfResponsavelFamiliar != null) {
            output.writeFieldBegin("cpfResponsavelFamiliar", thrift.Thrift.Type.STRING, 26);
            output.writeString(this.cpfResponsavelFamiliar);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): IdentificacaoUsuarioCidadaoThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.nomeSocial = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.codigoIbgeMunicipioNascimento = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.dataNascimentoCidadao = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_4: boolean = input.readBool();
                        _args.desconheceNomeMae = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.emailCidadao = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.nacionalidadeCidadao = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: string = input.readString();
                        _args.nomeCidadao = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_8: string = input.readString();
                        _args.nomeMaeCidadao = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_9: string = input.readString();
                        _args.cnsCidadao = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_10: string = input.readString();
                        _args.cnsResponsavelFamiliar = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_11: string = input.readString();
                        _args.telefoneCelular = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_12: string = input.readString();
                        _args.numeroNisPisPasep = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_13: Int64 = input.readI64();
                        _args.paisNascimento = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_14: Int64 = input.readI64();
                        _args.racaCorCidadao = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_15: Int64 = input.readI64();
                        _args.sexoCidadao = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_16: boolean = input.readBool();
                        _args.statusEhResponsavel = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_17: Int64 = input.readI64();
                        _args.etnia = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_18: string = input.readString();
                        _args.nomePaiCidadao = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 19:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_19: boolean = input.readBool();
                        _args.desconheceNomePai = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 20:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_20: Int64 = input.readI64();
                        _args.dtNaturalizacao = value_20;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 21:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_21: string = input.readString();
                        _args.portariaNaturalizacao = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 22:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_22: Int64 = input.readI64();
                        _args.dtEntradaBrasil = value_22;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 23:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_23: string = input.readString();
                        _args.microarea = value_23;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 24:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_24: boolean = input.readBool();
                        _args.stForaArea = value_24;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 25:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_25: string = input.readString();
                        _args.cpfCidadao = value_25;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 26:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_26: string = input.readString();
                        _args.cpfResponsavelFamiliar = value_26;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.nomeCidadao !== undefined) {
            return new IdentificacaoUsuarioCidadaoThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read IdentificacaoUsuarioCidadaoThrift from input");
        }
    }
}
