/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IInformacoesSocioDemograficasThriftArgs {
    deficienciasCidadao?: Array<number>;
    grauInstrucaoCidadao?: number | Int64;
    ocupacaoCodigoCbo2002?: string;
    orientacaoSexualCidadao?: Array<string>;
    relacaoParentescoCidadao?: number | Int64;
    situacaoMercadoTrabalhoCidadao?: number | Int64;
    statusDesejaInformarOrientacaoSexual?: boolean;
    statusFrequentaBenzedeira?: boolean;
    statusFrequentaEscola?: boolean;
    statusMembroPovoComunidadeTradicional?: boolean;
    statusParticipaGrupoComunitario?: boolean;
    statusPossuiPlanoSaudePrivado?: boolean;
    statusTemAlgumaDeficiencia?: boolean;
    identidadeGeneroCidadao?: Array<string>;
    statusDesejaInformarIdentidadeGenero?: boolean;
    responsavelPorCrianca?: number | Int64;
    coPovoComunidadeTradicional?: number | Int64;
}
export class InformacoesSocioDemograficasThrift {
    public deficienciasCidadao?: Array<number>;
    public grauInstrucaoCidadao?: Int64;
    public ocupacaoCodigoCbo2002?: string;
    public orientacaoSexualCidadao?: Array<string>;
    public relacaoParentescoCidadao?: Int64;
    public situacaoMercadoTrabalhoCidadao?: Int64;
    public statusDesejaInformarOrientacaoSexual?: boolean;
    public statusFrequentaBenzedeira?: boolean;
    public statusFrequentaEscola?: boolean;
    public statusMembroPovoComunidadeTradicional?: boolean;
    public statusParticipaGrupoComunitario?: boolean;
    public statusPossuiPlanoSaudePrivado?: boolean;
    public statusTemAlgumaDeficiencia?: boolean;
    public identidadeGeneroCidadao?: Array<string>;
    public statusDesejaInformarIdentidadeGenero?: boolean;
    public responsavelPorCrianca?: Int64;
    public coPovoComunidadeTradicional?: Int64;
    constructor(args?: IInformacoesSocioDemograficasThriftArgs) {
        if (args != null && args.deficienciasCidadao != null) {
            this.deficienciasCidadao = args.deficienciasCidadao;
        }
        if (args != null && args.grauInstrucaoCidadao != null) {
            if (typeof args.grauInstrucaoCidadao === "number") {
                this.grauInstrucaoCidadao = new Int64(args.grauInstrucaoCidadao);
            }
            else {
                this.grauInstrucaoCidadao = args.grauInstrucaoCidadao;
            }
        }
        if (args != null && args.ocupacaoCodigoCbo2002 != null) {
            this.ocupacaoCodigoCbo2002 = args.ocupacaoCodigoCbo2002;
        }
        if (args != null && args.orientacaoSexualCidadao != null) {
            this.orientacaoSexualCidadao = args.orientacaoSexualCidadao;
        }
        if (args != null && args.relacaoParentescoCidadao != null) {
            if (typeof args.relacaoParentescoCidadao === "number") {
                this.relacaoParentescoCidadao = new Int64(args.relacaoParentescoCidadao);
            }
            else {
                this.relacaoParentescoCidadao = args.relacaoParentescoCidadao;
            }
        }
        if (args != null && args.situacaoMercadoTrabalhoCidadao != null) {
            if (typeof args.situacaoMercadoTrabalhoCidadao === "number") {
                this.situacaoMercadoTrabalhoCidadao = new Int64(args.situacaoMercadoTrabalhoCidadao);
            }
            else {
                this.situacaoMercadoTrabalhoCidadao = args.situacaoMercadoTrabalhoCidadao;
            }
        }
        if (args != null && args.statusDesejaInformarOrientacaoSexual != null) {
            this.statusDesejaInformarOrientacaoSexual = args.statusDesejaInformarOrientacaoSexual;
        }
        if (args != null && args.statusFrequentaBenzedeira != null) {
            this.statusFrequentaBenzedeira = args.statusFrequentaBenzedeira;
        }
        if (args != null && args.statusFrequentaEscola != null) {
            this.statusFrequentaEscola = args.statusFrequentaEscola;
        }
        if (args != null && args.statusMembroPovoComunidadeTradicional != null) {
            this.statusMembroPovoComunidadeTradicional = args.statusMembroPovoComunidadeTradicional;
        }
        if (args != null && args.statusParticipaGrupoComunitario != null) {
            this.statusParticipaGrupoComunitario = args.statusParticipaGrupoComunitario;
        }
        if (args != null && args.statusPossuiPlanoSaudePrivado != null) {
            this.statusPossuiPlanoSaudePrivado = args.statusPossuiPlanoSaudePrivado;
        }
        if (args != null && args.statusTemAlgumaDeficiencia != null) {
            this.statusTemAlgumaDeficiencia = args.statusTemAlgumaDeficiencia;
        }
        if (args != null && args.identidadeGeneroCidadao != null) {
            this.identidadeGeneroCidadao = args.identidadeGeneroCidadao;
        }
        if (args != null && args.statusDesejaInformarIdentidadeGenero != null) {
            this.statusDesejaInformarIdentidadeGenero = args.statusDesejaInformarIdentidadeGenero;
        }
        if (args != null && args.responsavelPorCrianca != null) {
            if (typeof args.responsavelPorCrianca === "number") {
                this.responsavelPorCrianca = new Int64(args.responsavelPorCrianca);
            }
            else {
                this.responsavelPorCrianca = args.responsavelPorCrianca;
            }
        }
        if (args != null && args.coPovoComunidadeTradicional != null) {
            if (typeof args.coPovoComunidadeTradicional === "number") {
                this.coPovoComunidadeTradicional = new Int64(args.coPovoComunidadeTradicional);
            }
            else {
                this.coPovoComunidadeTradicional = args.coPovoComunidadeTradicional;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("InformacoesSocioDemograficasThrift");
        if (this.deficienciasCidadao != null) {
            output.writeFieldBegin("deficienciasCidadao", thrift.Thrift.Type.LIST, 1);
            output.writeListBegin(thrift.Thrift.Type.I32, this.deficienciasCidadao.length);
            this.deficienciasCidadao.forEach((value_1: number): void => {
                output.writeI32(value_1);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.grauInstrucaoCidadao != null) {
            output.writeFieldBegin("grauInstrucaoCidadao", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.grauInstrucaoCidadao);
            output.writeFieldEnd();
        }
        if (this.ocupacaoCodigoCbo2002 != null) {
            output.writeFieldBegin("ocupacaoCodigoCbo2002", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.ocupacaoCodigoCbo2002);
            output.writeFieldEnd();
        }
        if (this.orientacaoSexualCidadao != null) {
            output.writeFieldBegin("orientacaoSexualCidadao", thrift.Thrift.Type.LIST, 4);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.orientacaoSexualCidadao.length);
            this.orientacaoSexualCidadao.forEach((value_2: string): void => {
                output.writeString(value_2);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.relacaoParentescoCidadao != null) {
            output.writeFieldBegin("relacaoParentescoCidadao", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.relacaoParentescoCidadao);
            output.writeFieldEnd();
        }
        if (this.situacaoMercadoTrabalhoCidadao != null) {
            output.writeFieldBegin("situacaoMercadoTrabalhoCidadao", thrift.Thrift.Type.I64, 7);
            output.writeI64(this.situacaoMercadoTrabalhoCidadao);
            output.writeFieldEnd();
        }
        if (this.statusDesejaInformarOrientacaoSexual != null) {
            output.writeFieldBegin("statusDesejaInformarOrientacaoSexual", thrift.Thrift.Type.BOOL, 8);
            output.writeBool(this.statusDesejaInformarOrientacaoSexual);
            output.writeFieldEnd();
        }
        if (this.statusFrequentaBenzedeira != null) {
            output.writeFieldBegin("statusFrequentaBenzedeira", thrift.Thrift.Type.BOOL, 9);
            output.writeBool(this.statusFrequentaBenzedeira);
            output.writeFieldEnd();
        }
        if (this.statusFrequentaEscola != null) {
            output.writeFieldBegin("statusFrequentaEscola", thrift.Thrift.Type.BOOL, 10);
            output.writeBool(this.statusFrequentaEscola);
            output.writeFieldEnd();
        }
        if (this.statusMembroPovoComunidadeTradicional != null) {
            output.writeFieldBegin("statusMembroPovoComunidadeTradicional", thrift.Thrift.Type.BOOL, 11);
            output.writeBool(this.statusMembroPovoComunidadeTradicional);
            output.writeFieldEnd();
        }
        if (this.statusParticipaGrupoComunitario != null) {
            output.writeFieldBegin("statusParticipaGrupoComunitario", thrift.Thrift.Type.BOOL, 12);
            output.writeBool(this.statusParticipaGrupoComunitario);
            output.writeFieldEnd();
        }
        if (this.statusPossuiPlanoSaudePrivado != null) {
            output.writeFieldBegin("statusPossuiPlanoSaudePrivado", thrift.Thrift.Type.BOOL, 13);
            output.writeBool(this.statusPossuiPlanoSaudePrivado);
            output.writeFieldEnd();
        }
        if (this.statusTemAlgumaDeficiencia != null) {
            output.writeFieldBegin("statusTemAlgumaDeficiencia", thrift.Thrift.Type.BOOL, 14);
            output.writeBool(this.statusTemAlgumaDeficiencia);
            output.writeFieldEnd();
        }
        if (this.identidadeGeneroCidadao != null) {
            output.writeFieldBegin("identidadeGeneroCidadao", thrift.Thrift.Type.LIST, 15);
            output.writeListBegin(thrift.Thrift.Type.STRING, this.identidadeGeneroCidadao.length);
            this.identidadeGeneroCidadao.forEach((value_3: string): void => {
                output.writeString(value_3);
            });
            output.writeListEnd();
            output.writeFieldEnd();
        }
        if (this.statusDesejaInformarIdentidadeGenero != null) {
            output.writeFieldBegin("statusDesejaInformarIdentidadeGenero", thrift.Thrift.Type.BOOL, 16);
            output.writeBool(this.statusDesejaInformarIdentidadeGenero);
            output.writeFieldEnd();
        }
        if (this.responsavelPorCrianca != null) {
            output.writeFieldBegin("responsavelPorCrianca", thrift.Thrift.Type.I64, 17);
            output.writeI64(this.responsavelPorCrianca);
            output.writeFieldEnd();
        }
        if (this.coPovoComunidadeTradicional != null) {
            output.writeFieldBegin("coPovoComunidadeTradicional", thrift.Thrift.Type.I64, 18);
            output.writeI64(this.coPovoComunidadeTradicional);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): InformacoesSocioDemograficasThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_4: Array<number> = new Array<number>();
                        const metadata_1: thrift.TList = input.readListBegin();
                        const size_1: number = metadata_1.size;
                        for (let i_1: number = 0; i_1 < size_1; i_1++) {
                            const value_5: number = input.readI32();
                            value_4.push(value_5);
                        }
                        input.readListEnd();
                        _args.deficienciasCidadao = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.grauInstrucaoCidadao = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_7: string = input.readString();
                        _args.ocupacaoCodigoCbo2002 = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_8: Array<string> = new Array<string>();
                        const metadata_2: thrift.TList = input.readListBegin();
                        const size_2: number = metadata_2.size;
                        for (let i_2: number = 0; i_2 < size_2; i_2++) {
                            const value_9: string = input.readString();
                            value_8.push(value_9);
                        }
                        input.readListEnd();
                        _args.orientacaoSexualCidadao = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_10: Int64 = input.readI64();
                        _args.relacaoParentescoCidadao = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_11: Int64 = input.readI64();
                        _args.situacaoMercadoTrabalhoCidadao = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_12: boolean = input.readBool();
                        _args.statusDesejaInformarOrientacaoSexual = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_13: boolean = input.readBool();
                        _args.statusFrequentaBenzedeira = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_14: boolean = input.readBool();
                        _args.statusFrequentaEscola = value_14;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_15: boolean = input.readBool();
                        _args.statusMembroPovoComunidadeTradicional = value_15;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_16: boolean = input.readBool();
                        _args.statusParticipaGrupoComunitario = value_16;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_17: boolean = input.readBool();
                        _args.statusPossuiPlanoSaudePrivado = value_17;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 14:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_18: boolean = input.readBool();
                        _args.statusTemAlgumaDeficiencia = value_18;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 15:
                    if (fieldType === thrift.Thrift.Type.LIST) {
                        const value_19: Array<string> = new Array<string>();
                        const metadata_3: thrift.TList = input.readListBegin();
                        const size_3: number = metadata_3.size;
                        for (let i_3: number = 0; i_3 < size_3; i_3++) {
                            const value_20: string = input.readString();
                            value_19.push(value_20);
                        }
                        input.readListEnd();
                        _args.identidadeGeneroCidadao = value_19;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 16:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_21: boolean = input.readBool();
                        _args.statusDesejaInformarIdentidadeGenero = value_21;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 17:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_22: Int64 = input.readI64();
                        _args.responsavelPorCrianca = value_22;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 18:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_23: Int64 = input.readI64();
                        _args.coPovoComunidadeTradicional = value_23;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new InformacoesSocioDemograficasThrift(_args);
    }
}
