/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IInstituicaoPermanenciaThriftArgs {
    nomeInstituicaoPermanencia?: string;
    stOutrosProfissionaisVinculados?: boolean;
    nomeResponsavelTecnico?: string;
    cnsResponsavelTecnico?: string;
    cargoInstituicao?: string;
    telefoneResponsavelTecnico?: string;
}
export class InstituicaoPermanenciaThrift {
    public nomeInstituicaoPermanencia?: string;
    public stOutrosProfissionaisVinculados?: boolean;
    public nomeResponsavelTecnico?: string;
    public cnsResponsavelTecnico?: string;
    public cargoInstituicao?: string;
    public telefoneResponsavelTecnico?: string;
    constructor(args?: IInstituicaoPermanenciaThriftArgs) {
        if (args != null && args.nomeInstituicaoPermanencia != null) {
            this.nomeInstituicaoPermanencia = args.nomeInstituicaoPermanencia;
        }
        if (args != null && args.stOutrosProfissionaisVinculados != null) {
            this.stOutrosProfissionaisVinculados = args.stOutrosProfissionaisVinculados;
        }
        if (args != null && args.nomeResponsavelTecnico != null) {
            this.nomeResponsavelTecnico = args.nomeResponsavelTecnico;
        }
        if (args != null && args.cnsResponsavelTecnico != null) {
            this.cnsResponsavelTecnico = args.cnsResponsavelTecnico;
        }
        if (args != null && args.cargoInstituicao != null) {
            this.cargoInstituicao = args.cargoInstituicao;
        }
        if (args != null && args.telefoneResponsavelTecnico != null) {
            this.telefoneResponsavelTecnico = args.telefoneResponsavelTecnico;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("InstituicaoPermanenciaThrift");
        if (this.nomeInstituicaoPermanencia != null) {
            output.writeFieldBegin("nomeInstituicaoPermanencia", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.nomeInstituicaoPermanencia);
            output.writeFieldEnd();
        }
        if (this.stOutrosProfissionaisVinculados != null) {
            output.writeFieldBegin("stOutrosProfissionaisVinculados", thrift.Thrift.Type.BOOL, 2);
            output.writeBool(this.stOutrosProfissionaisVinculados);
            output.writeFieldEnd();
        }
        if (this.nomeResponsavelTecnico != null) {
            output.writeFieldBegin("nomeResponsavelTecnico", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.nomeResponsavelTecnico);
            output.writeFieldEnd();
        }
        if (this.cnsResponsavelTecnico != null) {
            output.writeFieldBegin("cnsResponsavelTecnico", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.cnsResponsavelTecnico);
            output.writeFieldEnd();
        }
        if (this.cargoInstituicao != null) {
            output.writeFieldBegin("cargoInstituicao", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.cargoInstituicao);
            output.writeFieldEnd();
        }
        if (this.telefoneResponsavelTecnico != null) {
            output.writeFieldBegin("telefoneResponsavelTecnico", thrift.Thrift.Type.STRING, 6);
            output.writeString(this.telefoneResponsavelTecnico);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): InstituicaoPermanenciaThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.nomeInstituicaoPermanencia = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_2: boolean = input.readBool();
                        _args.stOutrosProfissionaisVinculados = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.nomeResponsavelTecnico = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.cnsResponsavelTecnico = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.cargoInstituicao = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_6: string = input.readString();
                        _args.telefoneResponsavelTecnico = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new InstituicaoPermanenciaThrift(_args);
    }
}
