/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface ILediOriginadoraThriftArgs {
    contraChave: string;
    cpfCnpj: string;
}
export class LediOriginadoraThrift {
    public contraChave: string;
    public cpfCnpj: string;
    constructor(args: ILediOriginadoraThriftArgs) {
        if (args != null && args.contraChave != null) {
            this.contraChave = args.contraChave;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[contraChave] is unset!");
        }
        if (args != null && args.cpfCnpj != null) {
            this.cpfCnpj = args.cpfCnpj;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cpfCnpj] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("LediOriginadoraThrift");
        if (this.contraChave != null) {
            output.writeFieldBegin("contraChave", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.contraChave);
            output.writeFieldEnd();
        }
        if (this.cpfCnpj != null) {
            output.writeFieldBegin("cpfCnpj", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.cpfCnpj);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): LediOriginadoraThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.contraChave = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.cpfCnpj = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.contraChave !== undefined && _args.cpfCnpj !== undefined) {
            return new LediOriginadoraThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read LediOriginadoraThrift from input");
        }
    }
}
