/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ILotacaoHeaderThriftArgs {
    profissionalCNS: string;
    cboCodigo_2002: string;
    cnes: string;
    codigoIbgeMunicipio: string;
    ine?: string;
    dataAtendimento?: number | Int64;
}
export class LotacaoHeaderThrift {
    public profissionalCNS: string;
    public cboCodigo_2002: string;
    public cnes: string;
    public codigoIbgeMunicipio: string;
    public ine?: string;
    public dataAtendimento?: Int64;
    constructor(args: ILotacaoHeaderThriftArgs) {
        if (args != null && args.profissionalCNS != null) {
            this.profissionalCNS = args.profissionalCNS;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[profissionalCNS] is unset!");
        }
        if (args != null && args.cboCodigo_2002 != null) {
            this.cboCodigo_2002 = args.cboCodigo_2002;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cboCodigo_2002] is unset!");
        }
        if (args != null && args.cnes != null) {
            this.cnes = args.cnes;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cnes] is unset!");
        }
        if (args != null && args.codigoIbgeMunicipio != null) {
            this.codigoIbgeMunicipio = args.codigoIbgeMunicipio;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[codigoIbgeMunicipio] is unset!");
        }
        if (args != null && args.ine != null) {
            this.ine = args.ine;
        }
        if (args != null && args.dataAtendimento != null) {
            if (typeof args.dataAtendimento === "number") {
                this.dataAtendimento = new Int64(args.dataAtendimento);
            }
            else {
                this.dataAtendimento = args.dataAtendimento;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("LotacaoHeaderThrift");
        if (this.profissionalCNS != null) {
            output.writeFieldBegin("profissionalCNS", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.profissionalCNS);
            output.writeFieldEnd();
        }
        if (this.cboCodigo_2002 != null) {
            output.writeFieldBegin("cboCodigo_2002", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.cboCodigo_2002);
            output.writeFieldEnd();
        }
        if (this.cnes != null) {
            output.writeFieldBegin("cnes", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.cnes);
            output.writeFieldEnd();
        }
        if (this.codigoIbgeMunicipio != null) {
            output.writeFieldBegin("codigoIbgeMunicipio", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.codigoIbgeMunicipio);
            output.writeFieldEnd();
        }
        if (this.ine != null) {
            output.writeFieldBegin("ine", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.ine);
            output.writeFieldEnd();
        }
        if (this.dataAtendimento != null) {
            output.writeFieldBegin("dataAtendimento", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.dataAtendimento);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): LotacaoHeaderThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.profissionalCNS = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.cboCodigo_2002 = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.cnes = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.codigoIbgeMunicipio = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.ine = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.dataAtendimento = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.profissionalCNS !== undefined && _args.cboCodigo_2002 !== undefined && _args.cnes !== undefined && _args.codigoIbgeMunicipio !== undefined) {
            return new LotacaoHeaderThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read LotacaoHeaderThrift from input");
        }
    }
}
