/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IMedicoesThriftArgs {
    circunferenciaAbdominal?: number;
    perimetroPanturrilha?: number;
    pressaoArterialSistolica?: number;
    pressaoArterialDiastolica?: number;
    frequenciaRespiratoria?: number;
    frequenciaCardiaca?: number;
    temperatura?: number;
    saturacaoO2?: number;
    glicemiaCapilar?: number;
    tipoGlicemiaCapilar?: number | Int64;
    peso?: number;
    altura?: number;
    perimetroCefalico?: number;
}
export class MedicoesThrift {
    public circunferenciaAbdominal?: number;
    public perimetroPanturrilha?: number;
    public pressaoArterialSistolica?: number;
    public pressaoArterialDiastolica?: number;
    public frequenciaRespiratoria?: number;
    public frequenciaCardiaca?: number;
    public temperatura?: number;
    public saturacaoO2?: number;
    public glicemiaCapilar?: number;
    public tipoGlicemiaCapilar?: Int64;
    public peso?: number;
    public altura?: number;
    public perimetroCefalico?: number;
    constructor(args?: IMedicoesThriftArgs) {
        if (args != null && args.circunferenciaAbdominal != null) {
            this.circunferenciaAbdominal = args.circunferenciaAbdominal;
        }
        if (args != null && args.perimetroPanturrilha != null) {
            this.perimetroPanturrilha = args.perimetroPanturrilha;
        }
        if (args != null && args.pressaoArterialSistolica != null) {
            this.pressaoArterialSistolica = args.pressaoArterialSistolica;
        }
        if (args != null && args.pressaoArterialDiastolica != null) {
            this.pressaoArterialDiastolica = args.pressaoArterialDiastolica;
        }
        if (args != null && args.frequenciaRespiratoria != null) {
            this.frequenciaRespiratoria = args.frequenciaRespiratoria;
        }
        if (args != null && args.frequenciaCardiaca != null) {
            this.frequenciaCardiaca = args.frequenciaCardiaca;
        }
        if (args != null && args.temperatura != null) {
            this.temperatura = args.temperatura;
        }
        if (args != null && args.saturacaoO2 != null) {
            this.saturacaoO2 = args.saturacaoO2;
        }
        if (args != null && args.glicemiaCapilar != null) {
            this.glicemiaCapilar = args.glicemiaCapilar;
        }
        if (args != null && args.tipoGlicemiaCapilar != null) {
            if (typeof args.tipoGlicemiaCapilar === "number") {
                this.tipoGlicemiaCapilar = new Int64(args.tipoGlicemiaCapilar);
            }
            else {
                this.tipoGlicemiaCapilar = args.tipoGlicemiaCapilar;
            }
        }
        if (args != null && args.peso != null) {
            this.peso = args.peso;
        }
        if (args != null && args.altura != null) {
            this.altura = args.altura;
        }
        if (args != null && args.perimetroCefalico != null) {
            this.perimetroCefalico = args.perimetroCefalico;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("MedicoesThrift");
        if (this.circunferenciaAbdominal != null) {
            output.writeFieldBegin("circunferenciaAbdominal", thrift.Thrift.Type.DOUBLE, 1);
            output.writeDouble(this.circunferenciaAbdominal);
            output.writeFieldEnd();
        }
        if (this.perimetroPanturrilha != null) {
            output.writeFieldBegin("perimetroPanturrilha", thrift.Thrift.Type.DOUBLE, 2);
            output.writeDouble(this.perimetroPanturrilha);
            output.writeFieldEnd();
        }
        if (this.pressaoArterialSistolica != null) {
            output.writeFieldBegin("pressaoArterialSistolica", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.pressaoArterialSistolica);
            output.writeFieldEnd();
        }
        if (this.pressaoArterialDiastolica != null) {
            output.writeFieldBegin("pressaoArterialDiastolica", thrift.Thrift.Type.I32, 4);
            output.writeI32(this.pressaoArterialDiastolica);
            output.writeFieldEnd();
        }
        if (this.frequenciaRespiratoria != null) {
            output.writeFieldBegin("frequenciaRespiratoria", thrift.Thrift.Type.I32, 5);
            output.writeI32(this.frequenciaRespiratoria);
            output.writeFieldEnd();
        }
        if (this.frequenciaCardiaca != null) {
            output.writeFieldBegin("frequenciaCardiaca", thrift.Thrift.Type.I32, 6);
            output.writeI32(this.frequenciaCardiaca);
            output.writeFieldEnd();
        }
        if (this.temperatura != null) {
            output.writeFieldBegin("temperatura", thrift.Thrift.Type.DOUBLE, 7);
            output.writeDouble(this.temperatura);
            output.writeFieldEnd();
        }
        if (this.saturacaoO2 != null) {
            output.writeFieldBegin("saturacaoO2", thrift.Thrift.Type.I32, 8);
            output.writeI32(this.saturacaoO2);
            output.writeFieldEnd();
        }
        if (this.glicemiaCapilar != null) {
            output.writeFieldBegin("glicemiaCapilar", thrift.Thrift.Type.I32, 9);
            output.writeI32(this.glicemiaCapilar);
            output.writeFieldEnd();
        }
        if (this.tipoGlicemiaCapilar != null) {
            output.writeFieldBegin("tipoGlicemiaCapilar", thrift.Thrift.Type.I64, 10);
            output.writeI64(this.tipoGlicemiaCapilar);
            output.writeFieldEnd();
        }
        if (this.peso != null) {
            output.writeFieldBegin("peso", thrift.Thrift.Type.DOUBLE, 11);
            output.writeDouble(this.peso);
            output.writeFieldEnd();
        }
        if (this.altura != null) {
            output.writeFieldBegin("altura", thrift.Thrift.Type.DOUBLE, 12);
            output.writeDouble(this.altura);
            output.writeFieldEnd();
        }
        if (this.perimetroCefalico != null) {
            output.writeFieldBegin("perimetroCefalico", thrift.Thrift.Type.DOUBLE, 13);
            output.writeDouble(this.perimetroCefalico);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): MedicoesThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_1: number = input.readDouble();
                        _args.circunferenciaAbdominal = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_2: number = input.readDouble();
                        _args.perimetroPanturrilha = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.pressaoArterialSistolica = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_4: number = input.readI32();
                        _args.pressaoArterialDiastolica = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_5: number = input.readI32();
                        _args.frequenciaRespiratoria = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_6: number = input.readI32();
                        _args.frequenciaCardiaca = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_7: number = input.readDouble();
                        _args.temperatura = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_8: number = input.readI32();
                        _args.saturacaoO2 = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_9: number = input.readI32();
                        _args.glicemiaCapilar = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_10: Int64 = input.readI64();
                        _args.tipoGlicemiaCapilar = value_10;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_11: number = input.readDouble();
                        _args.peso = value_11;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_12: number = input.readDouble();
                        _args.altura = value_12;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_13: number = input.readDouble();
                        _args.perimetroCefalico = value_13;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new MedicoesThrift(_args);
    }
}
