/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IParticipanteRowThriftArgs {
    cnsParticipante?: string;
    dataNascimento?: number | Int64;
    sexo?: number | Int64;
    avaliacaoAlterada?: boolean;
    peso?: number;
    altura?: number;
    cessouHabitoFumar?: boolean;
    abandonouGrupo?: boolean;
}
export class ParticipanteRowThrift {
    public cnsParticipante?: string;
    public dataNascimento?: Int64;
    public sexo?: Int64;
    public avaliacaoAlterada?: boolean;
    public peso?: number;
    public altura?: number;
    public cessouHabitoFumar?: boolean;
    public abandonouGrupo?: boolean;
    constructor(args?: IParticipanteRowThriftArgs) {
        if (args != null && args.cnsParticipante != null) {
            this.cnsParticipante = args.cnsParticipante;
        }
        if (args != null && args.dataNascimento != null) {
            if (typeof args.dataNascimento === "number") {
                this.dataNascimento = new Int64(args.dataNascimento);
            }
            else {
                this.dataNascimento = args.dataNascimento;
            }
        }
        if (args != null && args.sexo != null) {
            if (typeof args.sexo === "number") {
                this.sexo = new Int64(args.sexo);
            }
            else {
                this.sexo = args.sexo;
            }
        }
        if (args != null && args.avaliacaoAlterada != null) {
            this.avaliacaoAlterada = args.avaliacaoAlterada;
        }
        if (args != null && args.peso != null) {
            this.peso = args.peso;
        }
        if (args != null && args.altura != null) {
            this.altura = args.altura;
        }
        if (args != null && args.cessouHabitoFumar != null) {
            this.cessouHabitoFumar = args.cessouHabitoFumar;
        }
        if (args != null && args.abandonouGrupo != null) {
            this.abandonouGrupo = args.abandonouGrupo;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ParticipanteRowThrift");
        if (this.cnsParticipante != null) {
            output.writeFieldBegin("cnsParticipante", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.cnsParticipante);
            output.writeFieldEnd();
        }
        if (this.dataNascimento != null) {
            output.writeFieldBegin("dataNascimento", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.dataNascimento);
            output.writeFieldEnd();
        }
        if (this.sexo != null) {
            output.writeFieldBegin("sexo", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.sexo);
            output.writeFieldEnd();
        }
        if (this.avaliacaoAlterada != null) {
            output.writeFieldBegin("avaliacaoAlterada", thrift.Thrift.Type.BOOL, 4);
            output.writeBool(this.avaliacaoAlterada);
            output.writeFieldEnd();
        }
        if (this.peso != null) {
            output.writeFieldBegin("peso", thrift.Thrift.Type.DOUBLE, 5);
            output.writeDouble(this.peso);
            output.writeFieldEnd();
        }
        if (this.altura != null) {
            output.writeFieldBegin("altura", thrift.Thrift.Type.DOUBLE, 6);
            output.writeDouble(this.altura);
            output.writeFieldEnd();
        }
        if (this.cessouHabitoFumar != null) {
            output.writeFieldBegin("cessouHabitoFumar", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.cessouHabitoFumar);
            output.writeFieldEnd();
        }
        if (this.abandonouGrupo != null) {
            output.writeFieldBegin("abandonouGrupo", thrift.Thrift.Type.BOOL, 8);
            output.writeBool(this.abandonouGrupo);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ParticipanteRowThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.cnsParticipante = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.dataNascimento = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.sexo = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_4: boolean = input.readBool();
                        _args.avaliacaoAlterada = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_5: number = input.readDouble();
                        _args.peso = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.DOUBLE) {
                        const value_6: number = input.readDouble();
                        _args.altura = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_7: boolean = input.readBool();
                        _args.cessouHabitoFumar = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_8: boolean = input.readBool();
                        _args.abandonouGrupo = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ParticipanteRowThrift(_args);
    }
}
