/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import Int64 = require("node-int64");

export interface IProblemaCondicaoThriftArgs {
    uuidProblema?: string;
    uuidEvolucaoProblema?: string;
    coSequencialEvolucao?: number | Int64;
    ciap?: string;
    cid10?: string;
    situacao?: string;
    dataInicioProblema?: number | Int64;
    dataFimProblema?: number | Int64;
    isAvaliado?: boolean;
}
export class ProblemaCondicaoThrift {
    public uuidProblema?: string;
    public uuidEvolucaoProblema?: string;
    public coSequencialEvolucao?: Int64;
    public ciap?: string;
    public cid10?: string;
    public situacao?: string;
    public dataInicioProblema?: Int64;
    public dataFimProblema?: Int64;
    public isAvaliado?: boolean;
    constructor(args?: IProblemaCondicaoThriftArgs) {
        if (args != null && args.uuidProblema != null) {
            this.uuidProblema = args.uuidProblema;
        }
        if (args != null && args.uuidEvolucaoProblema != null) {
            this.uuidEvolucaoProblema = args.uuidEvolucaoProblema;
        }
        if (args != null && args.coSequencialEvolucao != null) {
            if (typeof args.coSequencialEvolucao === "number") {
                this.coSequencialEvolucao = new Int64(args.coSequencialEvolucao);
            }
            else {
                this.coSequencialEvolucao = args.coSequencialEvolucao;
            }
        }
        if (args != null && args.ciap != null) {
            this.ciap = args.ciap;
        }
        if (args != null && args.cid10 != null) {
            this.cid10 = args.cid10;
        }
        if (args != null && args.situacao != null) {
            this.situacao = args.situacao;
        }
        if (args != null && args.dataInicioProblema != null) {
            if (typeof args.dataInicioProblema === "number") {
                this.dataInicioProblema = new Int64(args.dataInicioProblema);
            }
            else {
                this.dataInicioProblema = args.dataInicioProblema;
            }
        }
        if (args != null && args.dataFimProblema != null) {
            if (typeof args.dataFimProblema === "number") {
                this.dataFimProblema = new Int64(args.dataFimProblema);
            }
            else {
                this.dataFimProblema = args.dataFimProblema;
            }
        }
        if (args != null && args.isAvaliado != null) {
            this.isAvaliado = args.isAvaliado;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ProblemaCondicaoThrift");
        if (this.uuidProblema != null) {
            output.writeFieldBegin("uuidProblema", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.uuidProblema);
            output.writeFieldEnd();
        }
        if (this.uuidEvolucaoProblema != null) {
            output.writeFieldBegin("uuidEvolucaoProblema", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.uuidEvolucaoProblema);
            output.writeFieldEnd();
        }
        if (this.coSequencialEvolucao != null) {
            output.writeFieldBegin("coSequencialEvolucao", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.coSequencialEvolucao);
            output.writeFieldEnd();
        }
        if (this.ciap != null) {
            output.writeFieldBegin("ciap", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.ciap);
            output.writeFieldEnd();
        }
        if (this.cid10 != null) {
            output.writeFieldBegin("cid10", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.cid10);
            output.writeFieldEnd();
        }
        if (this.situacao != null) {
            output.writeFieldBegin("situacao", thrift.Thrift.Type.STRING, 6);
            output.writeString(this.situacao);
            output.writeFieldEnd();
        }
        if (this.dataInicioProblema != null) {
            output.writeFieldBegin("dataInicioProblema", thrift.Thrift.Type.I64, 7);
            output.writeI64(this.dataInicioProblema);
            output.writeFieldEnd();
        }
        if (this.dataFimProblema != null) {
            output.writeFieldBegin("dataFimProblema", thrift.Thrift.Type.I64, 8);
            output.writeI64(this.dataFimProblema);
            output.writeFieldEnd();
        }
        if (this.isAvaliado != null) {
            output.writeFieldBegin("isAvaliado", thrift.Thrift.Type.BOOL, 9);
            output.writeBool(this.isAvaliado);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ProblemaCondicaoThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.uuidProblema = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.uuidEvolucaoProblema = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.coSequencialEvolucao = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.ciap = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.cid10 = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_6: string = input.readString();
                        _args.situacao = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_7: Int64 = input.readI64();
                        _args.dataInicioProblema = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_8: Int64 = input.readI64();
                        _args.dataFimProblema = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_9: boolean = input.readBool();
                        _args.isAvaliado = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ProblemaCondicaoThrift(_args);
    }
}
