/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IProcedimentoThriftArgs {
    coMsProcedimento?: string;
    quantidade?: number;
}
export class ProcedimentoThrift {
    public coMsProcedimento?: string;
    public quantidade?: number;
    constructor(args?: IProcedimentoThriftArgs) {
        if (args != null && args.coMsProcedimento != null) {
            this.coMsProcedimento = args.coMsProcedimento;
        }
        if (args != null && args.quantidade != null) {
            this.quantidade = args.quantidade;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ProcedimentoThrift");
        if (this.coMsProcedimento != null) {
            output.writeFieldBegin("coMsProcedimento", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.coMsProcedimento);
            output.writeFieldEnd();
        }
        if (this.quantidade != null) {
            output.writeFieldBegin("quantidade", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.quantidade);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ProcedimentoThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.coMsProcedimento = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.quantidade = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new ProcedimentoThrift(_args);
    }
}
