/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IProfissionalColetivaThriftArgs {
    cnsProfissional: string;
    cboCodigo_2002: string;
}
export class ProfissionalColetivaThrift {
    public cnsProfissional: string;
    public cboCodigo_2002: string;
    constructor(args: IProfissionalColetivaThriftArgs) {
        if (args != null && args.cnsProfissional != null) {
            this.cnsProfissional = args.cnsProfissional;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cnsProfissional] is unset!");
        }
        if (args != null && args.cboCodigo_2002 != null) {
            this.cboCodigo_2002 = args.cboCodigo_2002;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[cboCodigo_2002] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("ProfissionalColetivaThrift");
        if (this.cnsProfissional != null) {
            output.writeFieldBegin("cnsProfissional", thrift.Thrift.Type.STRING, 1);
            output.writeString(this.cnsProfissional);
            output.writeFieldEnd();
        }
        if (this.cboCodigo_2002 != null) {
            output.writeFieldBegin("cboCodigo_2002", thrift.Thrift.Type.STRING, 2);
            output.writeString(this.cboCodigo_2002);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): ProfissionalColetivaThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_1: string = input.readString();
                        _args.cnsProfissional = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_2: string = input.readString();
                        _args.cboCodigo_2002 = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.cnsProfissional !== undefined && _args.cboCodigo_2002 !== undefined) {
            return new ProfissionalColetivaThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read ProfissionalColetivaThrift from input");
        }
    }
}
