/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface ISaidaCidadaoCadastroThriftArgs {
    motivoSaidaCidadao?: number | Int64;
    dataObito?: number | Int64;
    numeroDO?: string;
}
export class SaidaCidadaoCadastroThrift {
    public motivoSaidaCidadao?: Int64;
    public dataObito?: Int64;
    public numeroDO?: string;
    constructor(args?: ISaidaCidadaoCadastroThriftArgs) {
        if (args != null && args.motivoSaidaCidadao != null) {
            if (typeof args.motivoSaidaCidadao === "number") {
                this.motivoSaidaCidadao = new Int64(args.motivoSaidaCidadao);
            }
            else {
                this.motivoSaidaCidadao = args.motivoSaidaCidadao;
            }
        }
        if (args != null && args.dataObito != null) {
            if (typeof args.dataObito === "number") {
                this.dataObito = new Int64(args.dataObito);
            }
            else {
                this.dataObito = args.dataObito;
            }
        }
        if (args != null && args.numeroDO != null) {
            this.numeroDO = args.numeroDO;
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("SaidaCidadaoCadastroThrift");
        if (this.motivoSaidaCidadao != null) {
            output.writeFieldBegin("motivoSaidaCidadao", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.motivoSaidaCidadao);
            output.writeFieldEnd();
        }
        if (this.dataObito != null) {
            output.writeFieldBegin("dataObito", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.dataObito);
            output.writeFieldEnd();
        }
        if (this.numeroDO != null) {
            output.writeFieldBegin("numeroDO", thrift.Thrift.Type.STRING, 3);
            output.writeString(this.numeroDO);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): SaidaCidadaoCadastroThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.motivoSaidaCidadao = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.dataObito = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_3: string = input.readString();
                        _args.numeroDO = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new SaidaCidadaoCadastroThrift(_args);
    }
}
