/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import Int64 = require("node-int64");
import * as thrift from "thrift";
export interface IVacinaRowThriftArgs {
    imunobiologico?: number | Int64;
    estrategiaVacinacao?: number | Int64;
    dose?: number | Int64;
    lote?: string;
    fabricante?: string;
    grupoAtendimento?: number | Int64;
    stRegistroAnterior?: boolean;
    dataRegistroAnterior?: number | Int64;
    stAplicadoExterior?: boolean;
    especialidadeProfissionalPrescritor?: string;
    motivoIndicacao?: string;
    viaAdministracao?: number | Int64;
    localAplicacao?: number | Int64;
}
export class VacinaRowThrift {
    public imunobiologico?: Int64;
    public estrategiaVacinacao?: Int64;
    public dose?: Int64;
    public lote?: string;
    public fabricante?: string;
    public grupoAtendimento?: Int64;
    public stRegistroAnterior?: boolean;
    public dataRegistroAnterior?: Int64;
    public stAplicadoExterior?: boolean;
    public especialidadeProfissionalPrescritor?: string;
    public motivoIndicacao?: string;
    public viaAdministracao?: Int64;
    public localAplicacao?: Int64;
    constructor(args?: IVacinaRowThriftArgs) {
        if (args != null && args.imunobiologico != null) {
            if (typeof args.imunobiologico === "number") {
                this.imunobiologico = new Int64(args.imunobiologico);
            }
            else {
                this.imunobiologico = args.imunobiologico;
            }
        }
        if (args != null && args.estrategiaVacinacao != null) {
            if (typeof args.estrategiaVacinacao === "number") {
                this.estrategiaVacinacao = new Int64(args.estrategiaVacinacao);
            }
            else {
                this.estrategiaVacinacao = args.estrategiaVacinacao;
            }
        }
        if (args != null && args.dose != null) {
            if (typeof args.dose === "number") {
                this.dose = new Int64(args.dose);
            }
            else {
                this.dose = args.dose;
            }
        }
        if (args != null && args.lote != null) {
            this.lote = args.lote;
        }
        if (args != null && args.fabricante != null) {
            this.fabricante = args.fabricante;
        }
        if (args != null && args.grupoAtendimento != null) {
            if (typeof args.grupoAtendimento === "number") {
                this.grupoAtendimento = new Int64(args.grupoAtendimento);
            }
            else {
                this.grupoAtendimento = args.grupoAtendimento;
            }
        }
        if (args != null && args.stRegistroAnterior != null) {
            this.stRegistroAnterior = args.stRegistroAnterior;
        }
        if (args != null && args.dataRegistroAnterior != null) {
            if (typeof args.dataRegistroAnterior === "number") {
                this.dataRegistroAnterior = new Int64(args.dataRegistroAnterior);
            }
            else {
                this.dataRegistroAnterior = args.dataRegistroAnterior;
            }
        }
        if (args != null && args.stAplicadoExterior != null) {
            this.stAplicadoExterior = args.stAplicadoExterior;
        }
        if (args != null && args.especialidadeProfissionalPrescritor != null) {
            this.especialidadeProfissionalPrescritor = args.especialidadeProfissionalPrescritor;
        }
        if (args != null && args.motivoIndicacao != null) {
            this.motivoIndicacao = args.motivoIndicacao;
        }
        if (args != null && args.viaAdministracao != null) {
            if (typeof args.viaAdministracao === "number") {
                this.viaAdministracao = new Int64(args.viaAdministracao);
            }
            else {
                this.viaAdministracao = args.viaAdministracao;
            }
        }
        if (args != null && args.localAplicacao != null) {
            if (typeof args.localAplicacao === "number") {
                this.localAplicacao = new Int64(args.localAplicacao);
            }
            else {
                this.localAplicacao = args.localAplicacao;
            }
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("VacinaRowThrift");
        if (this.imunobiologico != null) {
            output.writeFieldBegin("imunobiologico", thrift.Thrift.Type.I64, 1);
            output.writeI64(this.imunobiologico);
            output.writeFieldEnd();
        }
        if (this.estrategiaVacinacao != null) {
            output.writeFieldBegin("estrategiaVacinacao", thrift.Thrift.Type.I64, 2);
            output.writeI64(this.estrategiaVacinacao);
            output.writeFieldEnd();
        }
        if (this.dose != null) {
            output.writeFieldBegin("dose", thrift.Thrift.Type.I64, 3);
            output.writeI64(this.dose);
            output.writeFieldEnd();
        }
        if (this.lote != null) {
            output.writeFieldBegin("lote", thrift.Thrift.Type.STRING, 4);
            output.writeString(this.lote);
            output.writeFieldEnd();
        }
        if (this.fabricante != null) {
            output.writeFieldBegin("fabricante", thrift.Thrift.Type.STRING, 5);
            output.writeString(this.fabricante);
            output.writeFieldEnd();
        }
        if (this.grupoAtendimento != null) {
            output.writeFieldBegin("grupoAtendimento", thrift.Thrift.Type.I64, 6);
            output.writeI64(this.grupoAtendimento);
            output.writeFieldEnd();
        }
        if (this.stRegistroAnterior != null) {
            output.writeFieldBegin("stRegistroAnterior", thrift.Thrift.Type.BOOL, 7);
            output.writeBool(this.stRegistroAnterior);
            output.writeFieldEnd();
        }
        if (this.dataRegistroAnterior != null) {
            output.writeFieldBegin("dataRegistroAnterior", thrift.Thrift.Type.I64, 8);
            output.writeI64(this.dataRegistroAnterior);
            output.writeFieldEnd();
        }
        if (this.stAplicadoExterior != null) {
            output.writeFieldBegin("stAplicadoExterior", thrift.Thrift.Type.BOOL, 9);
            output.writeBool(this.stAplicadoExterior);
            output.writeFieldEnd();
        }
        if (this.especialidadeProfissionalPrescritor != null) {
            output.writeFieldBegin("especialidadeProfissionalPrescritor", thrift.Thrift.Type.STRING, 10);
            output.writeString(this.especialidadeProfissionalPrescritor);
            output.writeFieldEnd();
        }
        if (this.motivoIndicacao != null) {
            output.writeFieldBegin("motivoIndicacao", thrift.Thrift.Type.STRING, 11);
            output.writeString(this.motivoIndicacao);
            output.writeFieldEnd();
        }
        if (this.viaAdministracao != null) {
            output.writeFieldBegin("viaAdministracao", thrift.Thrift.Type.I64, 12);
            output.writeI64(this.viaAdministracao);
            output.writeFieldEnd();
        }
        if (this.localAplicacao != null) {
            output.writeFieldBegin("localAplicacao", thrift.Thrift.Type.I64, 13);
            output.writeI64(this.localAplicacao);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): VacinaRowThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_1: Int64 = input.readI64();
                        _args.imunobiologico = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_2: Int64 = input.readI64();
                        _args.estrategiaVacinacao = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_3: Int64 = input.readI64();
                        _args.dose = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 4:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_4: string = input.readString();
                        _args.lote = value_4;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 5:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_5: string = input.readString();
                        _args.fabricante = value_5;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 6:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_6: Int64 = input.readI64();
                        _args.grupoAtendimento = value_6;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 7:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_7: boolean = input.readBool();
                        _args.stRegistroAnterior = value_7;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 8:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_8: Int64 = input.readI64();
                        _args.dataRegistroAnterior = value_8;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 9:
                    if (fieldType === thrift.Thrift.Type.BOOL) {
                        const value_9: boolean = input.readBool();
                        _args.stAplicadoExterior = value_9;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 10:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_10: string = input.readString();
                        _args.especialidadeProfissionalPrescritor = value_10;
                    } else { input.skip(fieldType); }
                    break;
                case 11:
                    if (fieldType === thrift.Thrift.Type.STRING) {
                        const value_11: string = input.readString();
                        _args.motivoIndicacao = value_11;
                    } else { input.skip(fieldType); }
                    break;
                case 12:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_12: Int64 = input.readI64();
                        _args.viaAdministracao = value_12;
                    } else { input.skip(fieldType); }
                    break;
                case 13:
                    if (fieldType === thrift.Thrift.Type.I64) {
                        const value_13: Int64 = input.readI64();
                        _args.localAplicacao = value_13;
                    } else { input.skip(fieldType); }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        return new VacinaRowThrift(_args);
    }
}
