/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
import * as LotacaoHeaderThrift from "./LotacaoHeaderThrift";
export interface IVariasLotacoesHeaderThriftArgs {
    lotacaoFormPrincipal: LotacaoHeaderThrift.LotacaoHeaderThrift;
}
export class VariasLotacoesHeaderThrift {
    public lotacaoFormPrincipal: LotacaoHeaderThrift.LotacaoHeaderThrift;
    constructor(args: IVariasLotacoesHeaderThriftArgs) {
        if (args != null && args.lotacaoFormPrincipal != null) {
            this.lotacaoFormPrincipal = args.lotacaoFormPrincipal;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[lotacaoFormPrincipal] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("VariasLotacoesHeaderThrift");
        if (this.lotacaoFormPrincipal != null) {
            output.writeFieldBegin("lotacaoFormPrincipal", thrift.Thrift.Type.STRUCT, 1);
            this.lotacaoFormPrincipal.write(output);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): VariasLotacoesHeaderThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.STRUCT) {
                        const value_1: LotacaoHeaderThrift.LotacaoHeaderThrift = LotacaoHeaderThrift.LotacaoHeaderThrift.read(input);
                        _args.lotacaoFormPrincipal = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.lotacaoFormPrincipal !== undefined) {
            return new VariasLotacoesHeaderThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read VariasLotacoesHeaderThrift from input");
        }
    }
}
