/* tslint:disable */
/* eslint-disable */
/*
 * Autogenerated by @creditkarma/thrift-typescript v3.7.6
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
*/
import * as thrift from "thrift";
export interface IVersaoThriftArgs {
    major: number;
    minor: number;
    revision: number;
}
export class VersaoThrift {
    public major: number;
    public minor: number;
    public revision: number;
    constructor(args: IVersaoThriftArgs) {
        if (args != null && args.major != null) {
            this.major = args.major;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[major] is unset!");
        }
        if (args != null && args.minor != null) {
            this.minor = args.minor;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[minor] is unset!");
        }
        if (args != null && args.revision != null) {
            this.revision = args.revision;
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Required field[revision] is unset!");
        }
    }
    public write(output: thrift.TProtocol): void {
        output.writeStructBegin("VersaoThrift");
        if (this.major != null) {
            output.writeFieldBegin("major", thrift.Thrift.Type.I32, 1);
            output.writeI32(this.major);
            output.writeFieldEnd();
        }
        if (this.minor != null) {
            output.writeFieldBegin("minor", thrift.Thrift.Type.I32, 2);
            output.writeI32(this.minor);
            output.writeFieldEnd();
        }
        if (this.revision != null) {
            output.writeFieldBegin("revision", thrift.Thrift.Type.I32, 3);
            output.writeI32(this.revision);
            output.writeFieldEnd();
        }
        output.writeFieldStop();
        output.writeStructEnd();
        return;
    }
    public static read(input: thrift.TProtocol): VersaoThrift {
        input.readStructBegin();
        let _args: any = {};
        while (true) {
            const ret: thrift.TField = input.readFieldBegin();
            const fieldType: thrift.Thrift.Type = ret.ftype;
            const fieldId: number = ret.fid;
            if (fieldType === thrift.Thrift.Type.STOP) {
                break;
            }
            switch (fieldId) {
                case 1:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_1: number = input.readI32();
                        _args.major = value_1;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 2:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_2: number = input.readI32();
                        _args.minor = value_2;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                case 3:
                    if (fieldType === thrift.Thrift.Type.I32) {
                        const value_3: number = input.readI32();
                        _args.revision = value_3;
                    }
                    else {
                        input.skip(fieldType);
                    }
                    break;
                default: {
                    input.skip(fieldType);
                }
            }
            input.readFieldEnd();
        }
        input.readStructEnd();
        if (_args.major !== undefined && _args.minor !== undefined && _args.revision !== undefined) {
            return new VersaoThrift(_args);
        }
        else {
            throw new thrift.Thrift.TProtocolException(thrift.Thrift.TProtocolExceptionType.UNKNOWN, "Unable to read VersaoThrift from input");
        }
    }
}
