import * as crypto from 'crypto';

/**
 * Utility for symmetric encryption/decryption using AES-256-GCM in Node.js
 * Compatible with WebCrypto API AES-GCM on the frontend.
 */

// Define standard algorithm parameters
const ALGORITHM = 'aes-256-gcm';
const IV_LENGTH = 12; // 96 bits standard for GCM
const AUTH_TAG_LENGTH = 16; // 128 bits
const PBKDF2_ITERATIONS = 100000;
const KEY_LENGTH = 32; // 256 bits

/**
 * Derives a 256-bit key from a passphrase using PBKDF2 (optional, if we use a direct base64 key we can skip this, 
 * but string passwords need derivation. We will assume the VITE_ENCRYPTION_KEY is a passphrase).
 */
function deriveKey(passphrase: string, salt: Buffer): Buffer {
    return crypto.pbkdf2Sync(passphrase, salt, PBKDF2_ITERATIONS, KEY_LENGTH, 'sha256');
}

/**
 * Decrypts a base64 encoded string generated by WebCrypto AES-GCM.
 * Expected format: base64( salt (16 bytes) + iv (12 bytes) + ciphertext + authTag (16 bytes) )
 */
export function decryptPayload(encryptedBase64: string, passphrase: string): any {
    try {
        const data = Buffer.from(encryptedBase64, 'base64');
        
        // Extract parts
        const salt = data.subarray(0, 16);
        const iv = data.subarray(16, 16 + IV_LENGTH);
        const authTag = data.subarray(data.length - AUTH_TAG_LENGTH, data.length);
        const encryptedText = data.subarray(16 + IV_LENGTH, data.length - AUTH_TAG_LENGTH);

        // Derive the same key used by frontend
        const key = deriveKey(passphrase, salt);

        // Decrypt
        const decipher = crypto.createDecipheriv(ALGORITHM, key, iv);
        decipher.setAuthTag(authTag);

        let decrypted = decipher.update(encryptedText);
        decrypted = Buffer.concat([decrypted, decipher.final()]);

        const jsonString = decrypted.toString('utf8');
        return JSON.parse(jsonString);
    } catch (error) {
        console.error("Decryption failed:", error);
        throw new Error("Falha na decriptação estrutural do payload de produção.");
    }
}
