import React, { useState } from 'react';
import { Card, Button, Input, Select, Badge, cn } from '../components/ui/BaseComponents';
import { MOCK_TICKETS, SUPPORT_CATEGORIES } from '../constants';
import { LifeBuoy, Plus, MessageSquare, Paperclip, CheckCircle, Clock, AlertCircle } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useApp } from '../context';
import { createSupportTicket, fetchUserTickets } from '../services/supportService';

export const Support: React.FC = () => {
    const [view, setView] = useState<'list' | 'create'>('list');
    const [tickets, setTickets] = useState<any[]>([]); // Start empty, rely on fetch or manual update
    const { user, currentUnit } = useApp(); // Need user context
    const [loading, setLoading] = useState(false);

    // Fetch tickets on load
    React.useEffect(() => {
        async function loadTickets() {
            if (user?.id || user?.professionalId) {
                // setLoading(true); // Optional: global loading or local list loading
                const data = await fetchUserTickets(user.id || user.professionalId);
                setTickets(data);
                // setLoading(false);
            }
        }
        loadTickets();
    }, [user?.id, user?.professionalId]);

    // Form Data
    const [formData, setFormData] = useState({
        category: '',
        subject: '',
        description: '',
        file: null as File | null
    });

    const handleSubmit = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!user) return;

        setLoading(true);

        try {
            await createSupportTicket({
                category: SUPPORT_CATEGORIES.find(c => c.value === formData.category)?.label || 'Outro',
                subject: formData.subject,
                description: formData.description,
                user: {
                    ...user,
                    // Ensure unit context is passed if available, prioritising currentUnit
                    units: currentUnit ? [currentUnit] : user.units
                },
                file: formData.file
            });

            // Optimistic update or success message
            setTickets(prev => [{
                id: 'Novo', // ID is generated by backend
                date: new Date().toISOString(),
                category: SUPPORT_CATEGORIES.find(c => c.value === formData.category)?.label || 'Outro',
                subject: formData.subject,
                description: formData.description,
                status: 'open',
                lastUpdate: new Date().toISOString()
            }, ...prev]);

            setView('list');
            setFormData({ category: '', subject: '', description: '', file: null });
        } catch (error) {
            console.error("Erro ao enviar chamado:", error);
            // Handle error (alert or toast)
        } finally {
            setLoading(false);
        }
    };

    const getStatusBadge = (status: string) => {
        switch (status) {
            case 'open':
                return <Badge variant="warning">Em Aberto</Badge>;
            case 'answered':
                return <Badge variant="success">Respondido</Badge>;
            case 'closed':
                return <Badge variant="neutral">Fechado</Badge>;
            default:
                return <Badge>Desconhecido</Badge>;
        }
    };

    return (
        <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="max-w-4xl mx-auto space-y-6">

            {/* Header */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
                <div>
                    <h1 className="text-2xl font-bold text-gray-900 dark:text-white flex items-center gap-2">
                        <LifeBuoy className="text-medical-600 dark:text-medical-400" />
                        Suporte Técnico
                    </h1>
                    <p className="text-gray-500 dark:text-gray-400 text-sm mt-1">
                        Gerenciado por <span className="font-semibold text-gray-700 dark:text-gray-300">GAX Tecnologia</span>
                    </p>
                </div>
                {view === 'list' && (
                    <Button onClick={() => setView('create')} className="shadow-lg shadow-medical-500/20">
                        <Plus size={18} className="mr-2" /> Novo Chamado
                    </Button>
                )}
            </div>

            <AnimatePresence mode="wait">
                {view === 'list' ? (
                    <motion.div
                        key="list"
                        initial={{ opacity: 0, x: -20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: -20 }}
                        className="space-y-4"
                    >
                        {tickets.length === 0 ? (
                            <Card className="p-8 text-center text-gray-500">
                                <MessageSquare size={48} className="mx-auto mb-4 opacity-20" />
                                <p>Nenhum chamado registrado.</p>
                            </Card>
                        ) : (
                            tickets.map(ticket => (
                                <Card key={ticket.id} className="p-5 hover:shadow-md transition-shadow cursor-pointer group">
                                    <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-3">
                                        <div className="flex items-center gap-3">
                                            <span className="font-mono text-xs font-bold bg-gray-100 dark:bg-gray-700 px-2 py-1 rounded text-gray-600 dark:text-gray-300">
                                                {ticket.id}
                                            </span>
                                            {getStatusBadge(ticket.status)}
                                            <span className="text-xs text-gray-400 flex items-center gap-1">
                                                <Clock size={12} /> {new Date(ticket.date).toLocaleDateString('pt-BR')}
                                            </span>
                                        </div>
                                        <span className="text-xs font-medium text-medical-600 dark:text-medical-400 bg-medical-50 dark:bg-medical-900/20 px-2 py-1 rounded-full self-start sm:self-auto">
                                            {ticket.category}
                                        </span>
                                    </div>
                                    <h3 className="font-bold text-gray-900 dark:text-white mb-2 group-hover:text-medical-600 transition-colors">
                                        {ticket.subject}
                                    </h3>
                                    <p className="text-sm text-gray-600 dark:text-gray-400 line-clamp-2">
                                        {ticket.description}
                                    </p>
                                    <div className="mt-4 pt-3 border-t border-gray-100 dark:border-gray-700 flex justify-between items-center text-xs text-gray-400">
                                        <span>Última atualização: {new Date(ticket.lastUpdate).toLocaleDateString()} às {new Date(ticket.lastUpdate).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span>
                                    </div>
                                </Card>
                            ))
                        )}
                    </motion.div>
                ) : (
                    <motion.div
                        key="create"
                        initial={{ opacity: 0, x: 20 }}
                        animate={{ opacity: 1, x: 0 }}
                        exit={{ opacity: 0, x: 20 }}
                    >
                        <Card className="p-6 border-t-4 border-t-medical-500">
                            <h2 className="text-lg font-bold text-gray-900 dark:text-white mb-6">Abrir Novo Chamado</h2>

                            <div className="bg-blue-50 dark:bg-blue-900/20 border border-blue-100 dark:border-blue-800 rounded-lg p-4 mb-6 flex gap-3">
                                <div className="shrink-0 text-blue-500 mt-0.5">
                                    <AlertCircle size={20} />
                                </div>
                                <div className="text-sm text-blue-700 dark:text-blue-300">
                                    <p className="font-semibold mb-1">Direcionado a: Suporte Técnico ProBPA - GAX Tecnologia</p>
                                    <p>Nossa equipe responderá em até 24 horas úteis. Para urgências, entre em contato via WhatsApp.</p>
                                </div>
                            </div>

                            <form onSubmit={handleSubmit} className="space-y-5">
                                <div className="grid grid-cols-1 md:grid-cols-2 gap-5">
                                    <Select
                                        label="Tipo da Solicitação"
                                        required
                                        value={formData.category}
                                        onChange={e => setFormData({ ...formData, category: e.target.value })}
                                        options={[{ value: '', label: 'Selecione...' }, ...SUPPORT_CATEGORIES]}
                                    />
                                    <Input
                                        label="Assunto Resumido"
                                        required
                                        placeholder="Ex: Erro ao sincronizar BPA-I"
                                        value={formData.subject}
                                        onChange={e => setFormData({ ...formData, subject: e.target.value })}
                                    />
                                </div>

                                <div className="space-y-1.5">
                                    <label className="text-sm font-medium text-gray-700 dark:text-gray-300 ml-1">Descrição Detalhada</label>
                                    <textarea
                                        required
                                        rows={6}
                                        className="w-full rounded-xl border border-gray-200 dark:border-gray-700 bg-white dark:bg-gray-800 px-3 py-2 text-sm focus:ring-2 focus:ring-medical-500 focus:outline-none dark:text-white"
                                        placeholder="Descreva o problema ou dúvida com o máximo de detalhes possível..."
                                        value={formData.description}
                                        onChange={e => setFormData({ ...formData, description: e.target.value })}
                                    />
                                </div>

                                <div className="space-y-1.5">
                                    <label className="text-sm font-medium text-gray-700 dark:text-gray-300 ml-1">Anexo (Imagem ou Arquivo)</label>
                                    <div className="border-2 border-dashed border-gray-300 dark:border-gray-700 rounded-xl p-6 flex flex-col items-center justify-center text-gray-500 hover:bg-gray-50 dark:hover:bg-gray-800/50 transition-colors cursor-pointer relative">
                                        <input
                                            type="file"
                                            className="absolute inset-0 opacity-0 cursor-pointer"
                                            onChange={e => setFormData({ ...formData, file: e.target.files?.[0] || null })}
                                        />
                                        <Paperclip size={24} className="mb-2" />
                                        {formData.file ? (
                                            <span className="text-medical-600 font-medium">{formData.file.name}</span>
                                        ) : (
                                            <span className="text-sm">Clique para adicionar print ou documento</span>
                                        )}
                                    </div>
                                </div>

                                <div className="flex gap-3 pt-4">
                                    <Button type="button" variant="ghost" onClick={() => setView('list')} disabled={loading}>
                                        Cancelar
                                    </Button>
                                    <Button type="submit" className="flex-1" isLoading={loading}>
                                        Enviar Solicitação
                                    </Button>
                                </div>
                            </form>
                        </Card>
                    </motion.div>
                )}
            </AnimatePresence>
        </motion.div>
    );
};